
<?php $baseUrl = $this->basePath(); 
$builderList = $this->routeHelper()->indexmodel()->getBuilderList();
$cities = $this->routeHelper()->indexmodel()->getCityList();
$citieList = $this->routeHelper()->indexmodel()->getCityList();


//echo '<pre>';print_r($builderList); EXIT;

//echo $builderList[0]['builder_footer_image'];exit;


?>
<!-- Top Builder========================================================================================== -->
  <!-- section 72 Builder--->
  <div class="clearfix margin_top5"></div>
  <div class="featured_section72">
    <div class="container">
      <h2 class="title27 roboto" style="color:#fff;"  align="center">Top Builder
        <div class="line white"></div>
      </h2>
      <div id="owl-demo14" class="owl-carousel">
          <?php if(count($builderList)>=4){?>
        <div class="item" align="center">
          <div class="one_fourth"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[0]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[0]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
          <div class="one_fourth"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[1]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[1]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
          <div class="one_fourth"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[2]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[2]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
          <div class="one_fourth last"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[3]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[3]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
        </div>
          <?php }?>
          <?php if(count($builderList)>=8){?>
        <div class="item">
          <div class="one_fourth"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[4]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[4]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
          <div class="one_fourth"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[5]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[5]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
          <div class="one_fourth"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[6]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[6]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
          <div class="one_fourth last"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[7]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[7]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
        </div>
          <?php }?>
          <?php if(count($builderList)>=12){?>
        <div class="item">
          <div class="one_fourth"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[8]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[8]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
          <div class="one_fourth"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[9]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[9]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
          <div class="one_fourth"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[10]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[10]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
          <div class="one_fourth last"><a href="<?php echo $baseUrl;?>/builders/<?php echo $builderList[11]['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $builderList[11]['builder_footer_image']?>" alt="" width="227" height="65" /></a></div>
        </div>
          <?php }?>
        <!-- end slide -->
      </div>
    </div>
  </div>
  <!-- end of section 72 Builder--->
  
  <!-- Footer=============================================================================================== -->
  <footer class="footer stwo">
<!--<div class="fbsocials">
<a href="#" class="fb"><i class="fa fa-facebook"></i></a>
<a href="#" class="tw"><i class="fa fa-twitter"></i></a>
<a href="#" class="in"><i class="fa fa-linkedin"></i></a>
</div>-->
    <div class="container">
      <div class="one_fourth animate" data-anim-type="fadeInUp" data-anim-delay="300">
        <h4><a href="<?php echo $baseUrl;?>/homepage"><img src="<?php echo $baseUrl;?>/public/images/logo/aadinath_logo.png" alt="" /></a></h4>
        <ul class="faddress" style="padding-top:10px;">
          <li></li>
          <li><i class="fa fa-map-marker fa-lg"></i>&nbsp; A-10, Sector-63, Noida.</li>
          <li><i class="fa fa-phone"></i>&nbsp; 0120 - 4256308</li>
          <li><i class="fa fa-phone"></i>&nbsp; +91 - 9650 797 111</li>
          <li><i class="fa fa-envelope"></i>&nbsp; crm@aadinathindia.com</li>
          <li>&nbsp;</li>
         
        </ul>
      </div>
      <!-- end address -->
      <div class="one_fourth animate" data-anim-type="fadeInUp" data-anim-delay="400">
        <div class="qlinks">
          <h4>Useful Links</h4>
          <ul>
           <li><a href="index.html"><i class="fa fa-angle-right"></i> Home</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> About Us</a></li>            
            <li><a href="all-builders.html"><i class="fa fa-angle-right"></i> Builders</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Media</a></li>   
            <li><a href="careers.html"><i class="fa fa-angle-right"></i> Careers</a></li>
            <li><a href="contact-us.html"><i class="fa fa-angle-right"></i> Contact Us</a></li>
            <li><a href="privacy-policy.html"><i class="fa fa-angle-right"></i> Privacy Policy</a></li>
          </ul>
        </div>
      </div>
      <!-- end links -->
      <div class="one_fourth animate" data-anim-type="fadeInUp" data-anim-delay="500">
        <div class="qlinks">
          <h4>Projects in india</h4>
          <ul>
             <?php foreach($cities as $city){?>
              <li><a href="<?php echo $baseUrl;?>/projects-in-<?php echo $city['citySlug']?>"><i class="fa fa-angle-right"></i> Projects in <?php echo $city['city_name']?></a></li>
             <?php }?>
          </ul>
        </div>
      </div>
      <!-- end site info -->
      <div class="one_fourth last animate" data-anim-type="fadeInUp" data-anim-delay="600">
        <div class="qlinks">
          <h4>Resale Property</h4>
          <ul>
              <?php foreach($citieList as $city){?>
              <li><a href=""><i class="fa fa-angle-right"></i> Resale in <?php echo $city['city_name']?></a></li>
             <?php }?>
          </ul>
        </div>
      </div>
      <!-- end flickr -->
    </div>
    <!-- end footer -->
    <div class="clearfix"></div>
    <div class="copyright_info two">
      <div class="container">
        <div class="clearfix divider_dashed10"></div>
        <div class="one_half animate" data-anim-type="fadeInRight" data-anim-delay="300"> Copyright &copy; <?php echo date('Y')?> aadinathindia.com. All rights reserved.</div>
        <div class="one_half last">
          <ul class="footer_social_links">
            <li class="animate" data-anim-type="zoomIn" data-anim-delay="300"><a href="#">Powerd by:</a></li>
            <li class="animate" data-anim-type="zoomIn" data-anim-delay="300"><a href="http://discoverysolutions.in"><img src="<?php echo $baseUrl;?>/public/images/logo/discovery-logo.png"></a></li>
          </ul>
        </div>
      </div>
    </div>
    <!-- end copyright info -->
  </footer>
  
  
  <!-- scroll to top======================================================================================== -->  
  <div class="scrollup" style="cursor:pointer"></div><!-- end scroll to top of the page-->
  
 

<!-- ######### JS FILES ######### -->
<!-- get jQuery used for the theme -->
<input id='projectBaseUrl' type='hidden' value="<?php echo $baseUrl?>"/>

<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/universal/jquery.js"></script>
<script src="<?php echo $baseUrl;?>/public/js/style-switcher/styleselector.js"></script>
<script src="<?php echo $baseUrl;?>/public/js/animations/js/animations.min.js" type="text/javascript"></script>
<script src="<?php echo $baseUrl;?>/public/js/mainmenu/bootstrap.min.js"></script>
<script src="<?php echo $baseUrl;?>/public/js/mainmenu/customeUI.js"></script>
<script src="<?php echo $baseUrl;?>/public/js/masterslider/jquery.easing.min.js"></script>



 
  <script type="text/javascript">
    $('#myModal').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
  
 </script>

 

<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" >Interested in <span id='callBackPrjName'>Parsvnath Paramount</span>?</h4>
      </div>
      <div class="modal-body">
        <form>
  <div class="form-group">
    <label >Email address</label>
    <input type="email" class="form-control" id="callBackInputEmail" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label >Mobile No.</label>
    <input type="text" class="form-control" id="callBackInputMobile" placeholder="Mobile No.">
  </div>
  <input type="hidden"  id="callBackProjectId" >
</form>
      </div>
      <div class="modal-footer">
          <img id="callBackLoader" style="display:none;margin-right:20px;" src="<?php echo $baseUrl;?>/public/images/lightbox-ico-loading.gif">
          <button id="callBackSubmit" type="button" class="btn btn-danger" onclick="return submitCallBack()">GET CALL BACK</button>
               
      </div>
      
    </div>
  </div>
</div>
 <!----LOGIN FORM---->
 <div class="modal fade" id="loginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">ACCOUNT LOGIN</h4>
      </div>
      <div class="modal-body">
        <form action="" method="post">
        <div class="form-group">
          <label for="">Email address</label>
          <input type="email" class="form-control userLoginEmail" placeholder="Enter your Email Address" value="<?php if(isset($_COOKIE['cookieEmail'])) echo $_COOKIE['cookieEmail'];?>">
        </div>        
        <div class="form-group">
          <label for="">Password</label>
          <input type="password" class="form-control userLoginPassword" placeholder="Enter your Password" value="<?php if(isset($_COOKIE['cookiePswd'])) echo $_COOKIE['cookiePswd'];?>">
        </div>
        <div class="checkbox">
          <label>
              <input type="checkbox" id="remember_me" <?php if(isset($_COOKIE['cookieEmail'])) echo 'checked="checked"';?>> Remember Me      
          </label> | <a onclick="return forgotPassword();" class="cursor">Forgot Password?</a>
        </div>  
      </form>

     </div>
      <div class="modal-footer">
       <div class="col-md-12">
        <button type="button" class="btn btn-danger userLogin">LOGIN NOW!</button>
        <button type="button" class="btn btn-default" onclick="return openSignUp()">SIGN UP</button>
       </div>
       <div class="clearfix"></div>
       <div class="col-md-12 login-main-add">
       <a href="#"><div class="col-md-6 text-center text-primary login-fb-bttn"><i class="fa fa-facebook"></i> Login with Facebook</div></a>
       <a id="gp_login" href="javascript:void(0)" onclick="javascript:googleAuth()"><div class="col-md-6 text-center text-danger login-gplus-bttn"><i class="fa fa-google-plus"></i> Login with Google+</div></a>
       <!--<a href="#"><div class="col-md-6 text-center text-danger login-gplus-bttn"><i class="fa fa-google-plus"></i> Login with Google+</div></a>
       <a id="gp_login" href="javascript:void(0)" onclick="javascript:googleAuth()"><div class="col-md-6 text-center text-danger "><i class="fa fa-google-plus"></i> Login with Google+ new</div></a>
        <pre id="userdata">

        </pre>-->
       </div>
      </div>
    </div>
  </div>
</div>
<!----SIGN UP FORM---->
<div class="modal fade" id="signUpForm" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" >ACCOUNT SIGN UP</h4>
      </div>
    <div class="modal-body">
    <form action="" method="post">
        <div class="form-group">
            <label >Name</label>
            <input type="text" class="form-control userName" value="" placeholder="Enter your Full Name">
        </div>
        <div class="form-group">
            <label >Password</label>
            <input type="password" class="form-control userPassword" value=""  placeholder="Enter your Password">
        </div>
        <div class="form-group">
            <label for="">Email address</label>
            <input type="email" class="form-control userEmail" placeholder="Enter your Email Address">
        </div>           
        <div class="form-group">
            <label for="">Mobile No.</label>
            <input type="text" class="form-control userMobile" placeholder="Enter your Mobile No.">
        </div>
    </form>
    </div>
      <div class="modal-footer">
        <img id="signUpLoader" style="display:none;margin-right:20px;" src="<?php echo $baseUrl;?>/public/images/lightbox-ico-loading.gif">  
        <button type="button" class="btn btn-danger signUpButton">SIGN UP</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
      </div>
    </div>
  </div>
</div>

<!----FORGOT PASSWORD FORM---->
<div class="modal fade" id="forgotPwswd" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content ">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">RESET PASSWORD</h4>
      </div>
        <div class="modal-body messageBody">
        <div class="modal-body">
        <p>Please enter the email address you signed up with and we'll send you a password reset link.</p>
        <!--<p>We have sent the password reset instructions on satish@discoverysolutions.in. Kindly follow the instructions in the mail for resetting your password.</p>-->
        <form>         
        <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="forgotEmail" placeholder="Enter your Email Address">
        </div>   
        </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger forgotPswd">RESET PASSWORD</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">CANCEL</button>
        </div>
        </div>
    </div>
  </div>
</div>
<script src="<?php echo $baseUrl;?>/public/js/masterslider/masterslider.min.js"></script>
<script type="text/javascript">
(function($) {
 "use strict";
	var slider = new MasterSlider();
	
	slider.setup('masterslider' , {
		 width:1400,    // slider standard width
		 height:539,   // slider standard height
		 space:0,
		 speed:27,
		 layout:'fullwidth',
		 loop:true,
		 preload:0,
		 autoplay:true,
		 view:"scale"
	});
})(jQuery);
</script>
<script src="<?php echo $baseUrl;?>/public/js/scrolltotop/totop.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/mainmenu/sticky.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/mainmenu/modernizr.custom.75180.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/cubeportfolio/jquery.cubeportfolio.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/cubeportfolio/main5.js"></script>
<script src="<?php echo $baseUrl;?>/public/js/carouselowl/owl.carousel.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/accordion2/custom.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/universal/custom.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/jquery.disablescroll.js"></script>