<?php $baseUrl = $this->basePath(); ?>
<div class="featured_section72">
    <div class="container">
      <h2 class="title27 roboto" style="color:#fff;"  align="center">Top Builder
        <div class="line white"></div>
      </h2>
      <div id="owl-demo14" class="owl-carousel">
        <div class="item" align="center">
          <div class="one_fourth"> <img src="<?php echo $baseUrl;?>/images/builders/unnati-logo.png" alt="" /></div>
          <!-- end section -->
          <div class="one_fourth"> <img src="<?php echo $baseUrl;?>/images/builders/prateek-group-logo.png" alt="" /></div>
          <!-- end section -->
          <div class="one_fourth"> <img src="<?php echo $baseUrl;?>/images/builders/supertech.png" alt="" /></div>
          <!-- end section -->
          <div class="one_fourth last"> <img src="<?php echo $baseUrl;?>/images/builders/sikka.png" alt="" /></div>
          <!-- end section -->
        </div>
        <!-- end slide -->
        <div class="item">
          <div class="one_fourth"> <img src="<?php echo $baseUrl;?>/images/builders/unnati-logo.png" alt="" /></div>
          <!-- end section -->
          <div class="one_fourth"> <img src="<?php echo $baseUrl;?>/images/builders/prateek-group-logo.png" alt="" /></div>
          <!-- end section -->
          <div class="one_fourth"> <img src="<?php echo $baseUrl;?>/images/builders/supertech.png" alt="" /></div>
          <!-- end section -->
          <div class="one_fourth last"> <img src="<?php echo $baseUrl;?>/images/builders/sikka.png" alt="" /></div>
          <!-- end section -->
        </div>
        <!-- end slide -->
        <div class="item">
          <div class="one_fourth"> <img src="<?php echo $baseUrl;?>/images/builders/unnati-logo.png" alt="" /></div>
          <!-- end section -->
          <div class="one_fourth"> <img src="<?php echo $baseUrl;?>/images/builders/prateek-group-logo.png" alt="" /></div>
          <!-- end section -->
          <div class="one_fourth"> <img src="<?php echo $baseUrl;?>/images/builders/supertech.png" alt="" /></div>
          <!-- end section -->
          <div class="one_fourth last"> <img src="<?php echo $baseUrl;?>/images/builders/sikka.png" alt="" /></div>
          <!-- end section -->
        </div>
        <!-- end slide -->
      </div>
    </div>
  </div>
  <!-- end of section 72 Builder--->
  
  
   <footer class="footer stwo">
<!--<div class="fbsocials">
<a href="#" class="fb"><i class="fa fa-facebook"></i></a>
<a href="#" class="tw"><i class="fa fa-twitter"></i></a>
<a href="#" class="in"><i class="fa fa-linkedin"></i></a>
</div>-->
    <div class="container">
      <div class="one_fourth animate" data-anim-type="fadeInUp" data-anim-delay="300">
        <h4><img src="<?php echo $baseUrl;?>/images/logo/aadinath_logo.png" alt="" /></h4>
        <ul class="faddress" style="padding-top:10px;">
          <li></li>
          <li><i class="fa fa-map-marker fa-lg"></i>&nbsp; A-61, 1st Floor, Sector-65, Noida.</li>
          <li><i class="fa fa-phone"></i>&nbsp; 0120 - 4256308</li>
          <li><i class="fa fa-phone"></i>&nbsp; +91 - 9810636461</li>
          <li><i class="fa fa-envelope"></i>&nbsp; director@urhomesindia.com</li>
          <li>&nbsp;</li>
         
        </ul>
      </div>
      <!-- end address -->
      <div class="one_fourth animate" data-anim-type="fadeInUp" data-anim-delay="400">
        <div class="qlinks">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="#"><i class="fa fa-angle-right"></i> Home</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> About Us</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Services</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Builder</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Emi-Calculator</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Resource</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> NRI Service</a></li>
          </ul>
        </div>
      </div>
      <!-- end links -->
      <div class="one_fourth animate" data-anim-type="fadeInUp" data-anim-delay="500">
        <div class="qlinks">
          <h4>Projects in india</h4>
          <ul>
            <li><a href="#"><i class="fa fa-angle-right"></i> Projects in Noida</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Projects in Greater Noida</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Projects in Raj Nagar Extension</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Projects in Indirapuram</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Projects in Noida Expressway</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Projects in Ghaziabad</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Projects in Gurgaon</a></li>
          </ul>
        </div>
      </div>
      <!-- end site info -->
      <div class="one_fourth last animate" data-anim-type="fadeInUp" data-anim-delay="600">
        <div class="qlinks">
          <h4>Resale Property</h4>
          <ul>
            <li><a href="#"><i class="fa fa-angle-right"></i> Resale in Noida</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Resale in Greater Noida</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Resale in Raj Nagar Extension</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Resale in Indirapuram</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Resale in Noida Expressway</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Resale in Ghaziabad</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Resale in Gurgaon</a></li>
          </ul>
        </div>
      </div>
      <!-- end flickr -->
    </div>
    <!-- end footer -->
    <div class="clearfix"></div>
    <div class="copyright_info two">
      <div class="container">
        <div class="clearfix divider_dashed10"></div>
        <div class="one_half animate" data-anim-type="fadeInRight" data-anim-delay="300"> Copyright © 2015 aadinath.com. All rights reserved. <a href="#">Terms of Use</a> | <a href="#">Privacy Policy</a> </div>
        <div class="one_half last">
          <ul class="footer_social_links">
            <li class="animate" data-anim-type="zoomIn" data-anim-delay="300"><a href="#">Powerd by:</a></li>
            <li class="animate" data-anim-type="zoomIn" data-anim-delay="300"><a href="#"><img src="<?php echo $baseUrl;?>/images/logo/discovery-logo.png"></a></li>
          </ul>
        </div>
      </div>
    </div>
    <!-- end copyright info -->
  </footer>
  
  
  