<?php $baseUrl      = $this->basePath(); 
$hotdealbanner      = $this->routeHelper()->indexmodel()->projectBanner(1);
$residentialPrjcts  = $this->routeHelper()->indexmodel()->projectByCategory(1);
$commercialPrjcts   = $this->routeHelper()->indexmodel()->projectByCategory(2);

?>

<!doctype html>
<html lang="en-gb" class="no-js">
<head>
<title id="pageTitle">Aadinath | One Stop Real State Portal</title>
<link rel="shortcut icon" type="image/png" href="<?php echo $baseUrl;?>/public/images/logo/favicon.png"/>
<link rel="shortcut icon" href="<?php echo $baseUrl;?>/public/images/favicon.html">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dancing+Script:400,700' rel='stylesheet' type='text/css'>
<!-- custom -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/custom.css">
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/reset.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/style.css" type="text/css" />
<!-- font awesome icons -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/font-awesome/css/font-awesome.min.css">
<!-- simple line icons -->
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/css/simpleline-icons/simple-line-icons.css" media="screen" />
<!-- et linefont icons -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/et-linefont/etlinefont.css">
<!-- animations -->
<link href="<?php echo $baseUrl;?>/public/js/animations/css/animations.min.css" rel="stylesheet" type="text/css" media="all" />
<!-- responsive devices styles -->
<link rel="stylesheet" media="screen" href="<?php echo $baseUrl;?>/public/css/responsive-leyouts.css" type="text/css" />
<!-- shortcodes -->
<link rel="stylesheet" media="screen" href="<?php echo $baseUrl;?>/public/css/shortcodes.css" type="text/css" />
<!-- style switcher -->
<link rel = "stylesheet" media = "screen" href = "<?php echo $baseUrl;?>/public/js/style-switcher/color-switcher.css" />
<!-- mega menu -->
<link href="<?php echo $baseUrl;?>/public/js/mainmenu/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo $baseUrl;?>/public/js/mainmenu/demo.css" rel="stylesheet">
<link href="<?php echo $baseUrl;?>/public/js/mainmenu/menu11.css" rel="stylesheet">
<!-- MasterSlider -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/js/masterslider/style/masterslider.css" />
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/js/masterslider/skins/default/style.css" />
<!-- cubeportfolio -->
<link rel="stylesheet" type="text/css" href="js/cubeportfolio/cubeportfolio.min.css">
<!-- owl carousel -->
<link href="<?php echo $baseUrl;?>/public/js/carouselowl/owl.transitions.css" rel="stylesheet">
<link href="<?php echo $baseUrl;?>/public/js/carouselowl/owl.carousel.css" rel="stylesheet">
<!-- accordion2 -->
<link href="<?php echo $baseUrl;?>/public/js/accordion2/style.css" rel="stylesheet" />

<link rel="stylesheet" media="screen" href="<?php echo $baseUrl;?>/public/bootstrap/css/bootstrap.min.css" type="text/css" />

</head>
<body>
<div class="site_wrapper" style="position: absolute;">
  <div class="top_section">
    <div class="container">
      <div class="left">
        <!-- Logo -->
        <div><a href="<?php echo $baseUrl ?>" id="logo"></a></div>
      </div>
      <div class="right"> <i class="fa fa-envelope"></i>&nbsp; crm@aadinathindia.com <i class="fa fa-phone-square"></i>&nbsp; +91-9650 797 111
        <ul class="topsocial">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- end top navigation links -->
  <div class="clearfix"></div>
  <header class="header">
    <div class="container">
      <!-- Navigation Menu -->
      <div class="menu_main_full">
        <div class="navbar yamm navbar-default-index">
          <div class="navbar-header">
            <div class="navbar-toggle .navbar-collapse .pull-right " data-toggle="collapse" data-target="#navbar-collapse-1"  > <span>Menu</span>
              <button type="button" > <i class="fa fa-bars"></i></button>
            </div>
          </div>
  

<style>
    
    .username-login{
        color:#fff;
    }
    .username-login a{
        color:#fff;
        text-decoration: none;
    }
    .nav .caret {
    border-bottom-color: #fff;
    border-top-color: #fff;
    }
    .nav a:hover .caret{
        border-bottom-color:#fff;
        border-top-color: #fff;        
    }
    .nav .open > a .caret, .nav .open > a:hover .caret, .nav .open > a:focus .caret {
    border-bottom-color: #fff;
    border-top-color: #fff;
}
</style>

		 <div id="navbar-collapse-1" class="navbar-collapse collapse">
            <nav>
              <ul class="nav navbar-nav">
                <!--Home-->
                <li class="dropdown yamm-fw"> <a href="<?php echo $baseUrl;?>/homepage" class="homeMenu active">Home</a></li>
                <!--About us-->
                <li class="dropdown"><a href="<?php echo $baseUrl;?>/about-us" class="AboutUsMenu">About us</a>
                </li>
                <!--Project-->
                <li class="dropdown yamm-fw"> <a class="dropdown-toggle cursor">Projects</a>

                  <ul class="dropdown-menu">
                    <li>
                      <!-- Content container to add padding -->
                      <div class="yamm-content">
                        <div class="row">
                          <ul class="col-sm-6 col-md-3 list-unstyled">
                            <li>
                              <p>Residential Projects</p>
                            </li>
                            <?php foreach($residentialPrjcts as $res){?>
                            <li><a href="<?php echo $baseUrl;?>/projects/<?php echo $res['projectSlug']?>"><i class="fa fa-caret-right"></i><?php echo $res['project_title']?></a></li>
                            <?php }?>
                            <li><a href="<?php echo $baseUrl;?>/front-end/index/projectbycity?propCatId=1"><i class="fa fa-caret-right"></i> For More Projects <em>Click</em></a></li>
                          </ul>
                          <ul class="col-sm-6 col-md-3 list-unstyled">
                            <li>
                              <p>Commercial Projects</p>
                            </li>
                            <?php foreach($commercialPrjcts as $res){?>
                            <li><a href="<?php echo $baseUrl;?>/projects/<?php echo $res['projectSlug']?>"><i class="fa fa-caret-right"></i><?php echo $res['project_title']?></a></li>
                            <?php }?>
                            <li><a href="<?php echo $baseUrl;?>/front-end/index/projectbycity?propCatId=2"><i class="fa fa-caret-right"></i> For More Projects <em>Click</em></a></li>
                          </ul>
                          <ul class="col-sm-6 col-md-3 last list-unstyled nav-project-img-ul-bordr">
                            <li>
                              <p>Hot Deals</p>
                            </li>
                            <li class="nav-project-img-bg"><a href="<?php echo $baseUrl;?>/projects/<?php echo $hotdealbanner[0]['projectSlug']?>"><img width="194" height="184" src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $hotdealbanner[0]['banner_image']?>" class="nav-project-img-border"></a></li>
                            <li class="nav-project-img-bg"><a href="<?php echo $baseUrl;?>/projects/<?php echo $hotdealbanner[1]['projectSlug']?>"><img width="194" height="184" src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $hotdealbanner[1]['banner_image']?>" class="nav-project-img-border"></a></li>
                          </ul>
                          <ul class="col-sm-6 col-md-3 last list-unstyled ">
                            <li><p></p></li>
                            <li class="nav-project-img-bg"><a href="<?php echo $baseUrl;?>/projects/<?php echo $hotdealbanner[2]['projectSlug']?>"><img width="194" height="184" src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $hotdealbanner[2]['banner_image']?>" class="nav-project-img-border"></a></li>
                            <li class="nav-project-img-bg"><a href="<?php echo $baseUrl;?>/projects/<?php echo $hotdealbanner[3]['projectSlug']?>"><img width="194" height="184" src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $hotdealbanner[3]['banner_image']?>" class="nav-project-img-border"></a></li>
                          </ul>
                        </div>
                      </div>
                    </li>
                  </ul>
                </li>
                
                <!--Builders-->
                <li class="dropdown"> <a href="<?php echo $baseUrl;?>/builders" class="dropdown-toggle">Builders </a></li>
                <!--Media-->
                <li class="dropdown"><a href="#" class="dropdown-toggle">Media</a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Press Coverage</a></li>
                    <li><a href="#">Press Releases</a></li>
                    <li><a href="#">Events</a></li>
                  </ul>
                </li>
               
                
                <!--Careers-->
                <li class="dropdown"> <a href="<?php echo $baseUrl;?>/careers" class="CareersMenu">Careers </a></li>
                <!--Contact us-->
                <li class="dropdown"><a href="<?php echo $baseUrl;?>/contact-us" class="ContactUsMenu">Contact us</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <!-- end Navigation Menu -->
      <?php 

       $auth = new \Zend\Authentication\AuthenticationService();
       if(!$auth->hasIdentity()){
           ?>
      <div class="menu_rlinks"> <a href="#" class="mrbut cart-tab" data-toggle="modal"  onclick="return openLoginForm()">LOGIN</a> </div>
      <?php }else{
          $identity = $auth->getIdentity();
          $nameArr = explode(' ',$identity->username);
          $userName = (count($nameArr)) ? $nameArr[0] : $identity->username;
            
           // $auth->clearIdentity();
//            echo '<pre>';
//            print_r($identity);
//            exit('Login Successfull');
          
          
          ?>
      <div class="menu_rlinks"> 
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown username-login">
            <a href="#" class="dropdown-toggle login-username" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> <?php echo $userName?> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">           
            <li class="divider"></li>
            <li><a href="<?php echo $baseUrl;?>/user/portfolio"><span class="glyphicon glyphicon-user"></span> My Portfolio</a></li>
            <li class="divider"></li>
            <li><a href="<?php echo $baseUrl;?>/user/enquired-properties"><span class="glyphicon glyphicon-circle-arrow-right"></span> Enquired Properties</a></li>
            <li class="divider"></li>
            <li><a href="<?php echo $baseUrl;?>/user/account-settings"><span class="glyphicon glyphicon-cog"></span> Account Settings</a></li>
            <li class="divider"></li>
            <li><a href="javascript:void(0)"onclick="return userLogout();"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
          </ul>
        </li>                     
      </ul>
      </div> 
      <?php }?>
      <!-- end menu right links -->
    </div>
  </header>
  <div class="clearfix"></div>          
            
            
            
            
    <?php echo $this->layout()->content;?>     
	<?php echo $this->partial("footer"); ?>
<div id='backgroundImage' style="height:4000px; margin:0; padding:0; position:fixed; margin-top:-800px;">
 
 <div id="style-selector" style="left:-225px;">
<div class="style-selector-wrapper">
<span class="title">MENU</span>
<div>        
<br /><br />

<span class="title-sub2"><strong>Aadinath Guide <br>(Complete Property Guide)</strong></span>
<ul class="styles" style="border-bottom: none;">
    <li><a href="<?php echo $baseUrl?>/faq" class="demolinks">- FAQs</a></li>
    <li><a href="<?php echo $baseUrl?>/home-loan" class="demolinks">- Home Loan</a></li>
    <li><a href="<?php echo $baseUrl?>/vaastu-tips" class="demolinks">- Vaastu Tips</a></li>
    <li><a href="<?php echo $baseUrl?>/emi-calculator" class="demolinks">- EMI Calculator</a></li>
	<li><a href="<?php echo $baseUrl?>/nri-services" class="demolinks">- NRI Services</a></li>
    <li><a href="#" class="demolinks">- Blog</a></li>
</ul>
<span class="title-sub2">Need Any Help? <br><b>Call us: +91-9650 797 111</b></span>


<a href="#" class="close icon-chevron-right"></a>  
    
</div>
</div>
</div>
 </div>

<script src="<?php echo $baseUrl;?>/public/projectScripts/index/users.js" type="text/javascript"></script>  
</body>
</html>
