<?php $baseUrl = $this->basePath(); ?>
<header class="header">
    <div class="container">
      <!-- Navigation Menu -->
      <div class="menu_main_full">
        <div class="navbar yamm navbar-default">
          <div class="navbar-header">
            <div class="navbar-toggle .navbar-collapse .pull-right " data-toggle="collapse" data-target="#navbar-collapse-1"  > <span>Menu</span>
              <button type="button" > <i class="fa fa-bars"></i></button>
            </div>
          </div>
          <div id="navbar-collapse-1" class="navbar-collapse collapse">
            <nav>
              <ul class="nav navbar-nav">
                <!--Home-->
                <li class="dropdown yamm-fw"> <a href="#" class="dropdown-toggle active">Home</a></li>
                <!--About us-->
                <li class="dropdown"><a href="#" class="dropdown-toggle">About us</a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Overview</a></li>
                    <li><a href="#">Core Values</a></li>
                    <li><a href="#">Leadership</a></li>
                    <li><a href="#">Mission & Vision</a></li>
                    <li><a href="#">Brand Story</a></li>
                    <li><a href="#">Testimonials</a></li>
                  </ul>
                </li>
                <!--Project-->
                <li class="dropdown yamm-fw"> <a href="projects.html" class="dropdown-toggle">Projects</a>
                  <ul class="dropdown-menu">
                    <li>
                      <!-- Content container to add padding -->
                      <div class="yamm-content">
                        <div class="row">
                          <ul class="col-sm-6 col-md-3 list-unstyled">
                            <li>
                              <p>Residential Projects</p>
                            </li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 1</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 2</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 3</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 4</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 5</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 6</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 7</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 8</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 9</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> For More Projects <em>Click</em></a></li>
                          </ul>
                          <ul class="col-sm-6 col-md-3 list-unstyled">
                            <li>
                              <p>Commercial Projects</p>
                            </li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 1</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 2</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 3</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 4</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 5</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 6</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 7</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 8</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 9</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> For More Projects <em>Click</em></a></li>
                          </ul>
                          <ul class="col-sm-6 col-md-3 last list-unstyled nav-project-img-ul-bordr">
                            <li>
                              <p>Hot Deals</p>
                            </li>
                            <li class="nav-project-img-bg"><a href="#"><img src="<?php echo $baseUrl;?>/images/latest-Project/lp1.jpg" class="nav-project-img-border"></a></li>
                            <li class="nav-project-img-bg"><a href="#"><img src="<?php echo $baseUrl;?>/images/latest-Project/lp2.jpg" class="nav-project-img-border"></a></li>
                          </ul>
                          <ul class="col-sm-6 col-md-3 last list-unstyled">
                            <li>
                              <p>&nbsp;</p>
                            </li>
                            <li class="nav-project-img-bg"><a href="#"><img src="<?php echo $baseUrl;?>/images/latest-Project/lp3.jpg" class="nav-project-img-border"></a></li>
                          </ul>
                        </div>
                      </div>
                    </li>
                  </ul>
                </li>
                <!--Media-->
                <li class="dropdown"><a href="#" class="dropdown-toggle">Media</a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Press Coverage</a></li>
                    <li><a href="#">Press Releases</a></li>
                    <li><a href="#">Events</a></li>
                  </ul>
                </li>
                <!--Know more-->
                <li class="dropdown"><a href="#" class="dropdown-toggle">Know more</a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">NRI Services</a></li>
                    <li><a href="#">Step to Buy Property</a></li>
                    <li><a href="#">Vaastu Tips</a></li>
                    <li><a href="#">Home Load</a></li>
                    <li><a href="#">EMI Calculator</a></li>
                  </ul>
                </li>
                <!--Careers-->
                <li class="dropdown"> <a href="#" class="dropdown-toggle">Careers </a></li>
                <!--Contact us-->
                <li class="dropdown"><a href="#" class="dropdown-toggle">Contact us</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <!-- end Navigation Menu -->
      <div class="menu_rlinks"> <a href="#" class="mrbut cart-tab js__p_start">LOGIN</a> </div>
      <!-- end menu right links -->
    </div>
  </header>