<?php $baseUrl = $this->basePath(); ?>

<!doctype html>
<html lang="en-gb" class="no-js">
<head>
<title>Aadinath</title>
<link rel="shortcut icon" type="image/png" href="<?php echo $baseUrl;?>/public/images/logo/favicon.png"/>
<link rel="shortcut icon" href="<?php echo $baseUrl;?>/public/images/favicon.html">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dancing+Script:400,700' rel='stylesheet' type='text/css'>
<!-- custom -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/custom.css">
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/reset.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/style.css" type="text/css" />
<!-- font awesome icons -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/font-awesome/css/font-awesome.min.css">
<!-- simple line icons -->
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/css/simpleline-icons/simple-line-icons.css" media="screen" />
<!-- et linefont icons -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/et-linefont/etlinefont.css">
<!-- animations -->
<link href="<?php echo $baseUrl;?>/public/js/animations/css/animations.min.css" rel="stylesheet" type="text/css" media="all" />
<!-- responsive devices styles -->
<link rel="stylesheet" media="screen" href="<?php echo $baseUrl;?>/public/css/responsive-leyouts.css" type="text/css" />
<!-- shortcodes -->
<link rel="stylesheet" media="screen" href="<?php echo $baseUrl;?>/public/css/shortcodes.css" type="text/css" />
<!-- style switcher -->
<link rel = "stylesheet" media = "screen" href = "<?php echo $baseUrl;?>/public/js/style-switcher/color-switcher.css" />
<!-- mega menu -->
<link href="<?php echo $baseUrl;?>/public/js/mainmenu/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo $baseUrl;?>/public/js/mainmenu/demo.css" rel="stylesheet">
<link href="<?php echo $baseUrl;?>/public/js/mainmenu/menu11.css" rel="stylesheet">
<!-- MasterSlider -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/js/masterslider/style/masterslider.css" />
<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/js/masterslider/skins/default/style.css" />
<!-- cubeportfolio -->
<link rel="stylesheet" type="text/css" href="js/cubeportfolio/cubeportfolio.min.css">
<!-- owl carousel -->
<link href="<?php echo $baseUrl;?>/public/js/carouselowl/owl.transitions.css" rel="stylesheet">
<link href="<?php echo $baseUrl;?>/public/js/carouselowl/owl.carousel.css" rel="stylesheet">
<!-- accordion2 -->
<link href="<?php echo $baseUrl;?>/public/js/accordion2/style.css" rel="stylesheet" />

<link rel="stylesheet" media="screen" href="<?php echo $baseUrl;?>/public/bootstrap/css/bootstrap.min.css" type="text/css" />

</head>
<body>
<div class="site_wrapper" style="position: absolute;">
  <div class="top_section">
    <div class="container">
      <div class="left">
        <!-- Logo -->
        <div><a href="<?php echo $baseUrl ?>" id="logo"></a></div>
      </div>
      <div class="right"> <i class="fa fa-envelope"></i>&nbsp; crm@aadinathindia.com <i class="fa fa-phone-square"></i>&nbsp; +91-9650 797 111
        <ul class="topsocial">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- end top navigation links -->
  <div class="clearfix"></div>
  <header class="header">
    <div class="container">
      <!-- Navigation Menu -->
      <div class="menu_main_full">
        <div class="navbar yamm navbar-default-index">
          <div class="navbar-header">
            <div class="navbar-toggle .navbar-collapse .pull-right " data-toggle="collapse" data-target="#navbar-collapse-1"  > <span>Menu</span>
              <button type="button" > <i class="fa fa-bars"></i></button>
            </div>
          </div>
		  
		  
    <?php echo $this->layout()->content;?>     
  

 <?php echo $this->partial("footer"); ?>





<div id='backgroundImage' style="height:4000px; margin:0; padding:0; position:fixed; margin-top:-800px;">
 
 <div id="style-selector" style="left:-225px;">
<div class="style-selector-wrapper">
<span class="title">MENU</span>
<div>        
<br /><br />

<span class="title-sub2"><strong>Aadinath Guide <br>(Complete Property Guide)</strong></span>
<ul class="styles" style="border-bottom: none;">
    <li><a href="property-buying-step.html" class="demolinks">- FAQs</a></li>
    <li><a href="home-loan.html" class="demolinks">- Home Loan</a></li>
    <li><a href="vaastu-tips.html" class="demolinks">- Vaastu Tips</a></li>
    <li><a href="emi.html" class="demolinks">- EMI Calculator</a></li>
	<li><a href="nri.html" class="demolinks">- NRI Services</a></li>
    <li><a href="#" class="demolinks">- Blog</a></li>
</ul>
<span class="title-sub2">Need Any Help? <br><b>Call us: +91-9650 797 111</b></span>


<a href="#" class="close icon-chevron-right"></a>  
    
</div>
</div>
</div>
 </div>

  
</body>
</html>
