<?php $baseUrl = $this->basePath(); ?>

<!doctype html>
<html lang="en-gb" class="no-js">
<head>
<title>Aadinath</title>
<link rel="shortcut icon" type="image/png" href="<?php echo $baseUrl;?>/images/logo/favicon.png"/>
<link rel="shortcut icon" href="<?php echo $baseUrl;?>/images/favicon.html">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Dancing+Script:400,700' rel='stylesheet' type='text/css'>
<!-- custom -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/css/custom.css">
<link rel="stylesheet" href="<?php echo $baseUrl;?>/css/reset.css" type="text/css" />
<link rel="stylesheet" href="<?php echo $baseUrl;?>/css/style.css" type="text/css" />
<!-- font awesome icons -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/css/font-awesome/css/font-awesome.min.css">
<!-- simple line icons -->
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/css/simpleline-icons/simple-line-icons.css" media="screen" />
<!-- et linefont icons -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/css/et-linefont/etlinefont.css">
<!-- animations -->
<link href="<?php echo $baseUrl;?>/js/animations/css/animations.min.css" rel="stylesheet" type="text/css" media="all" />
<!-- responsive devices styles -->
<link rel="stylesheet" media="screen" href="<?php echo $baseUrl;?>/css/responsive-leyouts.css" type="text/css" />
<!-- shortcodes -->
<link rel="stylesheet" media="screen" href="<?php echo $baseUrl;?>/css/shortcodes.css" type="text/css" />
<!-- style switcher -->
<link rel = "stylesheet" media = "screen" href = "<?php echo $baseUrl;?>/js/style-switcher/color-switcher.css" />
<!-- mega menu -->
<link href="<?php echo $baseUrl;?>/js/mainmenu/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo $baseUrl;?>/js/mainmenu/demo.css" rel="stylesheet">
<link href="<?php echo $baseUrl;?>/js/mainmenu/menu11.css" rel="stylesheet">
<!-- MasterSlider -->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/js/masterslider/style/masterslider.css" />
<link rel="stylesheet" href="<?php echo $baseUrl;?>/js/masterslider/skins/default/style.css" />
<!-- cubeportfolio -->
<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/js/cubeportfolio/cubeportfolio.min.css">
<!-- owl carousel -->
<link href="<?php echo $baseUrl;?>/js/carouselowl/owl.transitions.css" rel="stylesheet">
<link href="<?php echo $baseUrl;?>/js/carouselowl/owl.carousel.css" rel="stylesheet">
<!-- accordion2 -->
<link href="<?php echo $baseUrl;?>/js/accordion2/style.css" rel="stylesheet" />


<!--popup--->
<link rel="stylesheet" href="<?php echo $baseUrl;?>/css/jquery.popup.css" type="text/css">	
<link rel="stylesheet" href="<?php echo $baseUrl;?>/css/subscribe-style.css">



</head>
<body>
<div class="site_wrapper">
  <div class="top_section">
    <div class="container">
      <div class="left">
        <!-- Logo -->
        <div><a href="index.html" id="logo"></a></div>
      </div>
      <div class="right"> <i class="fa fa-envelope"></i>&nbsp; info@aadinath.com <i class="fa fa-phone-square"></i>&nbsp; +91 987 654 1234
        <ul class="topsocial">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- end top navigation links -->
  <div class="clearfix"></div>
  <?php echo $this->partial("indexheader"); ?>
  <div class="clearfix"></div>
  
  <!-- header file ends -->
  
   <!-- container body starts -->
  
 	<?php echo $this->layout()->content; ?>
  
  
  
  <!-- container body ends -->
  
  <!-- Top Builder========================================================================================== -->
  <!-- section 72 Builder--->
  <div class="clearfix margin_top12"></div>
  <!-- Footer=============================================================================================== -->
 
  
   <?php echo $this->partial("footer"); ?>
  
  
  
  <!-- scroll to top======================================================================================== -->  
  <a href="#" class="scrollup">Scroll</a><!-- end scroll to top of the page-->
  
  <!-- Left Navigation Toggal=============================================================================== --> 
  <div id="style-selector">
<div class="style-selector-wrapper">
<span class="title">MENU</span>
<div>        
<br /><br />

<span class="title-sub2"><a href="#">Aadinath Guide <br>(Complete Property Guide)</a></span>
<span class="title-sub2"><a href="#">Real Estate News</a></span>
<span class="title-sub2">More</span>
<ul class="styles" style="border-bottom: none;">
    <li><a href="#" class="demolinks">- FAQs</a></li>
    <li><a href="#" class="demolinks">- Home Loan</a></li>
    <li><a href="#" class="demolinks">- Vaastu Tips</a></li>
    <li><a href="#" class="demolinks">- EMI Calculator</a></li>
	<li><a href="#" class="demolinks">- NRI Services</a></li>
    <li><a href="#" class="demolinks">- Blog</a></li>
</ul>
<span class="title-sub2">Need Any Help? <br><b>Call us: 0120-4256308</b></span>


<a href="#" class="close icon-chevron-right"></a>  
    
</div>
</div>
</div>
</div>

<!-- ######### JS FILES ######### -->
<!-- get jQuery used for the theme -->
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/universal/jquery.js"></script>
<script src="<?php echo $baseUrl;?>/js/style-switcher/styleselector.js"></script>
<script src="<?php echo $baseUrl;?>/js/animations/js/animations.min.js" type="text/javascript"></script>
<script src="<?php echo $baseUrl;?>/js/mainmenu/bootstrap.min.js"></script>
<script src="<?php echo $baseUrl;?>/js/mainmenu/customeUI.js"></script>
<script src="<?php echo $baseUrl;?>/js/masterslider/jquery.easing.min.js"></script>
<script src="<?php echo $baseUrl;?>/js/masterslider/masterslider.min.js"></script>
<script type="text/javascript">
(function($) {
 "use strict";
	var slider = new MasterSlider();
	
	slider.setup('masterslider' , {
		 width:1400,    // slider standard width
		 height:640,   // slider standard height
		 space:0,
		 speed:27,
		 layout:'fullwidth',
		 loop:true,
		 preload:0,
		 autoplay:true,
		 view:"scale"
	});
})(jQuery);
</script>
<script src="js/scrolltotop/totop.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/mainmenu/sticky.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/mainmenu/modernizr.custom.75180.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/cubeportfolio/jquery.cubeportfolio.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/cubeportfolio/main5.js"></script>
<script src="<?php echo $baseUrl;?>/js/carouselowl/owl.carousel.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/accordion2/custom.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/js/universal/custom.js"></script>



<!--For Popup Jquery 
    <script type="text/javascript" src="js/jquery-2.0.3.min.js"></script>--> 
  <script type="text/javascript" src="<?php echo $baseUrl;?>/js/jquery.popup.js"></script>

  <script type="text/javascript">
    $(function() {
      $(".js__p_start, .js__p_another_start").simplePopup();
    });
  </script> 
    <!--End of For Popup Jquery--> 
    
    <div class="p_body js__p_body js__fadeout"></div>
  <div class="popup js__popup js__slide_top">
  <a href="#" class="p_close js__p_close">
      <span></span><span></span>
    </a>
  
    <div class="p_content container">
	
    <div class="logregform">
    
        
        <div class="title">
        
			<h3 class="margin_top2" style="margin-bottom:30px;">Account Login</h3>        		
			
            
        </div>
        
        <div class="feildcont margin_top3">
        
            <form role="form">
            
                <label><i class="fa fa-user"></i> User/Email</label>
                <input type="text">
                
                <label><i class="fa fa-lock"></i> Password</label>
                <input type="password">
                
                <div class="checkbox">
                    <label>
                        <input type="checkbox">
                    </label>
                    <label>Remember Me</label>
                    <label><a href="#"><strong>Forgot Password?</strong></a></label>
                </div>
                    <button type="button" class="fbut">Login Now!</button>
                    <button type="button" class="btn btn-default btn-sm"  style="margin-top:10px;margin-left:20px;">SIGN UP</button>
                                    
            </form>
        <div class="margin_top3">
        </div>
    
    </div>
  
</div>
    
  </div>
  
  </div>
    
  


  
</body>
</html>
