

<?php $baseUrl = $this->basePath(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="<?php echo $baseUrl;?>/adminpanel/css/style.css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo $baseUrl;?>/adminpanel/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/adminpanel/script.js"></script>
</head>

<body>
<div class="header">
<div class="header-inner">
<div class="logo" style="padding:15px; padding-left:15px;"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/aadinath_logo.png" /></a></div>
</div>
</div>

<div class="welcom">
<div class="welcom-left"><span style="padding-left:50px; line-height:50px;">Welcome Administrator</span></div>
<div class="welcom-right"><span style="padding-right:50px; line-height:50px;"><a href="">Launch Website</a> &nbsp; | &nbsp;
<a href="">Change Password</a>&nbsp; | &nbsp;
<a href="">Log Out</a></span>
</div>
</div>
<!----maincontainer---->
<div class="container">

<!----menu----->

<div class="menu">
	<div id='cssmenu' style="margin-top:30px;margin-left:30px;">
<ul>
   <li><a href='#'>Dashboard</a></li>
   <li class='active has-sub'><a href='#'>Nav1</a>
      <ul>
         <li class='has-sub'><a href='#' style="padding-left:45px;">Nav-1-1</a>
            <ul>
               <li><a href='#'>Nav-1-1-1</a></li>
               <li class='last'><a href='#'>Nav-1-1-2</a></li>
            </ul>
         </li>
         <li class='has-sub'><a href='#' style="padding-left:45px;">Nav-1-2</a>
            <ul>
               <li><a href='#'>Nav-1-2-1</a></li>
               <li class='last'><a href='#'>Nav-1-2-2</a></li>
            </ul>
         </li>
      </ul>
   </li>
   <li><a href='#'>Nav3</a></li>
   <li class='last'><a href='#'>Nav4</a></li>
</ul>
</div>

</div>

<!----body---->
<?php echo $this->layout()->content; ?>

</div><!----footer------->
<div class="footer">
	<div class="txt1" style="float:left; padding-top:10px; color:#FFFFFF;">All trademarks, logos and names are properties of their respective owners. All Right Reserved. ©2015 </div>
    <div class="txt1" style="float:right; padding-top:4px;"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/discovery-logo.png" /></a></div>
    
</div>
</body>
</html>