

<?php $baseUrl = $this->basePath(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="<?php echo $baseUrl;?>/adminpanel/css/style.css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo $baseUrl;?>/adminpanel/jquery.min.js"></script>
</head>

<body>
<div class="header">
<div class="logo" style="padding:15px;"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/logo.png" /></a></div>
</div>

<div class="welcom">
<div class="txt1" style="float:left; padding:10px;">Welcome Administrator</div>
<div class="txt1" style="float:right; padding:10px;"><a href="">Launch Website</a> 
<a href="">Change Password</a>
<a href="">Log Out</a>
</div>
</div>
<!----maincontainer---->
<div class="container">

<!----menu----->

<div class="menu">
	<div class="menu1">
    <ul>
    <li><a href="index.html">Dashboard</a> </li>
    <li><a href="index.html">Manage Locations</a> </li>
    </ul>
    </div>
</div>

<!----body---->
<?php echo $this->layout()->content; ?>

</div><!----footer------->
<div class="footer">
	<div class="txt1" style="float:left; padding:15px; color:#FFFFFF;">All trademarks, logos and names are properties of their respective owners. All Right Reserved. ©2015 </div>
    <div class="txt1" style="float:right; padding:10px;"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/discovery-logo.png" /></a></div>
    
</div>
</body>
</html>