<?php $baseUrl = $this->basePath(); 

//echo '<pre>';print_r($this->projectsDetail);exit;

$amenityArr = count($this->projectsDetail) ? explode(',',$this->projectsDetail[0]['amenities']) : array();


?>
<script src="<?php echo $baseUrl; ?>/public/js/ajaxupload.3.5.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/public/tinmca/jscripts/tiny_mce/tiny_mce.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script type="text/javascript">
$(function(){
     var btnUpload=$('#upload_1');
     var status=$('#status');
     ajaxUpload(btnUpload,status,1);
});
$(function(){
    var btnUpload=$('#upload_2');
    var status=$('#status');
    ajaxUpload(btnUpload,status,2);
});
 $(function(){
      var btnUpload=$('#upload_3');
      var status=$('#status');
      ajaxUpload(btnUpload,status,3);
 });
$(function(){
	 var btnUpload=$('#upload_4');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,4);
});
$(function(){
	 var btnUpload=$('#upload_5');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,5);
});
$(function(){
	 var btnUpload=$('#upload_6');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,6);
});
$(function(){
	 var btnUpload=$('#upload_7');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,7);
});
$(function(){
	 var btnUpload=$('#upload_8');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,8);
});
$(function(){
	 var btnUpload=$('#upload_9');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,9);
});
$(function(){
	 var btnUpload=$('#upload_10');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,10);
});
$(function(){
	 var btnUpload=$('#project_image_upload');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,11);
});
$(function(){
	 var btnUpload=$('#brochure_upload');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,12);
});
$(function(){
	 var btnUpload=$('#location_map_upload');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,13);
});
$(function(){
	 var btnUpload=$('#site_plan_upload');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,14);
});
$(function(){
	 var btnUpload=$('#application_form_upload');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,15);
});
	
function ajaxUpload(btnUpload,status,id){
	 var url='<?php echo $baseUrl ?>';
	 var SITEROOT=url+"/backend/admin/upload";
	 new AjaxUpload(btnUpload,
		 {
		     action: SITEROOT,
		     name:'uploadfile' ,
		     onSubmit: function(file, ext){
		         if (! (ext && /^(jpg|png|jpeg|gif|pdf)$/.test(ext))){
		             // extension is not allowed
		             status.text('Only JPG, PNG or GIF files are allowed');
		             return false;
		         }
                 $extnsn = ext;
		         status.text('Uploading...');
		     },
		     onComplete: function(file, response){
		         //On completion clear the status
		         status.text('');
		         var filepath = url+'/public/uploadfiles/'+response;
		    	 id = parseInt(id);
				$('#files_'+id).html('');
		         if(response != ""){
		             document.getElementById("imagename_"+id).value = response;
		             $('#preview_'+id).show();
                     
                     if($extnsn=='pdf')
                         $('<div></div>').appendTo('#files_'+id).html('<a href="'+filepath+'" target="_blank" style="color:#fff;text-decoration:none"><span style="width:auto;background-color:#333;padding:5px 15px; color:#fff;font-weight:bold;font-size: 12px; ">View File</span></a>').addClass('success');                    else
                        $('<div></div>').appendTo('#files_'+id).html('<img height="50" width="50" src="'+filepath+'" alt="" /><br />').addClass('success');
		           //  $('#lastImageId').val(id+1);
		         } else{
		            // $('<div></div>').appendTo('#files').text(response).addClass('error');
		         }
		         
		     }
		 });
}

function previewImage(id){
	$('#files_'+id).toggle();
	return false;
}
 $(function() {
    $( "#possessiondate" ).datepicker();
    $( "#completed_on" ).datepicker();
  });
function delBanner(id){
    $('#imagename_'+id).val('');
    $('#files_'+id).html('');
    return false;
}
$('#project_status').change(function(){
  if($(this).val()==1)
    $('#completed_on_div').hide();
  else{
    $('#completed_on').val('');
    $('#completed_on_div').show();
  }
});
</script>
<script type="text/javascript">
    tinyMCE.init({
        // General options
        mode: "exact",
        elements: "desc,preq",
        theme: "advanced",
        width: "100%",
        height: 310,
        plugins: "jbimages,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",
        // Theme options
        theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,code,",
        theme_advanced_buttons2: "",
        theme_advanced_buttons3: "",
        //theme_advanced_buttons3 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft",
        //theme_advanced_buttons4 : "",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        theme_advanced_statusbar_location: "bottom",
        theme_advanced_resizing: true,
        // Example content CSS (should be your site CSS)
        content_css: "<?php echo $baseUrl; ?>/js/tinmca/css/content.css",
        // Drop lists for link/image/media/template dialogs
        template_external_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/template_list.js",
        external_link_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/link_list.js",
        external_image_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/image_list.js",
        media_external_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/media_list.js",
        // Style formats
        style_formats: [
            {title: 'Bold text', inline: 'b'},
            {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
            {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
            {title: 'Example 1', inline: 'span', classes: 'example1'},
            {title: 'Example 2', inline: 'span', classes: 'example2'},
            {title: 'Table styles'},
            {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ],
        relative_urls: false,
        // Replace values for the template plugin
        template_replace_values: {
            username: "Some User",
            staffid: "991234"
        },
        autosave_ask_before_unload: false
    });
</script>
<input type="text" id="errorMsg" style="width:0px;border:none">
<div class="contant">
    <div class="heading"><?php echo $this->heading ?></div>
    <div class="contant1">
        <form method="post" action="" name="" id="projectform">
            <input type="hidden" id="projectSlug" name="projectSlug">    
            <?php if ($this->msg != '') { ?>
                <div ><?php echo $this->msg ?></div>
            <?php } ?>
                <span style="color:#cc0000;margin-left:20px;display:none;" id="nameExist"></span>
            <div class="content2-1">
                <div class="content3-1"><span style="color:red">*</span> Property Type:</div>
                <div class="content4-1">
                    <select id="property_type_id" name="property_type_id" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
                        <?php
                            $tempArr = array();
                            foreach ($this->property_types as $property_category) {
                                if(count($property_category['propertyTypeList'])){?>
                                    <optgroup label="<?php echo $property_category['category_name'] ?>">
                                   <?php   
                                        foreach($property_category['propertyTypeList'] as $property_type){
                                    ?>       
                                         <option <?php if($this->projectsDetail[0]['property_type_id']==$property_type['id'])  { echo 'selected';}?> value="<?php echo $property_type['id'] ?>"><?php echo ucfirst($property_type['property_type']) ?></option>   
                                    <?php          
                                        }
                                    ?>    
                                     </optgroup>   
                        <?php            
                                }
                            }
                        ?>

                    </select>
                </div>
            </div>
            <div class="content2-1">
                <div class="content3-1"><span style="color:red">*</span> Transaction Type:</div>
                <div class="content4-1">
                    <select id="transaction_type_id" name="transaction_type_id" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
                        <option <?php if($this->projectsDetail[0]['transaction_type_id']==1)  { echo 'selected';}?> value=1>Fresh</option>
                        <option <?php if($this->projectsDetail[0]['transaction_type_id']==2)  { echo 'selected';}?> value=2>Resale</option>
                    </select>
                </div>
            </div>
   
            <div class="content2-1">
                <div class="content3-1"><span style="color:red">*</span> Project Title:</div>
                <div class="content4-1">
                    <input type="text" name="project_title" id="projecttitle" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"  value="<?php if($this->projectsDetail[0]['project_title']!='')  { echo $this->projectsDetail[0]['project_title'];}?>"/> (e.g. 3C Sports Village Noida.)
                </div>
            </div>

            <div class="content2-1">
                <div class="content3-1"> <span style="color:red">*</span> Project Plan:</div>
                <div class="content4-1">
                    <input type="text" name="project_plan" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="project_plan"  value="<?php if($this->projectsDetail[0]['project_plan']!='')  { echo $this->projectsDetail[0]['project_plan'];}?>"/> (e.g. 4 BHK-3 BHK.)
                </div>
            </div>

             <div class="content2">
                <div class="content3" Style="font-weight: normal;"><span style="color:red">*</span> Address: </div>
                <div class="content4-builder">
                    <textarea name="address" id="address"  style="width:250px; height:56px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" ><?php if($this->projectsDetail[0]['address']!='')  { echo $this->projectsDetail[0]['address'];}?></textarea>
                </div>
            </div>
            
            <div class="content2-1" >
                <div class="content3-1"> <span style="color:red">*</span> Super Built-up Area:</div>
                <div class="content4-1">
                    <input type="text" name="builtup_area" id="builtup_area" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" value="<?php if($this->projectsDetail[0]['builtup_area']!='')  { echo $this->projectsDetail[0]['builtup_area'];}?>"/> (e.g. 1690 - 3965 sq.ft.)
                </div>
            </div>
            <div class="content2" style="margin-top:35px;">
                <div class="content3" Style="font-weight: normal;"> <span style="color:red">*</span> Starting Price:</div>
                <div class="content4">
                   <input type="text" name="starting_price" id="starting_price" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" value="<?php if($this->projectsDetail[0]['starting_price']!='')  { echo $this->projectsDetail[0]['starting_price'];}?>"/> (e.g. 3.04 Crs.)
                </div>
            </div>

           

            <div class="content2-1">
                <div class="content3-1"> <span style="color:red">*</span> Buildings:</div>
                <div class="content4-1">
                    <input type="text" name="buildings" id="buildings" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" value="<?php if($this->projectsDetail[0]['buildings']!='')  { echo $this->projectsDetail[0]['buildings'];}?>"/> (e.g. 5.)
                </div>
            </div>

 <!--            <div class="content2">
                <div class="content3" Style="font-weight: normal;"><span style="color:red">*</span> Configurations: </div>
                <div class="content4-builder">
                    <textarea name="configurations" id="configurations" style="width:250px; height:56px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"><?php if($this->projectsDetail[0]['configurations']!='')  { echo $this->projectsDetail[0]['configurations'];}?></textarea>
                </div>
            </div>-->
            <div class="content2-1">
                <div class="content3-1"><span style="color:red;margin-top:30px;">*</span>Builder:</div>
                <div class="content4-1">
                    <select id="builder" name="builder" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
                        <?php foreach ($this->builderList as $builder) { ?>
                            <option  <?php if($this->projectsDetail[0]['builder']== $builder['id']) echo "selected"   ?> value=<?php echo $builder['id'] ?>><?php echo $builder['builder_name'] ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>


            <div class="content2-1" style="margin-top:35px;">
                <div class="content3-1"> <span style="color:red">*</span> Priority: </div>
                <div class="content4-1">
                    <input type="text" name="priority" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="priority" value="<?php if($this->projectsDetail[0]['order']!='')  { echo $this->projectsDetail[0]['order'];}?>"/>
                </div>
            </div>

<div class="content2-1" style="margin-top:35px;">
                <div class="content3-1"> <span style="color:red">*</span> Possession: </div>
                <div class="content4-1">
                    <input type="text" name="possession" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="possessiondate" value="<?php if($this->projectsDetail[0]['possession']!='')  { echo $this->projectsDetail[0]['possession'];}?>"/>
                </div>
            </div>

            <div class="content2-1-2">
                <div class="content3-1-2" style="font-weight: normal";><span style="color:red">*</span>Project Description:</div>
                <div class="content4-1-2">
                    <textarea name="project_desc" id="desc"  value=""><?php if($this->projectsDetail[0]['project_desc']!='')  { echo $this->projectsDetail[0]['project_desc'];}?></textarea>
                </div>
            </div>

            <div class="heading-1">Location</div>
            <div class="content2-1">
                <div class="content3-1"><span style="color:red">*</span>City:</div>
                <div class="content4-1">
                    <select  name="city" id="cityName" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
                        <option value=''>Select</option>
                        <?php foreach ($this->cityList as $city) { ?>
                            <option  <?php if($this->projectsDetail[0]['city']== $city['cityId']) echo "selected";?> value=<?php echo $city['cityId'] ?>><?php echo $city['city_name'] ?></option>

                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="content2-1">
                <div class="content3-1"><span style="color:red">*</span>Location:</div>
                <div class="content4-1">
                    <select id="locationName" name="location" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"  >
					<?php if(isset($this->locaOptions)){
        		foreach ($this->locaOptions as $location){?>
        		<option <?php if($this->projectsDetail[0]['location']== $location['id']) echo "selected"?> value=<?php echo $location['id']?>><?php echo $location['location_name']?></option>
        	
        	<?php }}?>

                    </select>
                </div>
            </div>


            <div class="content2-1">
                <div class="content3-1"> <span style="color:red">*</span> Contact No:  </div>
                <div class="content4-1">
                    <input type="text" name="contact" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="contact" value="<?php if($this->projectsDetail[0]['contact']!='')  { echo $this->projectsDetail[0]['contact'];}?>"/>
                </div>
            </div>


            <div class="heading-1"> Display Price & Size</div>
            <div class="content2-1">
                <div class="content3-1"> <span style="color:red">*</span> Size:  </div>
                <div class="content4-1">
                    <input type="text" id="display_size" name="display_size" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"  value="<?php if($this->projectsDetail[0]['display_size']!='')  { echo $this->projectsDetail[0]['display_size'];}?>"/>
                </div>
            </div>

            <div class="content2-1">
                <div class="content3-1"> <span style="color:red">*</span> Price:  </div>
                <div class="content4-1">
                    <input type="text"  name="display_price" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="display_price" value="<?php if($this->projectsDetail[0]['display_price']!='')  { echo $this->projectsDetail[0]['display_price'];}?>"/>
					
                </div>
            </div>

			 <div class="content2-1">
                <div class="content3-1"><span style="color:red">*</span> Project Status:</div>
                <div class="content4-1">
                    <select id="project_status" name="project_status" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
                    <option value="">Select Project Status</option>   
                    <option <?php if($this->projectsDetail[0]['project_status']==1) echo 'selected'?> value="1">Ongoing Project</option>   
                    <option <?php if($this->projectsDetail[0]['project_status']==2) echo 'selected'?> value="2">Completed Project</option> 
                    </select>
                </div>
            </div>

           
            <div class="content2-1" id="completed_on_div" >
                <div class="content3-1"> <span style="color:red">*</span> Completed On: </div>
                <div class="content4-1">
                    <input type="text" name="completion_date" style="width:246px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="completed_on" value="<?php if($this->projectsDetail[0]['completion_date']!='')  { echo date('Y-m-d',  strtotime($this->projectsDetail[0]['completion_date']));}?>"/>
                </div>
            </div>
            <div class="heading-1"> Search Price & Size (e.g. only 0-9 digits.) </div>
            <div class="content2-1">
                <div class="content3-1"> <span style="color:red">*</span> Price:  </div>
                <div class="content4-1">

                    <input type="text" placeholder="Min" name="search_min_price" style="width:140px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="search_min_price" value="<?php if($this->projectsDetail[0]['search_min_price']!='')  { echo $this->projectsDetail[0]['search_min_price'];}?>"/>

                    <input type="text" placeholder="Max" name="search_max_price" style="width:140px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="search_max_price" value="<?php if($this->projectsDetail[0]['search_max_price']!='')  { echo $this->projectsDetail[0]['search_max_price'];}?>"/>
                </div>
            </div>

            <div class="content2-1">
                <div class="content3-1"> <span style="color:red">*</span> Size: </div>
                <div class="content4-1">

                    <input type="text" placeholder="Min" name="search_min_size" style="width:140px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="search_min_size" value="<?php if($this->projectsDetail[0]['search_max_price']!='')  { echo $this->projectsDetail[0]['search_min_size'];}?>"/>

                    <input type="text" placeholder="Max" name="search_max_size" style="width:140px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="search_max_size" value="<?php if($this->projectsDetail[0]['search_max_price']!='')  { echo $this->projectsDetail[0]['search_max_size'];}?>"/>
                </div>
            </div>
			
			 <div class="content2-1">
                <div class="content3-1"> <span style="color:red">*</span> BHK's: </div>
                 <div class="content2-5-ser"><input type="checkbox" name="is_1bhk"  value = "1" style="width:20px; height:8px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" <?php if($this->projectsDetail[0]['has_1BHK'] =='1') {echo 'checked';} ?>/>1BHK
				 <input type="checkbox" name="is_2bhk" value = "1" style="width:20px; height:8px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" <?php if($this->projectsDetail[0]['has_2BHK'] == '1'){echo 'checked';} ?>/>2BHK
				 <input type="checkbox" name="is_3bhk" value = "1" style="width:20px; height:8px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" <?php if($this->projectsDetail[0]['has_3BHK'] =='1'){echo 'checked';} ?> />3BHK
				 <input type="checkbox" name="is_4bhk" value = "1" style="width:20px; height:8px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" <?php if($this->projectsDetail[0]['has_4BHK'] =='1'){echo 'checked';} ?>/>4BHK
				 <input type="checkbox" name="is_5bhk" value = "1" style="width:20px; height:8px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"<?php if($this->projectsDetail[0]['has_5BHK'] =='1'){echo 'checked';} ?> />5BHK
                            </div>
            </div>

            <div class="heading-1"> Focused Project </div>

            <div class="content2-1">
                <div class="content3-1"><span style="color:red">*</span>Mark as focused project:</div>
                <div class="content4-1">
                    <input type="checkbox" name="is_focused" value="1"<?php if($this->projectsDetail[0]['is_focused'] =='1'){echo 'checked';} ?>  style="width:50px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"/>
                </div>
            </div>

            <div class="heading-1">Amenities </div>
            <div style="width:100%;height:30px;">Internal Amenities:</div>


            <div class="content2-6">
                <?php
                foreach ($this->aminityList as $aminity) {
                    if ($aminity['aminity_type_id'] == 1) {
                        ?>
                        <div class="content2-5-amn"><input type="checkbox" name="aminities[]" style="width:20px; height:8px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" <?php if(in_array($aminity['id'],$amenityArr)) echo "checked";?> value="<?php echo $aminity['id'] ?>"/>
                            <?php echo $aminity['amenity_name'] ?></div>
                    <?php
                    }
                }
                ?>	
            </div>

            <div class="clear"></div>

            <div style="width:100%;height:30px;">External Amenities:</div>

            <div class="content2-6">
                <?php
                foreach ($this->aminityListtt as $aminity) {
                    if ($aminity['aminity_type_id'] == 2) {
                        ?>
                        <div class="content2-5-amn"><input type="checkbox" name="aminities[]" style="width:20px; height:8px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" <?php if(in_array($aminity['id'],$amenityArr)) echo "checked";?> value="<?php echo $aminity['id'] ?>"/>
                        <?php echo $aminity['amenity_name'] ?></div>
                    <?php
                    }
                }
                ?>
            </div>

            <div class="clear"></div>

            <div class="heading-1" style="margin-top:20px !important;"> Project Snapshot </div>

            <div class="content2-1">
                <input type='hidden' name='slide_image_1' id='imagename_1' value='<?php if ($this->projectsDetail[0]['slide_image_1']!='') echo $this->projectsDetail[0]['slide_image_1']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Slide Image 1:(850 * 400)</div>
                <div class="content4-1"><button class="" style="" id="upload_1">Browse</button>
                <?php if($this->projectsDetail[0]['slide_image_1']!='') {?>
                <button id=" " class="" onclick="return delBanner('1')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>    
                    <div class="am2" >
                        <div class="" id="files_1">
                        <?php if ($this->projectsDetail[0]['slide_image_1']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['slide_image_1']; ?>"/> 
                        <?php } ?>
                        </div>
                       
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='slide_image_2' id='imagename_2' value='<?php if ($this->projectsDetail[0]['slide_image_2']!='') echo $this->projectsDetail[0]['slide_image_2']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Slide Image 2:(850 * 400)</div>
                <div class="content4-1"><button class="" style="" id="upload_2">Browse</button>
                    <?php if($this->projectsDetail[0]['slide_image_2']!='') {?>
                <button id=" " class="" onclick="return delBanner('2')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_2">
                             <?php if ($this->projectsDetail[0]['slide_image_2']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['slide_image_2']; ?>"/> 
                        <?php } ?>
                        </div>
                       
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='slide_image_3' id='imagename_3' value='<?php if ($this->projectsDetail[0]['slide_image_3']!='') echo $this->projectsDetail[0]['slide_image_3']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Slide Image 3:(850 * 400)</div>
                <div class="content4-1"><button class="" style="" id="upload_3">Browse</button>
                <?php if($this->projectsDetail[0]['slide_image_3']!='') {?>
                <button id=" " class="" onclick="return delBanner('3')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_3">
                        <?php if ($this->projectsDetail[0]['slide_image_3']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['slide_image_3']; ?>"/> 
                        <?php } ?>
                        </div>
                        
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='slide_image_4' id='imagename_4' value='<?php if ($this->projectsDetail[0]['slide_image_4']!='') echo $this->projectsDetail[0]['slide_image_4']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Slide Image 4:(850 * 400)</div>
                <div class="content4-1"><button class="" style="" id="upload_4">Browse</button>
                    <?php if($this->projectsDetail[0]['slide_image_4']!='') {?>
                <button id=" " class="" onclick="return delBanner('4')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_4" >
                         <?php if ($this->projectsDetail[0]['slide_image_4']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['slide_image_4']; ?>"/> 
                        <?php } ?>
                        </div>
                       
                    </div>
                </div>  
            </div>

            <div class="content2-1">
                <input type='hidden' name='slide_image_5' id='imagename_5' value='<?php if ($this->projectsDetail[0]['slide_image_5']!='') echo $this->projectsDetail[0]['slide_image_5']; ?>'>                
                <div class="content3-1"><span style="color:red">*</span> Slide Image 5:(850 * 400)</div>
                <div class="content4-1"><button class="" style="" id="upload_5">Browse</button>
                    <?php if($this->projectsDetail[0]['slide_image_5']!='') {?>
                <button id=" " class="" onclick="return delBanner('5')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_5" > 
                        <?php if ($this->projectsDetail[0]['slide_image_5']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['slide_image_5']; ?>"/> 
                        <?php } ?>
                        </div>
                        
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='slide_image_6' id='imagename_6' value='<?php if ($this->projectsDetail[0]['slide_image_6']!='') echo $this->projectsDetail[0]['slide_image_6']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Slide Image 6:(850 * 400)</div>
                <div class="content4-1"><button class="" style="" id="upload_6">Browse</button>
                    <?php if($this->projectsDetail[0]['slide_image_6']!='') {?>
                <button id=" " class="" onclick="return delBanner('6')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_6">
                             <?php if ($this->projectsDetail[0]['slide_image_6']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['slide_image_6']; ?>"/> 
                        <?php } ?>
                        </div>
                       
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='slide_image_7' id='imagename_7' value='<?php if ($this->projectsDetail[0]['slide_image_7']!='') echo $this->projectsDetail[0]['slide_image_7']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Slide Image 7:(850 * 400)</div>
                <div class="content4-1"><button class="" style="" id="upload_7">Browse</button>
                    <?php if($this->projectsDetail[0]['slide_image_7']!='') {?>
                <button id=" " class="" onclick="return delBanner('7')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_7">
                             <?php if ($this->projectsDetail[0]['slide_image_7']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['slide_image_7']; ?>"/> 
                        <?php } ?>
                        </div>
                       
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='slide_image_8' id='imagename_8' value='<?php if ($this->projectsDetail[0]['slide_image_8']!='') echo $this->projectsDetail[0]['slide_image_8']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Slide Image 8:(850 * 400)</div>
                <div class="content4-1"><button class="" style="" id="upload_8">Browse</button>
                    <?php if($this->projectsDetail[0]['slide_image_8']!='') {?>
                <button id=" " class="" onclick="return delBanner('8')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_8">
                             <?php if ($this->projectsDetail[0]['slide_image_8']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['slide_image_8']; ?>"/> 
                        <?php } ?>
                        </div>
                       
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='slide_image_9' id='imagename_9' value='<?php if ($this->projectsDetail[0]['slide_image_9']!='') echo $this->projectsDetail[0]['slide_image_9']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Slide Image 9:(850 * 400)</div>
                <div class="content4-1"><button class="" style="" id="upload_9">Browse</button>
                    <?php if($this->projectsDetail[0]['slide_image_9']!='') {?>
                <button id=" " class="" onclick="return delBanner('9')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_9">
                            <?php if ($this->projectsDetail[0]['slide_image_9']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['slide_image_9']; ?>"/> 
                        <?php } ?>
                        </div>
                        
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='slide_image_10' id='imagename_10' value='<?php if ($this->projectsDetail[0]['slide_image_10']!='') echo $this->projectsDetail[0]['slide_image_10']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Slide Image 10:(850 * 400)</div>
                <div class="content4-1"><button class="" style="" id="upload_10">Browse</button>
                    <?php if($this->projectsDetail[0]['slide_image_10']!='') {?>
                <button id=" " class="" onclick="return delBanner('10')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_10">
                            <?php if ($this->projectsDetail[0]['slide_image_10']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['slide_image_10']; ?>"/> 
                        <?php } ?>
                        </div>
                        
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='project_image' id='imagename_11' value='<?php if ($this->projectsDetail[0]['project_image']!='') echo $this->projectsDetail[0]['project_image']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Project Image:(275 * 210)</div>
                <div class="content4-1"><button class="" style="" id="project_image_upload">Browse</button>
                    <?php if($this->projectsDetail[0]['project_image']!='') {?>
                <button id=" " class="" onclick="return delBanner('11')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_11">
                        <?php if ($this->projectsDetail[0]['project_image']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['project_image']; ?>"/> 
                        <?php } ?>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='brochure' id='imagename_12' value='<?php if ($this->projectsDetail[0]['brochure']!='') echo $this->projectsDetail[0]['brochure']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> E-brochure:</div>
                <div class="content4-1"><button class="" style="" id="brochure_upload">Browse</button>
                     <?php if($this->projectsDetail[0]['brochure']!='') {?>
                <button id=" " class="" onclick="return delBanner('12')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_12" style="margin-top: 08px;" >
                        <?php if ($this->projectsDetail[0]['brochure']!='') { ?>
                            <a href="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['brochure']; ?>" target="_blank" style="color:#fff;text-decoration:none"><span style="width:auto;background-color:#333;padding:5px 15px; color:#fff;font-weight:bold;font-size: 12px; ">View File</span></a>
                        <?php } ?>
                        </div>
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='location_map' id='imagename_13' value='<?php if ($this->projectsDetail[0]['location_map']!='') echo $this->projectsDetail[0]['location_map']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Location Map:(675 * 675)</div>
                <div class="content4-1"><button class="" style="" id="location_map_upload">Browse</button>
                    <?php if($this->projectsDetail[0]['location_map']!='') {?>
                <button id=" " class="" onclick="return delBanner('13')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_13">
                            <?php if ($this->projectsDetail[0]['location_map']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['location_map']; ?>"/> 
                        <?php } ?>
                        </div>
                        
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='site_plan' id='imagename_14' value='<?php if ($this->projectsDetail[0]['site_plan']!='') echo $this->projectsDetail[0]['site_plan']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Site Plan:(675 * 675)</div>
                <div class="content4-1"><button class="" style="" id="site_plan_upload">Browse</button>
                    <?php if($this->projectsDetail[0]['site_plan']!='') {?>
                <button id=" " class="" onclick="return delBanner('14')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_14">
                             <?php if ($this->projectsDetail[0]['site_plan']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['site_plan']; ?>"/> 
                        <?php } ?>
                        </div>
                       
                    </div>
                </div>  
            </div>
            <div class="content2-1">
                <input type='hidden' name='application_form' id='imagename_15' value='<?php if ($this->projectsDetail[0]['application_form']!='') echo $this->projectsDetail[0]['application_form']; ?>'>
                <div class="content3-1"><span style="color:red">*</span> Application Form:</div>
                <div class="content4-1"><button class="" style="" id="application_form_upload">Browse</button>
                    <?php if($this->projectsDetail[0]['application_form']!='') {?>
                <button id=" " class="" onclick="return delBanner('15')" style="width:69px;height:28px;margin-left:10px; background-color:#cc0000; color:#fff; border">Delete</button>
                <?php }?>
                    <div class="am2" >
                        <div class="" id="files_15" >
                            <?php if ($this->projectsDetail[0]['application_form']!='') { ?>
                            <img height="50" width="50" style="border:1px solid #ccc;"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->projectsDetail[0]['application_form']; ?>"/> 
                        <?php } ?>
                        </div>
                        
                    </div>
                </div>  
            </div>



  <!--           <div class="content2-1">
                <div class="content3-1"><span style="color:red">*</span>Recommendation:</div>
                <div class="content4-1">
                    <select id="recommendation" name="recommendation" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
                        <?php foreach ($this->stateList as $state) { ?>
                            <option  <?php if ($this->cityDetail[0]['state_id'] == $state['id']) echo "selected" ?> value=<?php echo $state['id'] ?>><?php echo $state['state_name'] ?></option>

<?php } ?>
                    </select>
                </div>
            </div>
-->
            <div class="heading-1">Google Map Latitude & Longitude </div>
            <div class="content2-1">
                <div class="content3-1"><span style="color:red">*</span>Latitude:</div>
                <div class="content4-1">
                    <input type="text" name="latitude" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="latitudeid" value="<?php if (isset($this->projectsDetail[0]['latitude'])) echo $this->projectsDetail[0]['latitude']; ?>"/>
                </div>
            </div>



            <div class="content2-1">
                <div class="content3-1"><span style="color:red">*</span>Longitude: 	
                </div>
                <div class="content4-1">
                    <input type="text" name="longitude" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="longitudeid" value="<?php if (isset($this->projectsDetail[0]['longitude'])) echo $this->projectsDetail[0]['longitude'];?>"/>
                </div>
            </div>
            <div class="content2">
                <div class="content3" Style="font-weight: normal;"><span style="color:red">*</span> Location Advantages: </div>
                <div class="content4-builder">
                    <textarea name="location_advantages" id="location_advantages" style="width:250px; height:56px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" ><?php if (isset($this->projectsDetail[0]['location_advantages'])) echo $this->projectsDetail[0]['location_advantages'];?></textarea>
                </div>
            </div>


            <div class="content5">

                <button onclick="return submitForm()" value="<?php echo $this->heading ?>" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer;padding:5px;"><?php echo $this->heading ?></button>
                <a style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer;padding:5px;text-decoration:none;" href="<?php echo $baseUrl;?>/backend/admin/projectslist">Cancel</a>

            </div>

        </form>

    </div>
</div>

<script>
    $("#cityName").change(function () {
        var cityId = $(this).val();
        SITEROOT = '<?php echo $baseUrl ?>';
        if (cityId != '')
        {
            $.post(SITEROOT + '/backend/admin/getlocations', {cityId: cityId}, function (response) {
                if (response != '') {
                    $('#locationName').html(response);
                    return false;
                } else {
                    $('#locationName').html('');
                    return false;
                }
            });
        } else {
            $('#locationName').html('');
            return false;
        }
    });

    var error = 0;
    function hasNumbers(t) {
        return /\d/.test(t);
    }

    function submitForm(){
		
	// alert(tinyMCE.get('desc').getContent());
		// return false;	
		
	var project_title 	= $('#projecttitle').val();
	var project_plan 	= $('#project_plan').val();
	var address 	    = $('#address').val();
	var builtup_area 	= $('#builtup_area').val();
	var starting_price 	= $('#starting_price').val();
	var buildings 	    = $('#buildings').val();
	//var configurations 	= $('#configurations').val();
	var builder 	    = $('#builder').val();
	var priority        = $('#priority').val();
	var possession 	    = $('#possessiondate').val();
	var cityName 	    = $('#cityName').val();
	var contact 	    = $('#contact').val();
	var display_size   = $('#display_size').val();
	var display_price  = $('#display_price').val();
	var project_status 	= $('#project_status').val();
	var completed_on 	= $('#completed_on').val();
	var search_max_price = $('#search_max_price').val();
	var search_max_price = $('#search_max_price').val();
	var search_min_size  = $('#search_min_size').val();
	var search_max_size  = $('#search_max_size').val();
	var imagename_1 	       = $('#imagename_1').val();
	var imagename_2 	       = $('#imagename_2').val();
	var imagename_3 	       = $('#imagename_3').val();
	var imagename_4 	       = $('#imagename_4').val();
    var imagename_5 	       = $('#imagename_5').val();
	var imagename_11 	       = $('#imagename_11').val();
	var imagename_12 	       = $('#imagename_12').val();
	var imagename_13 	       = $('#imagename_13').val();
	var imagename_14 	       = $('#imagename_14').val();
	var imagename_15 	       = $('#imagename_15').val();
	// var recommendation  = $('#recommendation').val();
	var latitudeid 	   = $('#latitudeid').val();
	var longitudeid    = $('#longitudeid').val();
	var location_advantages  = $('#location_advantages').val();
	
	var error = 0;
	var msg = '';

	if(project_title ==''){
		// alert('project_title  ='+project_title);return false;
		var msg = 'Project Title cannot be empty.';
		error = 1;
	}else if(project_plan =='' ){
		var msg = 'Project Plan cannot be empty.';
		error = 1;
	}else if(address =='' ){
		var msg = 'Address cannot be empty.';
		error = 1;
	}else if(builtup_area =='' ){
		var msg = 'Builtup Area cannot be empty.';
		error = 1;
	}else if(starting_price =='' ){
		var msg = 'Starting Price cannot be empty.';
		error = 1;
	}else if(buildings =='' ){
		var msg = 'Buildings cannot be empty.';
		error = 1;
	}
//    else if(configurations =='' ){
//		var msg = 'Configurations cannot be empty.';
//		error = 1;
//	}
    else if(builder =='' ){
		var msg = 'Builder cannot be empty.';
		error = 1;
	}else if(priority =='' ){
		var msg = 'Priority cannot be empty.';
		error = 1;
	}else if(possession =='' ){
		var msg = 'Possession cannot be empty.';
		error = 1;
	}else if ( tinyMCE.get('desc').getContent() == '' ){
		alert('Description cannot be empty.');
		return false;
	 }else if(cityName =='' ){
		var msg = 'City cannot be empty.';
		error = 1;
	}else if(contact =='' ){
		var msg = 'Contact cannot be empty.';
		error = 1;
	}else if(display_size =='' ){
		var msg = 'Display Size cannot be empty.';
		error = 1;
	}else if(display_price =='' ){
		var msg = 'Display Price cannot be empty.';
		error = 1;
	}else if(project_status =='' ){
		var msg = 'Project Status cannot be empty.';
		error = 1;
	}else if(search_max_price =='' ){
		var msg = 'Search Max Price cannot be empty.';
		error = 1;
	}else if(search_max_price =='' ){
		var msg = 'Search Min Price cannot be empty.';
		error = 1;
	}else if(search_min_size =='' ){
		var msg = 'Search Max Size cannot be empty.';
		error = 1;
	}else if(search_max_size =='' ){
		var msg = 'Search Min Size cannot be empty.';
		error = 1;
	}else if(imagename_1 =='' ){
		var msg = 'Slider Image 1 cannot be empty.';
		error = 1;
	}else if(imagename_2 =='' ){
		var msg = 'Slider Image 2 cannot be empty.';
		error = 1;
	}else if(imagename_3 =='' ){
		var msg = 'Slider Image 3 cannot be empty.';
		error = 1;
	}else if(imagename_4 =='' ){
		var msg = 'Slider Image 4 cannot be empty.';
		error = 1;
	}else if(imagename_5 =='' ){
		var msg = 'Slider Image 5 cannot be empty.';
		error = 1;
	}else if(imagename_11 =='' ){
		var msg = 'Project Image cannot be empty.';
		error = 1;
	}
//    else if(imagename_12 =='' ){
//		var msg = 'E-brochure cannot be empty.';
//		error = 1;
//	}
    else if(imagename_13 =='' ){
		var msg = 'Location Map cannot be empty.';
		error = 1;
	}else if(imagename_14 =='' ){
		var msg = 'Site Plan cannot be empty.';
		error = 1;
	}
//    else if(imagename_15 =='' ){
//		var msg = 'Application Form cannot be empty.';
//		error = 1;
//	}
    else if(latitudeid =='' ){
		var msg = 'Latitude cannot be empty.';
		error = 1;
	}else if(longitudeid =='' ){
		var msg = 'Longitude cannot be empty.';
		error = 1;
	}else if(location_advantages =='' ){
		var msg = 'Location Advantages cannot be empty.';
		error = 1;
	}
    if(contact!=''){
        var filter = /^[0-9-+]+$/;
        if (filter.test(contact)==false) {
            var msg = 'Invalid contact no.';
            error = 1;
        }
    }
	if(msg!=''){
		$("#nameExist").text(msg).show();
        $('#errorMsg').focus();
		return false;
	}else{
        var projectSlug = project_title.replace(/\s+/g, '-').toLowerCase();
        $('#projectSlug').val(projectSlug); 
		$('#projectform').submit();
	}	
	return false;
}


</script>