<?php $baseUrl = $this->basePath(); ?>

<script src="<?php echo $baseUrl;?>/public/js/ajaxupload.3.5.js"></script>
<script type="text/javascript">
var deletedDivArray = [];
$(function(){
	 var btnUpload=$('#upload_1');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,1);
});
$(function(){
	 var btnUpload=$('#upload_2');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,2);
});
$(function(){
	 var btnUpload=$('#upload_3');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,3);
});

	
function ajaxUpload(btnUpload,status,id){
	 var url='<?php echo $baseUrl ?>';
	 var SITEROOT=url+"/admin/upload";
	 new AjaxUpload(btnUpload,
		 {
		     action: SITEROOT,
		     name:'uploadfile' ,
		     onSubmit: function(file, ext){
		         if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
		             // extension is not allowed
		             status.text('Only JPG, PNG or GIF files are allowed');
		             return false;
		         }
		         status.text('Uploading...');
		     },
		     onComplete: function(file, response){
		         //On completion clear the status
		         status.text('');
		         var filepath = url+'/public/uploadfiles/'+response;
		    	 id = parseInt(id);
				$('#files_'+id).html('');
		         if(response != ""){

// 		        	 alert(id);
// 		        	 return false;		         
			         
		             document.getElementById("imagename_"+id).value = response;
		             $('#preview_'+id).show();
		             $('<div></div>').appendTo('#files_'+id).html('<img height="50" width="50"  src="'+filepath+'" alt="" /><br />').addClass('success');
		           //  $('#lastImageId').val(id+1);
		         } else{
		            // $('<div></div>').appendTo('#files').text(response).addClass('error');
		         }
		         
		     }
		 });
}

function previewImage(id){
	$('#files_'+id).toggle();
	return false;
}

function addMore(){
	if(deletedDivArray.length > 0){
		for(var i=0;i<deletedDivArray.length;i++){
			if(deletedDivArray[i]!=''){
				var id = deletedDivArray[i];
			}
		}
		deletedDivArray.pop(id);
	}else{
		var id = $('#lastDivId').val();
		id = parseInt(id)+1;
		if(id<6) $('#lastDivId').val(id);
	}
		$('#div_'+id).show();
	return false;
}

function delDiv(id){
	deletedDivArray.push(id);
	$('#imagename_'+id).val('');
	$('#amenityName_'+id).val('');
	$('#preview_'+id).hide();
	$('#files_'+id).html('');
	$('#div_'+id).hide();
	return false;
}



</script>


<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" name="" id="newsform">
		
    <?php if($this->msg!=''){?>
	<div ><?php echo $this->msg?></div>
	<?php }?>
	<span style="color:#cc0000;margin-left:20px;display:none;" id="nameExist"></span>
	
    <input type='hidden' name='lastDivId' id='lastDivId' value=1>
    
    <div class="content2">
    	<input type='hidden' name='imagename_1' id='imagename_1' value='<?php echo $this->logolist[0]['homelogo']; ?>'>
		<div class="content3"><span style="color:red">*</span> Home Logo:</div>
        <div class="content4-builder"> 
			<button class="" style="height:28px;margin-left:10px;" id="upload_1">Browse</button>

			<button class="" style="height:28px;margin-left:10px;display:none; background-color:#333; color:#fff; border" id="preview_1" onclick="return previewImage('1')">Preview</button>
			<div class="am" >
		        <div class="" id="files_1" style="display: none"></div>
		        <?php if(isset($this->logolist[0]['homelogo'])) {?>
					<img height="60" width="70"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->logolist[0]['homelogo']; ?>"/> 
				<?php }?>
				
	    	</div>
		</div>
		
	</div>
	
    <div class="content2">
    	<input type='hidden' name='imagename_2' id='imagename_2' value='<?php echo $this->logolist[0]['bottomlogo']; ?>'>
		<div class="content3"><span style="color:red">*</span>Header Logo:</div>
        <div class="content4-builder"> 
		<button class="" style="height:28px;margin-left:10px;"  id="upload_2">Browse</button>
		
		<button class="" style="height:28px;margin-left:10px;display:none; background-color:#333; color:#fff; border" id="preview_2" onclick="return previewImage('2')">Preview</button>
		<div class="am" >
	        <div class="" id="files_2" style="display: none"></div>
	        <?php if(isset($this->logolist[0]['bottomlogo'])) {?>
				<img height="60" width="70"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->logolist[0]['bottomlogo']; ?>"/> 
			<?php }?>
			
	    </div>
		
		</div>
	</div>
		
	<div class="content2">
    	<input type='hidden' name='imagename_3' id='imagename_3' value='<?php echo $this->logolist[0]['bottomlogo']; ?>'>
		<div class="content3"><span style="color:red">*</span>Bottom Logo:</div>
        <div class="content4-builder">
		<button class="" style="height:28px;margin-left:10px;" id="upload_3">Browse</button>
		
		<button class="" style="height:28px;margin-left:10px;display:none; background-color:#333; color:#fff; border" id="preview_3" onclick="return previewImage('3')">Preview</button>
		<div class="am" >
        <div class="" id="files_3" style="display: none"></div>
        <?php if(isset($this->logolist[0]['bottomlogo'])) {?>
			<img height="60" width="70"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->logolist[0]['bottomlogo']; ?>"/> 
		<?php }?>
		
    	</div>
		</div>
	</div>
    
  
	<div class="content5">
	
	<button onclick="return submitForm()" value="<?php echo $this->heading?>" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer;padding:5px;"><?php echo $this->heading?></button>
	<a style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer;padding:5px;text-decoration:none;" href="<?php echo $baseUrl;?>/admin/builderlist" >Cancel</a>
	
	</div>
	
	</form>
    
</div>
</div>

