<?php $baseUrl = $this->basePath(); ?>
<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" name="">
		
    <?php if($this->msg!=''){?>
	<div ><?php echo $this->msg?></div>
	<?php }?>
	<div class="content2">
		<div class="content3"><span style="color:red">*</span> State:</div>
        <div class="content4"><input name="state" type="text" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="stateName" value="<?php echo $this->stateDetail[0]['state_name']?>"/></div>
    </div>
	<div class="content5">
	
	<input type="submit" value="<?php echo $this->heading?>" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer;padding:5px;"  />
	<input type="button" value="Cancel" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer;padding:5px;" />
	
	</div>
	
	</form>
    
</div>
</div>

<script>

$("#stateName").blur(function(){
	var name = $(this).val();
	SITEROOT = '<?php echo $baseUrl?>';
	if(name!=''){
		$.post(SITEROOT+'/admin/checkname', {name:name,field:'states'},function(response){
			if(response == '1'){
				alert('Name entered already exists');
				return false;
			}
		});
	}
});
</script>