<?php $baseUrl = $this->basePath(); ?>
<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" name="" id="locationForm">
		
    <?php if($this->msg!=''){?>
	<div ><?php echo $this->msg?></div>
	<?php }?>
	<span style="color:#cc0000;margin-left:20px;display:none;" id="nameExist"></span>
	<div class="content2">
		<div class="content3"><span style="color:red">*</span> State:</div>
        <div class="content4">
        <select id="stateName" name="state"  style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"  >
        	<option value="">Select</option>
        	<?php foreach ($this->stateList as $state){?>
        		<option <?php if($this->locationDetail[0]['state_id']== $state['id']) echo "selected"?> value=<?php echo $state['id']?>><?php echo $state['state_name']?></option>
        	
        	<?php }?>
        </select>
        </div>
    </div>
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> City:</div>
        <div class="content4">
        
        <select id="cityName" name="city" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"  >
        	<?php if(isset($this->cityOptions)){
        		foreach ($this->cityOptions as $city){?>
        		<option <?php if($this->locationDetail[0]['city_id']== $city['id']) echo "selected"?> value=<?php echo $city['id']?>><?php echo $city['city_name']?></option>
        	
        	<?php }}?>
        </select>
        </div>
    </div>
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> Location:</div>
        <div class="content4"><input name="location" type="text" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="locationName" value="<?php if(isset($this->locationDetail[0]['location_name']))echo $this->locationDetail[0]['location_name']?>"/></div>
    </div>
	<div class="content5">
	<button onclick="return submitForm()" value="<?php echo $this->heading?>" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer;padding:5px;">Submit</button>
	<a style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer;padding:5px;text-decoration:none;" href="<?php echo $baseUrl;?>/backend/admin/locationlist" >Cancel</a>
	</div>
	
	</form>
    
</div>
</div>

<script>

$("#stateName").change(function(){
	var stateId = $(this).val();
	SITEROOT = '<?php echo $baseUrl?>';
	$('#locationName').val('');
	if(stateId!='')
	{
		$.post(SITEROOT+'/admin/getcities', {stateId:stateId},function(response){
			if(response!=''){
				$('#cityName').html(response);
				return false;
			}else{
				$('#cityName').html('<option>No Data Found</option>');
				return false;
			}
		});
	}else{
		$('#cityName').html('');
		return false;
	}
});

$('#cityName').change(function(){
	$('#locationName').val('');
});

var error = 0;
function hasNumbers(t){
	return /\d/.test(t);
}

function submitForm(){

	var locationName = $("#locationName").val();
	// var cityName = $("#cityName").val();
	var stateName = $("#stateName").val();
	
	if(stateName == ''){
		$("#nameExist").text('State Name cannot be empty.').show();
		return false;
	}
	if($('#cityName').html() == ''){
		$("#nameExist").text('City Name cannot be empty.').show();
		return false;
	}
	if(locationName == ''){
		$("#nameExist").text('Location Name cannot be empty.').show();
		return false;
	}
	SITEROOT = '<?php echo $baseUrl?>';
	if(locationName!=''){
//		$.post(SITEROOT+'/admin/checkname', {name:locationName,field:'locations'},function(response){
//			if(response == '1'){
//				$("#nameExist").text('Name entered already exists.').show();
//				error = 1;
//				return false;
//			}else{
				if(error==0){
					$('#locationForm').submit();
				}
//			}
//		});
	}
return false;
}

// $("#locationName").blur(function(){
// 	var name = $(this).val();
//	SITEROOT = '<?php echo $baseUrl?>';
// 	if(name!=''){
// 		$.post(SITEROOT+'/admin/checkname', {name:name,field:'locations'},function(response){
// 			if(response == '1'){
// 				alert('Name entered already exists');
// 				return false;
// 			}
// 		});
// 	}
// });




</script>