<?php $baseUrl = $this->basePath(); ?>
<script src="<?php echo $baseUrl;?>/public/js/ajaxupload.3.5.js"></script>
<script type="text/javascript">


var deletedDivArray = [];
$(function(){
	 var btnUpload=$('#upload_1');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,1);
});

function ajaxUpload(btnUpload,status,id){
	 var url='<?php echo $baseUrl ?>';
	 var SITEROOT=url+"/admin/upload";
	 new AjaxUpload(btnUpload,
		 {
		     action: SITEROOT,
		     name:'uploadfile' ,
		     onSubmit: function(file, ext){
		         if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
		             // extension is not allowed
		             status.text('Only JPG, PNG or GIF files are allowed');
		             return false;
		         }
		         status.text('Uploading...');
		     },
		     onComplete: function(file, response){
		         //On completion clear the status
		         status.text('');
		         var filepath = url+'/public/uploadfiles/'+response;
		    	 id = parseInt(id);
				$('#files_'+id).html('');
		         if(response != ""){

// 		        	 alert(id);
// 		        	 return false;		         
			         
		             document.getElementById("imagename_"+id).value = response;
		             $('#preview_'+id).show();
		             $('<div></div>').appendTo('#files_'+id).html('<img height="50" width="50"  src="'+filepath+'" alt="" /><br />').addClass('success');
		           //  $('#lastImageId').val(id+1);
		         } else{
		            // $('<div></div>').appendTo('#files').text(response).addClass('error');
		         }
		         
		     }
		 });
}

function previewImage(id){
	$('#files_'+id).toggle();
	return false;
}


function delDiv(id){
	deletedDivArray.push(id);
	$('#imagename_'+id).val('');
	$('#amenityName_'+id).val('');
	$('#preview_'+id).hide();
	$('#files_'+id).html('');
	$('#div_'+id).hide();
	return false;
}

</script>



<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" name="" id="builderform">
		
    <?php if($this->msg!=''){?>
	<div ><?php echo $this->msg?></div>
	<?php }?>
	<span style="color:#cc0000;margin-left:20px;display:none;" id="nameExist"></span>
	<div class="content2">
		<div class="content3"><span style="color:red">*</span> Builder:</div>
        <div class="content4">
        <input type="text" name="builder_name" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="builder_name" value="<?php if(isset($this->builderDetail[0]['builder_name'])) echo $this->builderDetail[0]['builder_name']; ?>"/>
        </div>
    </div>
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> About Builder:</div>
        <div class="content4-builder">
        <textarea name="about_builder" style="width:250px; height:56px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="about_builder"><?php if(isset($this->builderDetail[0]['builder_name'])) echo $this->builderDetail[0]['builder_name']; ?></textarea>
        </div>
    </div>
     <div class="content2">
    	<input type='hidden' name='imagename_1' id='imagename_1' value='<?php echo $this->builderDetail[0]['builder_image']; ?>'>
		<div class="content3"><span style="color:red">*</span>Image:</div>
        <div class="content4-builder">
			<button class="" style="height:28px;margin-left:10px;" id="upload_1">Browse</button>
			
			<button class="" style="height:28px;margin-left:10px;display:none; background-color:#333; color:#fff; border" id="preview_1" onclick="return previewImage('1')">Preview</button>
			<div class="am" >
		        <div class="" id="files_1" style="display: none"></div>
		        <?php if(isset($this->builderDetail[0]['builder_image'])) {?>
					<img height="60" width="70"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->builderDetail[0]['builder_image']; ?>"/> 
				<?php }?>
				
	    	</div>
		</div>
		
	</div>
	
    
    
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> Meta Tag:</div>
        <div class="content4-builder">
        <textarea name="meta_tag"  style="width:250px; height:56px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="meta_tag"><?php if(isset($this->builderDetail[0]['builder_image'])) echo $this->builderDetail[0]['meta_tag']; ?></textarea>
        </div>
    </div>
    
    <div class="content2">
		<div class="content3"> <span style="color:red">*</span> Keyword:</div>
        <div class="content4-builder">
        <textarea name="keyword" style="width:250px; height:56px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"  id="keyword"><?php if(isset($this->builderDetail[0]['builder_image'])) echo $this->builderDetail[0]['keyword']; ?></textarea>
        </div>
    </div>
    
    <div class="content2">
		<div class="content3"><span style="color:red">*</span>Description:</div>
        <div class="content4">
        <textarea name="description"  style="width:250px; height:56px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"  id="description"><?php if(isset($this->builderDetail[0]['builder_image'])) echo $this->builderDetail[0]['description']; ?></textarea>
        </div>
    </div>
    
    <div class="content2" style="margin-top:120px;">
		<div class="content3"> <span style="color:red">*</span> Priority:</div>
        <div class="content4-builder">
         <input type='text' style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" name='priority' id='priority' value='<?php if(isset($this->builderDetail[0]['priority'])) echo $this->builderDetail[0]['priority']; ?>'>
        </div>
    </div>
    
  
	<div class="content5">
	
	<button onclick="return submitForm()" value="<?php echo $this->heading?>" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer;padding:5px;"><?php echo $this->heading?></button>
	<a style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer;padding:5px;text-decoration:none;" href="<?php echo $baseUrl;?>/admin/builderlist" >Cancel</a>
	
	</div>
	
	</form>
    
</div>
</div>

<script>

var error = 0;
function hasNumbers(t){
	return /\d/.test(t);
}

function submitForm(){
	var builder_name 	= $('#builder_name').val();
	var about_builder 	= $('#about_builder').val();
	var imagename 		= $('#imagename').val();
	var meta_tag 		= $('#meta_tag').val();
	var keyword 		= $('#keyword').val();
	var description 	= $('#description').val();
	var priority 		= $('#priority').val();
	var error = 0;
	var msg = '';
	if(builder_name =='' ){
		var msg = 'Builder Name cannot be empty.';
		error = 1;
	}else if(about_builder =='' ){
		var msg = 'About Builder cannot be empty.';
		error = 1;
	}else if(imagename =='' ){
		var msg = 'Builder Image cannot be empty.';
		error = 1;
	}else if(meta_tag =='' ){
		var msg = 'Meta Tag cannot be empty.';
		error = 1;
	}else if(keyword =='' ){
		var msg = 'Keyword cannot be empty.';
		error = 1;
	}else if(description =='' ){
		var msg = 'Description cannot be empty.';
		error = 1;
	}else if(priority =='' ){
		var msg = 'Priority cannot be empty.';
		error = 1;
	}

	if(msg!=''){
		$("#nameExist").text(msg).show();
		return false;
	}else{
		$('#builderform').submit();
	}	
}

// $("#cityName").blur(function(){
// 	var name = $(this).val();
//	SITEROOT = '<?php echo $baseUrl?>';
// 	if(name!=''){
// 		$.post(SITEROOT+'/admin/checkname', {name:name,field:'cities'},function(response){
// 			if(response == '1'){
// 				alert('Name entered already exists');
// 				return false;
// 			}
// 		});
// 	}
// });
</script>