<?php $baseUrl = $this->basePath(); ?>
<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" name="" id="propertyTypeform">
		
    <?php if($this->msg!=''){?>
	<div ><?php echo $this->msg?></div>
	<?php }?>
	<span style="color:#cc0000;margin-left:20px;display:none;" id="nameExist"></span>
	<div class="content2">
		<div class="content3"><span style="color:red">*</span> Property Category:</div>
        <div class="content4">
        
        <select id="propertyCategory" name="propertyCategory" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
        	<?php foreach ($this->propertyCategoryList as $property){?>
        		<option <?php if($this->propertyTypeDetail[0]['property_category_id']== $property['id']) echo "selected"?> value=<?php echo $property['id']?>><?php echo $property['category_name']?></option>
        	
        	<?php }?>
        </select>
        
        </div>
    </div>
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> Title:</div>
        <div class="content4"><input name="propertyType" type="text" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="propertyType" value="<?php echo $this->propertyTypeDetail[0]['property_type']?>"/></div>
    </div>
	<div class="content5">
	
	<button onclick="return submitForm()" value="<?php echo $this->heading?>" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer;padding:5px;"><?php echo $this->heading?></button>
	<a style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer;padding:5px;text-decoration:none;" href="<?php echo $baseUrl;?>/backend/admin/propertytypelist" >Cancel</a>
	
	</div>
	
	</form>
    
</div>
</div>

<script>
var error = 0;
function hasNumbers(t){
	return /\d/.test(t);
}
$('#propertyCategory').change(function(){
	$('#propertyType').val('');
});
function submitForm(){

	var propertyType = $("#propertyType").val();
	if(propertyType == ''){
		$("#nameExist").text('Property Type cannot be empty.').show();
		return false;
	}
	SITEROOT = '<?php echo $baseUrl?>';
	if(propertyType!=''){
//		$.post(SITEROOT+'/admin/checkname', {name:propertyType,field:'property_type'},function(response){
//			if(response == '1'){
//				$("#nameExist").text('Name entered already exists.').show();
//				error = 1;
//				return false;
//			}else{
				var chknumber = hasNumbers($('#propertyType').val());
				if(chknumber==true){
					$("#nameExist").text('Property Type cannot have numbers.').show();
					error = 1;
					return false;
				}else{
					$("#nameExist").hide();
					error = 0;
				}
				if(error==0){
					$('#propertyTypeform').submit();
				}
//			}
//		});
	}
return false;
}
// $("#cityName").blur(function(){
// 	var name = $(this).val();
//	SITEROOT = '<?php echo $baseUrl?>';
// 	if(name!=''){
// 		$.post(SITEROOT+'/admin/checkname', {name:name,field:'cities'},function(response){
// 			if(response == '1'){
// 				alert('Name entered already exists');
// 				return false;
// 			}
// 		});
// 	}
// });
</script>