<?php $baseUrl = $this->basePath(); 

// 	echo '<pre>';print_r($this->cityDetail);exit; 

?>
<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" name="">
		
    <?php if($this->msg!=''){?>
	<div ><?php echo $this->msg?></div>
	<?php }?>
	<div class="content2">
		<div class="content3"><span style="color:red">*</span> State:</div>
        <div class="content4">
        
        <select id="stateName" name="state"  style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"  >
        	<option value="">Select</option>
        	<?php foreach ($this->stateList as $state){?>
        		<option <?php if($this->locationDetail[0]['state_id']== $state['id']) echo "selected"?> value=<?php echo $state['id']?>><?php echo $state['state_name']?></option>
        	
        	<?php }?>
        </select>
        </div>
    </div>
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> City:</div>
        <div class="content4">
        
        <select id="cityName" name="city" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;"  >
        	<?php if(isset($this->cityOptions)){
        		foreach ($this->cityOptions as $city){?>
        		<option <?php if($this->locationDetail[0]['city_id']== $city['id']) echo "selected"?> value=<?php echo $city['id']?>><?php echo $city['city_name']?></option>
        	
        	<?php }}?>
        </select>
        </div>
    </div>
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> Location:</div>
        <div class="content4"><input name="location" type="text" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="locationName" value="<?php if(isset($this->locationDetail[0]['location_name']))echo $this->locationDetail[0]['location_name']?>"/></div>
    </div>
	<div class="content5">
	
	<input type="submit" value="Add Location"  style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer; padding:5px;" />
	<input type="button" value="Cancel" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer; padding:5px;" />
	
	</div>
	
	</form>
    
</div>
</div>

<script>

$("#stateName").change(function(){
	var stateId = $(this).val();
	SITEROOT = '<?php echo $baseUrl?>';
	$('#locationName').val('');
	if(stateId!='')
	{
		$.post(SITEROOT+'/admin/getcities', {stateId:stateId},function(response){
			if(response!=''){
				$('#cityName').html(response);
				return false;
			}
		});
	}
	
});



$('#cityName').change(function(){
	$('#locationName').val('');
});


$("#locationName").blur(function(){
	var name = $(this).val();
	SITEROOT = '<?php echo $baseUrl?>';
	if(name!=''){
		$.post(SITEROOT+'/admin/checkname', {name:name,field:'locations'},function(response){
			if(response == '1'){
				alert('Name entered already exists');
				return false;
			}
		});
	}
});
</script>