<?php $baseUrl = $this->basePath(); 

// 	echo '<pre>';print_r($this->cityDetail);exit; 

?>
<script src="<?php echo $baseUrl;?>/js/ajaxupload.3.5.js"></script>
<script type="text/javascript">

$(function(){
 var btnUpload=$('#upload');


//  alert('dddd');return false;



 var status=$('#status');
 var url='<?php echo $baseUrl ?>';
 var SITEROOT=url+"/admin/upload";
	
 
 new AjaxUpload(btnUpload,
 {

// 	 alert('dddd');return false;
	 
     action: SITEROOT,
     name:'uploadfile' ,
     onSubmit: function(file, ext){

         if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
             // extension is not allowed
             status.text('Only JPG, PNG or GIF files are allowed');
             return false;
         }
         status.text('Uploading...');
     },
     onComplete: function(file, response){
         //On completion clear the status
         status.text('');
         var filepath = url+'/uploadfiles/'+response;
         var xp = document.getElementById('files');
         while(xp.hasChildNodes()){
             document.getElementById('files').removeChild(xp.firstChild);
         }

         if(response != ""){
             document.getElementById("imagename").value = response;
             $('<div></div>').appendTo('#files').html('<img height="50" width="50"  src="'+filepath+'" alt="" /><br />').addClass('success');
         } else{
             $('<div></div>').appendTo('#files').text(response).addClass('error');
         }
     }
 });

});

</script>



<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" name="">
		
    <?php if($this->msg!=''){?>
	<div ><?php echo $this->msg?></div>
	<?php }?>
	<div class="content2">
		<div class="content3"><span style="color:red">*</span> Type:</div>
        <div class="content4">
        
        <select id="amenityType" name="amenityType" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
        	<?php foreach ($this->amenityTypeList as $amenityType){?>
        		<option <?php if($this->amenityDetail[0]['amenity_type_id']== $amenityType['id']) echo "selected"?> value=<?php echo $amenityType['id']?>><?php echo $amenityType['amenity_type']?></option>
        	
        	<?php }?>
        </select>
        
        </div>
    </div>
    <div class="content2">
    	 <input type='hidden' name='imagename' id='imagename' value='<?php echo $this->amenityDetail[0]['amenity_image']; ?>'>
		<div class="content3"><span style="color:red">*</span> Title / Image:</div>
        <div class="content4"> <input name="amenityName" type="text" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="amenityName" value="<?php echo $this->amenityDetail[0]['amenity_name']; ?>"/>
		<button class="" style="height:28px;margin-left:10px;" id="upload">Browse</button>
		<button class="" style="height:28px;margin-left:10px; background-color:#333; color:#fff; border" id="upload">Preview</button>
		<button class="" style="height:28px;margin-left:10px; background-color:#333; color:#fff; border" id="upload">+ Next</button>
		<div class="am" >
        <div class="" id="files">
        <?php if(isset($this->amenityDetail[0]['amenity_image'])) {?>
			<img height="60" width="70"  src="<?php echo $baseUrl; ?>/uploadfiles/<?php echo $this->amenityDetail[0]['amenity_image']; ?>"/> 
		<?php }?>
		</div>
    </div>
		
		</div>
		</div>
		
	
   </div>
	<div class="content5" style="padding-left:311px">
	
	<input type="submit" value="Add Amenities" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer; padding:5px;" />
	<input type="button" value="Cancel" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer; padding:5px;" />
	
	</div>
	
	</form>
    
</div>
</div>

<script>

$("#cityName").blur(function(){
	var name = $(this).val();
	SITEROOT = '<?php echo $baseUrl?>';
	if(name!=''){
		$.post(SITEROOT+'/admin/checkname', {name:name,field:'cities'},function(response){
			if(response == '1'){
				alert('Name entered already exists');
				return false;
			}
		});
	}
});
</script>