<?php $baseUrl = $this->basePath(); ?>
<script src="<?php echo $baseUrl;?>/public/js/ajaxupload.3.5.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/public/tinmca/jscripts/tiny_mce/tiny_mce.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        // General options
        mode: "exact",
        elements: "about_builder,preq",
        theme: "advanced",
        width: "100%",
        height: 310,
        plugins: "jbimages,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",
        // Theme options
        theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,code,",
        theme_advanced_buttons2: "",
        theme_advanced_buttons3: "",
        //theme_advanced_buttons3 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft",
        //theme_advanced_buttons4 : "",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        theme_advanced_statusbar_location: "bottom",
        theme_advanced_resizing: true,
        // Example content CSS (should be your site CSS)
        content_css: "<?php echo $baseUrl; ?>/js/tinmca/css/content.css",
        // Drop lists for link/image/media/template dialogs
        template_external_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/template_list.js",
        external_link_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/link_list.js",
        external_image_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/image_list.js",
        media_external_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/media_list.js",
        // Style formats
        style_formats: [
            {title: 'Bold text', inline: 'b'},
            {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
            {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
            {title: 'Example 1', inline: 'span', classes: 'example1'},
            {title: 'Example 2', inline: 'span', classes: 'example2'},
            {title: 'Table styles'},
            {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ],
        relative_urls: false,
        // Replace values for the template plugin
        template_replace_values: {
            username: "Some User",
            staffid: "991234"
        },
        autosave_ask_before_unload: false
    });
</script>
<script type="text/javascript">


var deletedDivArray = [];
$(function(){
	 var btnUpload=$('#upload_1');
	 var status=$('#status');
	 ajaxUpload(btnUpload,status,1);
});

function ajaxUpload(btnUpload,status,id){
	 var url='<?php echo $baseUrl ?>';
	 var SITEROOT=url+"/admin/upload";
	 new AjaxUpload(btnUpload,
		 {
		     action: SITEROOT,
		     name:'uploadfile' ,
		     onSubmit: function(file, ext){
		         if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
		             // extension is not allowed
		             status.text('Only JPG, PNG or GIF files are allowed');
		             return false;
		         }
		         status.text('Uploading...');
		     },
		     onComplete: function(file, response){
		         //On completion clear the status
		         status.text('');
		         var filepath = url+'/public/uploadfiles/'+response;
		    	 id = parseInt(id);
				$('#files_'+id).html('');
		         if(response != ""){

// 		        	 alert(id);
// 		        	 return false;		         
			         
		             document.getElementById("imagename_"+id).value = response;
		             $('#preview_'+id).show();
		             $('<div></div>').appendTo('#files_'+id).html('<img height="50" width="50"  src="'+filepath+'" alt="" /><br />').addClass('success');
		           //  $('#lastImageId').val(id+1);
		         } else{
		            // $('<div></div>').appendTo('#files').text(response).addClass('error');
		         }
		         
		     }
		 });
}

function previewImage(id){
	$('#files_'+id).toggle();
	return false;
}


function delDiv(id){
	deletedDivArray.push(id);
	$('#imagename_'+id).val('');
	$('#amenityName_'+id).val('');
	$('#preview_'+id).hide();
	$('#files_'+id).html('');
	$('#div_'+id).hide();
	return false;
}

</script>



<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" name="" id="builderform">
	<input type="hidden" id="builderId" value="<?php if(isset($this->builderDetail[0]['id'])) echo $this->builderDetail[0]['id']; ?>" />	
    <?php if($this->msg!=''){?>
	<div ><?php echo $this->msg?></div>
	<?php }?>
	<span style="color:#cc0000;margin-left:20px;display:none;" id="nameExist"></span>
	<div class="content2">
		<div class="content3"><span style="color:red">*</span> Builder:</div>
        <div class="content4">
        <input type="text" name="builder_name" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="builder_name" value="<?php if(isset($this->builderDetail[0]['builder_name'])) echo $this->builderDetail[0]['builder_name']; ?>"/>
        </div>
    </div>
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> About Builder:</div>
        <div class="content4-1-2">
        <textarea name="about_builder" style="width:250px; height:56px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="about_builder"><?php if(isset($this->builderDetail[0]['about_builder'])) echo $this->builderDetail[0]['about_builder']; ?></textarea>
        </div>
    </div>
     <div class="content2">
    	<input type='hidden' name='imagename_1' id='imagename_1' value='<?php echo $this->builderDetail[0]['builder_image']; ?>'>
		<div class="content3"><span style="color:red">*</span>Image:(200 * 67)</div>
        <div class="content4-builder">
			<button class="" style="height:28px;margin-left:10px;" id="upload_1">Browse</button>
			
			<button class="" style="height:28px;margin-left:10px;display:none; background-color:#333; color:#fff; border" id="preview_1" onclick="return previewImage('1')">Preview</button>
			<div class="am" >
		        <div class="" id="files_1" style="display: none"></div>
		        <?php if(isset($this->builderDetail[0]['builder_image'])) {?>
					<img height="60" width="70"  src="<?php echo $baseUrl; ?>/public/uploadfiles/<?php echo $this->builderDetail[0]['builder_image']; ?>"/> 
				<?php }?>
				
	    	</div>
		</div>
		
	</div>
	
    
    
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> Add Experience:</div>
        <div class="content4-builder">
        <input type='text' style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" name='experience' id='experience' value='<?php if(isset($this->builderDetail[0]['builder_experience'])) echo $this->builderDetail[0]['builder_experience']; ?>'>
        </div>
    </div>
    
    
    
    <div class="content2" style="margin-top:120px;">
		<div class="content3"> <span style="color:red">*</span> Priority:</div>
        <div class="content4-builder">
         <input type='text' style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" name='priority' id='priority' value='<?php if(isset($this->builderDetail[0]['priority'])) echo $this->builderDetail[0]['priority']; ?>'>
        </div>
    </div>
    
  
	<div class="content5">
	
	<button onclick="return submitForm()" value="<?php echo $this->heading?>" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer;padding:5px;"><?php echo $this->heading?></button>
	<a style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer;padding:5px;text-decoration:none;" href="<?php echo $baseUrl;?>/admin/builderlist" >Cancel</a>
	
	</div>
	
	</form>
    
</div>
</div>

<script>

var error = 0;
function hasNumbers(t){
	return /\d/.test(t);
}

function submitForm(){
    SITEROOT = '<?php echo $baseUrl?>';
	var builderId       = $('#builderId').val();
	var builder_name 	= $('#builder_name').val();
	var imagename 		= $('#imagename_1').val();
	var experience 		= $('#experience').val();
	var priority 		= $('#priority').val();
	var error = 0;
	var msg = '';
    
    
	if(builder_name =='' ){
		var msg = 'Builder Name cannot be empty.';
		error = 1;
	}else if ( tinyMCE.get('about_builder').getContent() == '' ){
        var msg = 'Description cannot be empty.';
		error = 1;
	 }else if(imagename =='' ){
		var msg = 'Builder Image cannot be empty.';
		error = 1;
	}else if(experience =='' ){
		var msg = 'Builder Experience cannot be empty.';
		error = 1;
	}else if(priority =='' ){
		var msg = 'Priority cannot be empty.';
		error = 1;
	}
    
	if(msg!=''){
		$("#nameExist").text(msg).show();
		return false;
	}
    if(builderId==''){
        
 		$.post(SITEROOT+'/admin/checkname', {name:builder_name,field:'builders'},function(response){
 			if(response == '1'){
                var msg = 'Builder Name entered already exists';
                $("#nameExist").text(msg).show();
                return false;
 			}else{
                $('#builderform').submit();
            }
 		});
 	}else{
         $('#builderform').submit();
    }
    return false;
}

</script>