<?php $baseUrl = $this->basePath(); ?>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/public/tinmca/jscripts/tiny_mce/tiny_mce.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        // General options
        mode: "exact",
        elements: "pagedesc,preq",
        theme: "advanced",
        width: "100%",
        height: 310,
        plugins: "jbimages,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",
        // Theme options
        theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,code,",
        theme_advanced_buttons2: "",
        theme_advanced_buttons3: "",
        //theme_advanced_buttons3 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft",
        //theme_advanced_buttons4 : "",
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        theme_advanced_statusbar_location: "bottom",
        theme_advanced_resizing: true,
        // Example content CSS (should be your site CSS)
        content_css: "<?php echo $baseUrl; ?>/js/tinmca/css/content.css",
        // Drop lists for link/image/media/template dialogs
        template_external_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/template_list.js",
        external_link_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/link_list.js",
        external_image_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/image_list.js",
        media_external_list_url: "<?php echo $baseUrl; ?>/js/tinmca/lists/media_list.js",
        // Style formats
        style_formats: [
            {title: 'Bold text', inline: 'b'},
            {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
            {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
            {title: 'Example 1', inline: 'span', classes: 'example1'},
            {title: 'Example 2', inline: 'span', classes: 'example2'},
            {title: 'Table styles'},
            {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
        ],
        relative_urls: false,
        // Replace values for the template plugin
        template_replace_values: {
            username: "Some User",
            staffid: "991234"
        },
        autosave_ask_before_unload: false
    });
</script>
<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" id="pageform">
    <?php if($this->msg!=''){?>
	<div><?php echo $this->msg?></div>
	<?php }?>
	<div class="content2">
		<div class="content3"><span style="color:red">*</span> Pages:</div>
        <div class="content4"> 
		<select id="pageName" name="page" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
		<option value='' >Select Page Name</option>
		<?php 
		//print_r();
		foreach ($this->pageList as $pages){
		?>
		<option value=<?php echo $pages['id']?> ><?php echo $pages['page_name'];?></option>
		<?php } ?>
		</select><span style="color:#cc0000;margin-left:20px;display:none;" id="nameExist"></span></div>
    </div>
	<div class="content2">
	<div class="content3"><span style="color:red">*</span>Description:</div>
        <div class="content4-1-2"><textarea name="desc" value="" style="width:250px; height:50px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="pagedesc" />
				
				</textarea><span style="color:#cc0000;margin-left:20px;display:none;" id="nameExist"> </span></div>
    </div>
	</div>
	<div class="content5">
	
	<button onclick="return submitForm()" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer;padding:5px;"><?php echo $this->heading?></button>
	<a style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer;padding:5px;text-decoration:none;" href="<?php echo $baseUrl;?>/admin/statelist" >Cancel</a>
	
	</div>
	
	</form>
    
</div>
</div>
<script>

$("#pageName").change(function(){
	var PageId = $(this).val();
	SITEROOT = '<?php echo $baseUrl?>';
	if(PageId!='')
	{
		$.post(SITEROOT+'/admin/getpages', {PageId:PageId},function(response){
			if(response!=''){
				//$('#pagedesc').html(response);
				tinyMCE.get('pagedesc').setContent(response);
				return false;
			}else{
				tinyMCE.get('pagedesc').setContent('');
				return false;
			}
		});
	}else{
		tinyMCE.get('pagedesc').setContent('');
		return false;
	}
});





</script>

