<?php $baseUrl = $this->basePath(); 

// 	echo '<pre>';print_r($this->cityDetail);exit; 

?>
<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" name="">
		
    <?php if($this->msg!=''){?>
	<div ><?php echo $this->msg?></div>
	<?php }?>
	<div class="content2">
		<div class="content3"><span style="color:red">*</span> Property Category:</div>
        <div class="content4">
        
        <select id="propertyCategory" name="propertyCategory" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
        	<?php foreach ($this->propertyCategoryList as $property){?>
        		<option <?php if($this->propertyTypeDetail[0]['property_category_id']== $property['id']) echo "selected"?> value=<?php echo $property['id']?>><?php echo $property['category_name']?></option>
        	
        	<?php }?>
        </select>
        
        </div>
    </div>
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> Title:</div>
        <div class="content4"><input name="propertyType" type="text" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="propertyType" value="<?php echo $this->propertyTypeDetail[0]['property_type']?>"/></div>
    </div>
	<div class="content5">
	
	<input type="submit" value="Add Type"   style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer; padding:5px;" />
	<input type="button" value="Cancel" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer; padding:5px;" />
	
	</div>
	
	</form>
    
</div>
</div>

<script>

$("#cityName").blur(function(){
	var name = $(this).val();
	SITEROOT = '<?php echo $baseUrl?>';
	if(name!=''){
		$.post(SITEROOT+'/admin/checkname', {name:name,field:'cities'},function(response){
			if(response == '1'){
				alert('Name entered already exists');
				return false;
			}
		});
	}
});
</script>