<?php $baseUrl = $this->basePath(); 

// 	echo '<pre>';print_r($this->cityDetail);exit; 

?>
<script src="<?php echo $baseUrl;?>/js/ajaxupload.3.5.js"></script>
<script type="text/javascript">

$(function(){
 var btnUpload=$('#upload');


//  alert('dddd');return false;



 var status=$('#status');
 var url='<?php echo $baseUrl ?>';
 var SITEROOT=url+"/admin/upload";
	
 
 new AjaxUpload(btnUpload,
 {

// 	 alert('dddd');return false;
	 
     action: SITEROOT,
     name:'uploadfile' ,
     onSubmit: function(file, ext){

         if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
             // extension is not allowed
             status.text('Only JPG, PNG or GIF files are allowed');
             return false;
         }
         status.text('Uploading...');
     },
     onComplete: function(file, response){
         //On completion clear the status
         status.text('');
         var filepath = url+'/uploadfiles/'+response;
         var xp = document.getElementById('files');
         while(xp.hasChildNodes()){
             document.getElementById('files').removeChild(xp.firstChild);
         }

         if(response != ""){
             document.getElementById("imagename").value = response;
             $('<div></div>').appendTo('#files').html('<img class="" height="100" width="100" src="'+filepath+'" alt="" /><br />').addClass('success');
         } else{
             $('<div></div>').appendTo('#files').text(response).addClass('error');
         }
     }
 });

});

</script>



<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" name="">
		
    <?php if($this->msg!=''){?>
	<div ><?php echo $this->msg?></div>
	<?php }?>
	<div class="content2">
		<div class="content3">Type:</div>
        <div class="content4">
        
        <select id="amenityType" name="amenityType" style="width:200px"; >
        	<?php foreach ($this->amenityTypeList as $amenityType){?>
        		<option <?php if($this->amenityDetail[0]['amenity_type_id']== $amenityType['id']) echo "selected"?> value=<?php echo $amenityType['id']?>><?php echo $amenityType['amenity_type']?></option>
        	
        	<?php }?>
        </select>
        
        </div>
    </div>
    <div class="content2">
    	 <input type='hidden' name='imagename' id='imagename' value='<?php echo $this->amenityDetail[0]['amenity_image']; ?>'>
		<div class="content3">Image:</div>
        <div class="content4"><button class="" style="" id="upload">Upload</button>
		</div>
		
		
        <div class="" id="files">
        <?php if(isset($this->amenityDetail[0]['amenity_image'])) {?>
			<img height="100" width="100" src="<?php echo $baseUrl; ?>/uploadfiles/<?php echo $this->amenityDetail[0]['amenity_image']; ?>"/> 
		<?php }?>
		</div>
    </div>
    <div class="content2">
		<div class="content3">Title:</div>
        <div class="content4"><input name="amenityName" type="text" style="width:200px"; id="amenityName" value="<?php echo $this->amenityDetail[0]['amenity_name']; ?>"/></div>
    </div>
	<div class="content5">
	
	<input type="submit" value="Submit" style="width:100px; height:30px; background-color:#CC0000; color:#FFFFFF; border:none;" />
	<input type="button" value="Cancel" style="width:100px; height:30px; background-color:#CC0000; color:#FFFFFF; border:none;" />
	
	</div>
	
	</form>
    
</div>
</div>

<script>

$("#cityName").blur(function(){
	var name = $(this).val();
	SITEROOT = '<?php echo $baseUrl?>';
	if(name!=''){
		$.post(SITEROOT+'/admin/checkname', {name:name,field:'cities'},function(response){
			if(response == '1'){
				alert('Name entered already exists');
				return false;
			}
		});
	}
});
</script>