<?php $baseUrl = $this->basePath(); ?>
<div class="contant">
<div class="heading"><?php echo $this->heading?></div>
<div class="contant1">
	<form method="post" action="" id="cityform">
		
    <?php if($this->msg!=''){?>
	<div><?php echo $this->msg?></div>
	<?php }?>
	<span style="color:#cc0000;margin-left:20px;display:none;" id="nameExist"></span>
	<div class="content2">
		<div class="content3"><span style="color:red">*</span> State:</div>
        <div class="content4">
        
        <select id="stateName" name="state" style="width:250px; height:33px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" >
        	<?php foreach ($this->stateList as $state){?>
        		<option  <?php if($this->cityDetail[0]['state_id']== $state['id']) echo "selected"?> value=<?php echo $state['id']?>><?php echo $state['state_name']?></option>
        	
        	<?php }?>
        </select>
        
        </div>
    </div>
    <div class="content2">
		<div class="content3"><span style="color:red">*</span> City:</div>
        <div class="content4"><input name="city" type="text" style="width:250px; height:28px; border-radius:3px;border:1px solid #aaa; background-color:#f9f9f9;" id="cityName" value="<?php echo $this->cityDetail[0]['city_name']?>" /></div>
    </div>
	<div class="content5">
	
	<button onclick="return submitForm()" value="<?php echo $this->heading?>" style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px;cursor: pointer;padding:5px;">Submit</button>
	<a style="width:auto; height:28px; background-color:#CC0000; color:#FFFFFF; border:none; border-radius: 3px; margin-left:10px;cursor: pointer;padding:5px;text-decoration:none;" href="<?php echo $baseUrl;?>/admin/citylist" >Cancel</a>
	
	</div>
	
	</form>
    
</div>
</div>

<script>
var error = 0;
function hasNumbers(t){
	return /\d/.test(t);
}
//$('#stateName').change(function(){
//	$('#cityName').val('');
//});
function submitForm(){

	var name = $("#cityName").val();
	if(name == ''){
		$("#nameExist").text('City Name cannot be empty.').show();
		return false;
	}
	SITEROOT = '<?php echo $baseUrl?>';
	if(name!=''){
		$.post(SITEROOT+'/admin/checkname', {name:name,field:'cities'},function(response){
			if(response == '1'){
				$("#nameExist").text('Name entered already exists.').show();
				error = 1;
				return false;
			}else{
				var chknumber = hasNumbers($('#cityName').val());
				if(chknumber==true){
					$("#nameExist").text('City Name cannot have numbers.').show();
					error = 1;
					return false;
				}else{
					$("#nameExist").hide();
					error = 0;
				}
                var splChars = "*|,\":<>[]{}`\';()@&$#%";
                for (var i = 0; i < name.length; i++) {
                    if (splChars.indexOf(name.charAt(i)) != -1){
                    $("#nameExist").text('Illegal characters detected.').show();
					error = 1;
					return false;
                    }
                }
				if(error==0){
					$('#cityform').submit();
				}
			}
		});
	}
return false;
}
// $("#cityName").blur(function(){
// 	var name = $(this).val();
//	SITEROOT = '<?php echo $baseUrl?>';
// 	if(name!=''){
// 		$.post(SITEROOT+'/admin/checkname', {name:name,field:'cities'},function(response){
// 			if(response == '1'){
// 				alert('Name entered already exists');
// 				return false;
// 			}
// 		});
// 	}
// });
</script>