<?php $baseUrl = $this->basePath(); ?>
<div class="contant">
<div class="heading">Dashboard</div>
<!----img area----->
<div class="dashboard-contant1" style="border:1px solid #ccc;">
	<div class="dashboard-img">
    	<div class="dashboard-img1" style="border-bottom:1px solid #ccc; border-right:1px solid #ccc;"><a href='<?php echo $baseUrl;?>/admin/location'><img src="<?php echo $baseUrl;?>/adminpanel/img/ad4.png" height="80px;" /></a>
		<br>
		<span class="dashboard-text" ><a href='<?php echo $baseUrl;?>/admin/location' > Manage Location</a> </span> 
		
		</div>
		
        <div class="dashboard-img1" style="border-bottom:1px solid #ccc; border-right:1px solid #ccc;"><a href='<?php echo $baseUrl;?>/admin/propertytypelist'><img src="<?php echo $baseUrl;?>/adminpanel/img/propertytype.jpeg" height="80px;" /></a>
		<br>
		<span class="dashboard-text" ><a href='<?php echo $baseUrl;?>/admin/propertytypelist' >Manage Property Type</a> </span> 
		</div>
		
        <div class="dashboard-img1" style="border-bottom:1px solid #ccc; border-right:1px solid #ccc;"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/download.jpg" height="80px;" /></a>
		<br>
		<span class="dashboard-text" ><a href="#" > Manage Amenities</a> </span> 
		</div>
		
			<div class="dashboard-img1"style="border-bottom:1px solid #ccc;"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/builder.jpg" height="80px;" /></a>
			<br>
		<span class="dashboard-text" ><a href="#" > Manage Builders</a> </span> 
			</div>
        
		
		<div class="dashboard-img1" style=" border-right:1px solid #ccc;"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/projects_icon.jpg" height="80px;" /></a>
		<br>
		<span class="dashboard-text" ><a href="#" > Manage Projects</a> </span> 
		</div>
		
        <div class="dashboard-img1" style=" border-right:1px solid #ccc;"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/cms.jpg" height="80px;" /></a>
		<br>
		<span class="dashboard-text" ><a href="#" > Manage CMS</a> </span> 
		</div>
		
        <div class="dashboard-img1" style=" border-right:1px solid #ccc;"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/news.jpg" height="80px;" /></a>
		<br>
		<span class="dashboard-text" ><a href="#" > Manage News </a> </span> 
		
		</div>
		
			<div class="dashboard-img1"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/ad8.jpg" height="80px;" /></a>
			
			<br>
		<span class="dashboard-text" ><a href="#" >Manage Logo </a> </span> 
			</div>
        
    </div>
</div>
</div>