<?php $baseUrl = $this->basePath(); ?>
<div class="contant">
<div class="heading">Location</div>
<!----img area----->
<div class="contant1">
	<div class="img">
    	<div class="img1"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/news.jpg" height="80px;" /></a></div>
        <div class="img1"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/news.jpg" height="80px;" /></a></div>
        <div class="img1"><a href=""><img src="<?php echo $baseUrl;?>/adminpanel/img/news.jpg" height="80px;" /></a></div>
    </div>
</div>
</div>