<?php $baseUrl = $this->basePath(); ?>
<div class="contant">
<div class="heading">Location</div>
<!----img area----->
<div class="dashboard-contant1">
	<div class="dashboard-img">
    	<div class="dashboard-img1" style="border:1px solid #ccc;"><a href='<?php echo $baseUrl;?>/admin/statelist'><img src="<?php echo $baseUrl;?>/adminpanel/img/state.png" height="80px;" /></a>
		<br>
		<span class="dashboard-text" ><a href='<?php echo $baseUrl;?>/admin/statelist' > Manage State</a> </span> 
		
		</div>
		
        <div class="dashboard-img1" style="border-top:1px solid #ccc; border-bottom:1px solid #ccc; " ><a href='<?php echo $baseUrl;?>/admin/citylist'><img src="<?php echo $baseUrl;?>/adminpanel/img/city.png" height="80px;" /></a>
		<br>
		<span class="dashboard-text" ><a href='<?php echo $baseUrl;?>/admin/citylist' >Manage City</a> </span> 
		</div>
		
        <div class="dashboard-img1" style="border:1px solid #ccc; "><a href='<?php echo $baseUrl;?>/admin/locationlist'><img src="<?php echo $baseUrl;?>/adminpanel/img/location.png" height="80px;" /></a>
		<br>
		<span class="dashboard-text" ><a href='<?php echo $baseUrl;?>/admin/locationlist' >Manage Location</a> </span> 
		</div>
		
			
		
		
		
       
		
       
		
			
        
    </div>
</div>
</div>