<?php $baseUrl = $this->basePath(); ?>


<div class="container">
	<div class="margin_top12"></div>
	<div class="page-header">
  <div class="clearfix"></div>  
  <h3>My Portfolio</h3></div>
	
   
<div class="container margin_top2">
<div class="content_left">        
    <p style="text-align:justify;">ppp</p>     
</div><!-- end content left side -->


<!-- right sidebar starts -->
<div class="right_sidebar">
	<div class="sidebar_widget">    
    	<div class="sidebar_title">
        <div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text">My Account</span></h3></div>
        </div>        
		<ul class="arrows_list1">        
            <li><a href="<?php echo $baseUrl;?>/user/portfolio"><i class="fa fa-angle-right"></i> My Portfolio</a></li>
            <li><a href="<?php echo $baseUrl;?>/user/recently-viewed"><i class="fa fa-angle-right"></i> Recently Viewed</a></li>
            <li><a href="<?php echo $baseUrl;?>/user/enquired-properties"><i class="fa fa-angle-right"></i> Enquired Properties</a></li>
            <li><a href="<?php echo $baseUrl;?>/user/account-settings"><i class="fa fa-angle-right"></i> Account Settings</a></li>          
		</ul>              
	</div><!-- end section -->
    <div class="margin_top5"></div>
    <div class="sidebar_widget">    
    	<div class="sidebar_title">
        <div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text">Quick Links</span></h3></div>
        </div>        
		<ul class="arrows_list1">        
             <li><a href="property-buying-step.html"><i class="fa fa-angle-right"></i> Property Buying Steps</a></li>
            <li><a href="home-loan.html"><i class="fa fa-angle-right"></i> Home Loan</a></li>
            <li><a href="vaastu-tips.html"><i class="fa fa-angle-right"></i> Vaastu Tips</a></li>
            <li><a href="emi.html"><i class="fa fa-angle-right"></i> EMI Calculator</a></li>
            <li><a href="nri.html"><i class="fa fa-angle-right"></i> NRI services</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Real Estate News</a></li> 
		</ul>              
	</div>
    
</div><!-- end right sidebar -->

</div>
    
    <!-- end section -->
    
</div>
    
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
    $(document).ready(function(){
        $('#pageTitle').text('Aadinath | My Portfolio');
    });
    </script>


<!---End of Builder--->



  
  