<?php $baseUrl = $this->basePath(); ?>

<div class="slidermar9">
    
  <div class="page_title1 sty8">
<div class="container">	
    <h1 style="text-shadow: 2px 2px #000;">About Us</h1>     
</div>
</div><!-- end page title --> 
<div class="clearfix"></div>
<div class="content_fullwidth less2">

<!---About Intro--->
<div class="container">
    
    <div class="one_half">  
            <div><img src="<?php echo $baseUrl?>/public/images/about-intrologo.jpg" alt=""></div>    
    </div><!-- end section -->
    
    <div class="one_half last">
    
        <div class="stcode_title5">
            <h3 class="nmb"><strong>Welcome to Aadinath</strong></h3>
        </div>
        
        <h5 class="gray">Contrary to popular belief, Lorem Ipsum is not simply random text.</h5>
        
        <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <p class="text-justify">The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham</p>        
        <div class="clearfix marb12"></div>
    </div><!-- end section -->     
</div>
<!-- End About Intro -->
<div class="clearfix margin_top6"></div>
<!---Vision & Mission--->
<div class="featured_section56">
    <div class="left">    	
        <div class="cont">        
			<h5 class="title29">Our Vision & Mission <div class="line"></div></h5>
        	<h2><strong>Our Vision</strong></h2>
        	<p>Lorem Ipsum passages more recently with desktop publishing software are versions desktop therefore always. Many desktop publishi packages and web page editors in use the Ipsum as their default model as and search many web sites believable.</p>
            <h2><strong>Our Mission</strong></h2>
        	<p>Lorem Ipsum passages more recently with desktop publishing software are versions desktop therefore always.</p>
        </div>
        
    </div><!-- end left section -->
    
    <div class="right">    	
        <div class="cont">        
			<h5 class="title29">What we do <div class="line"></div></h5>            
            <i class="fa fa-home"></i>BUY &nbsp;&nbsp;&nbsp;&nbsp<i class="fa fa-rupee"></i>SELL &nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-building"></i>NEW PROJECTS
            <br /><br />
            
        	<h2><strong>Lorem Ipsum passages.</strong></h2>
        	<p>Lorem Ipsum passages more recently with desktop publishing software are versions desktop therefore always. Many desktop publishi packages and web page editors in use the Ipsum as their default model as and search many web sites believable.</p>
        </div>
        
    </div><!-- end left section -->


</div>
<!---End of Vision & Mission--->
<div class="clearfix"></div>
<!---Team--->
<div class="featured_section91">
<div class="container">

	<h2 class="title27 text-center">Meet Our Team <div class="line"></div></h2>
    	<div class="clearfix margin_top1"></div>    
    <div class="one_fourth">    
		<img src="<?php echo $baseUrl?>/public/images/team/team1.jpg" alt="" />
    	<span><strong>Arvind Jha</strong> CEO</span>
	</div><!-- end section -->
    
    <div class="one_fourth">    
		<img src="<?php echo $baseUrl?>/public/images/team/team1.jpg" alt="" />
    	<span><strong>Arvind Jha</strong> CEO</span>
	</div><!-- end section -->
    
    <div class="one_fourth">    
		<img src="<?php echo $baseUrl?>/public/images/team/team1.jpg" alt="" />
    	<span><strong>Arvind Jha</strong> CEO</span>
	</div><!-- end section -->
    
    <div class="one_fourth last">    
		<img src="<?php echo $baseUrl?>/public/images/team/team1.jpg" alt="" />
    	<span><strong>Arvind Jha</strong> CEO</span>
        
	</div><!-- end section -->
    
</div>
</div>
<!-- End Team -->

<div class="clearfix margin_top12"></div>

<div class="featured_section46">
<div class="container">
	
    <h2 class="title27">People Says <div class="line"></div></h2>
    
    <div class="clearfix margin_top1"></div>
    
    <div class="one_half">
    	<div class="bubble">
        
        	<img src="<?php echo $baseUrl?>/public/images/testimonial/people-img-1.jpg" alt="" />
        	
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
        
        	<div class="clearfix"></div>
		</div>
        
        <strong>Arvind Jha
		<em>client a</em></strong>
        
	</div><!-- end section -->
    
    <div class="one_half last">
    	<div class="bubble">
        
        	<img src="<?php echo $baseUrl?>/public/images/testimonial/people-img-1.jpg" alt="" />
        	
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        
        	<div class="clearfix"></div>
		</div>
        
        <strong>Arvind Jha
		<em>client b</em></strong>
        
	</div><!-- end section -->
    

</div>
</div><!-- end featured section 46 -->
</div><!-- end content area -->
    
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
    $(document).ready(function(){
        $('#pageTitle').text('Aadinath | About Us');
    });
    </script>


<!---End of Builder--->



  
  