 <?php $baseUrl = $this->basePath(); ?>

<!---------Filteration bar----------->
<div class="filteration">
<div class="container">
  <div class="container-fluid bg-white">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><div style="color:#777; padding-top:15px; margin-right:30px;">Refine Results :</div></li>               
        <li class="dropdown">
            <a  class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" ><span id="possessionText" >Possession</span><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a ><input type="checkbox" onchange="managePossession('readyToMoveIn')" id="readyToMoveIn" value="readyToMoveIn"><span id="text_readyToMoveIn" > Ready to move in</span></a></li>
            <li><a ><input type="checkbox" onchange="managePossession('upto3month')" id="upto3month" value="upto3month"><span id="text_upto3month" > Upto 3 Months</span></a></li>
            <li><a ><input type="checkbox" onchange="managePossession('upto6month')" id="upto6month" value="upto6month"><span id="text_upto6month" > Upto 6 Months</span></a></li>
            <li><a ><input type="checkbox" onchange="managePossession('upto9month')" id="upto9month" value="upto9month"><span id="text_upto9month" > Upto 9 Months</span></a></li>            
          </ul>
        </li>
<!--    <li class="dropdown">
          <a class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" id="propertyTypeFilter">Property Type <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <?php
              foreach($this->propertyTypeArr as $propertyType){?>
                  <li><a ><input type="checkbox"  onchange="managePropertyType(<?php echo $propertyType['id'];?>)" id="propertyType_<?php echo $propertyType['id'];?>" value="<?php echo $propertyType['id'];?>"> <?php echo $propertyType['property_type'];?></a></li>
             <?php  }?>         
          </ul>
        </li>-->
        <li class="dropdown">
          <a class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" id="budgetFilter">Budget <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <li><a ><input type="checkbox" onchange="manageBudget(2500000)" id="budget_2500000" value="2500000">&nbsp;&nbsp;<span class="rupee">`</span> 25 L</a></li> 
              <li><a ><input type="checkbox" onchange="manageBudget(5000000)" id="budget_5000000" value="5000000">&nbsp;&nbsp;<span class="rupee">`</span> 50 L</a></li> 
              <li><a ><input type="checkbox" onchange="manageBudget(7500000)" id="budget_7500000" value="7500000">&nbsp;&nbsp;<span class="rupee">`</span> 75 L</a></li> 
              <li><a ><input type="checkbox" onchange="manageBudget(10000000)" id="budget_10000000" value="10000000">&nbsp;&nbsp;<span class="rupee">`</span> 1.00 Cr</a></li> 
              <li><a ><input type="checkbox" onchange="manageBudget(15000000)" id="budget_15000000" value="15000000">&nbsp;&nbsp;<span class="rupee">`</span> 1.50 Cr</a></li> 
              <li><a ><input type="checkbox" onchange="manageBudget(20000000)" id="budget_20000000" value="20000000">&nbsp;&nbsp;<span class="rupee">`</span> 2.00 Cr</a></li> 
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" id="bedroomFilter">Bedrooms <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a ><input type="checkbox" onchange="manageBedrooms(1)" id="bedroom_1" value="1"> 1 Bedroom</a></li>
            <li><a ><input type="checkbox" onchange="manageBedrooms(2)" id="bedroom_2" value="2"> 2 Bedrooms</a></li>
            <li><a ><input type="checkbox" onchange="manageBedrooms(3)" id="bedroom_3" value="3"> 3 Bedrooms</a></li>
            <li><a ><input type="checkbox" onchange="manageBedrooms(4)" id="bedroom_4" value="4"> 4 Bedrooms</a></li>
            <li><a ><input type="checkbox" onchange="manageBedrooms(5)" id="bedroom_5" value="4+"> 4+ Bedrooms</a></li>           
          </ul>
        </li>
        <li><a ><span class="glyphicon glyphicon-refresh"></span> <span style="cursor:pointer" id="resetFilter">Reset</span> </a></li> 
      </ul>
     <!--right---> 
      <ul class="nav navbar-nav navbar-right"> 
        <li><a onclick="changeView('list')" class="cursor"><span class="glyphicon glyphicon-th-list"></span> LIST</a></li>       
        <li><a onclick="changeView('grid')" class="cursor"><span class="glyphicon glyphicon-th-large"></span> GRID</a></li>
             
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</div>
</div>

 
  <div class="clearfix margin_top12"></div>
  
  <!---------Heading----------->
  <input type="hidden" id="baseUrl" value="<?php echo $baseUrl;?>">
  <input type="hidden" id="pageName" value="builder-detail">
  <input type="hidden" id="builderDetailId" value="<?php echo $this->builderDetail[0]['id'];?>">
  <input type="hidden" id="PossessionFilters" value="<?php echo $this->possession;?>">
  <input type="hidden" id="PropertyTypeFilters" value="<?php echo $this->propertyType;?>">
  <input type="hidden" id="BudgetFilters" value="<?php echo $this->budget;?>">
  <input type="hidden" id="BedroomFilters" value="<?php echo $this->bedroom;?>">
  
   
  <div class="container">
		<div class="one_full">    
    	<div class="page-header">
  <div class="clearfix"></div>  
  <h3>About <?php echo $this->builderDetail[0]['builder_name'];?></h3></div>
        <div class="three_fourth" style="min-height: 320px">
        <p style="text-align:justify; padding-top:30px;"><?php echo $this->builderDetail[0]['about_builder'];?>
    </p>
    	</div>
        <div class="one_fourth last">
        <div class="one_one margin_top3">   
        <div class="flips4">        
            <div class="flipscont4">
            	<img height="80" width="100" style="padding-top:15px;" src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->builderDetail[0]['builder_image']?>" alt="" >                
            </div>            
                      
        </div>
        <div class="last stcode_title5 margin_top5">       
        <ul>
        <li>EXPERIENCE - <?php echo $this->builderDetail[0]['builder_experience']?> Years</li><br>
        <li>TOTAL PROJECTS - <?php echo $this->totalProject?></li><br>
        <li>ONGOING PROJECTS - <?php echo $this->ongoingProject?></li><br>         
        </ul>        
    </div>    
    </div>
  
        </div>
    </div>
  </div>
  
  <!---------Heading----------->
   <div class="clearfix"></div>
   <div class="divider_line1"></div>
  <div class="insidepg-heading">
  <div class="container">
  <div class="page-header">
  <div class="clearfix"></div>  
  <h3><?php echo $this->builderDetail[0]['builder_name'];?> Projects<br> <small>Found a total of <?php echo count($this->searchResultArr)?> projects.</small></h3></div>
  </div>  
  </div>
 
  <!---------All Project-----------> 

  <div id='searchProjects'>
     <?php if($this->viewType == 'list'){ 
        if(count($this->searchResultArr)){
            $ii = 0;
            foreach($this->searchResultArr as $searchResult){
    ?>            
            <div class="container insidepg-proj-row"> 
              <div class="row">
              <div class="col-md-3  insidepg-proj-img-box"><a href="projects-detail.html"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['project_image']?>" class="img-responsive"></a></div>
              <div class="col-md-7 insidepg-proj-detail">
              <div class="bs-example" data-example-id="bordered-table">
               <h4 id="tables-bordered"><a href="projects-detail.html"><?php echo $searchResult['project_title']?></a></h4>
              <p><?php echo $searchResult['address']?></p>
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>PROPERTY</th>
                      <th>SIZE</th>
                      <th>BUILDER PRICE</th>
                    </tr>
                  </thead>
                  <tbody>
                      <?php $floorSizeArr = array();
                      foreach($searchResult['floor_plans'] as $floor_plan){?>
                          <tr>
                          <td><?php echo $floor_plan['plan_type'];?></th>
                          <td><?php echo $floor_plan['size'].' '.$floor_plan['unit'];?></td>
                          <td><span class="rupee">`</span> <?php echo $floor_plan['price'];?></td>
                        </tr> 
                     <?php $floorSizeArr[]= $floor_plan['price'];
                      }?>

                  </tbody>
                </table>
              </div>
              </div>


              <div class="col-md-2 insidepg-proj-builder">
              <div class="row insidepg-proj-builder-img" align="center"><a href="#"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['builder_image']?>"  class="img-responsive"></a></div>
            <div class="row insidepg-proj-builder text-center"><?php if(count($floorSizeArr)){ ?><div class="proj-price-text"><span class="rupee">`</span>  <?php echo $searchResult['min_floor_plan_price'];?> - <span class="rupee">`</span> <?php echo $searchResult['max_floor_plan_price'];?></div><?php } ?>
                  POSSESSION <?php echo date('M', strtotime($searchResult['possession']))?> `<?php echo date('d', strtotime($searchResult['possession']))?></div>
              <div class="row text-center"><button type="button" class="btn btn-danger" onclick="return getCallBAck('<?php echo $searchResult['project_id']?>','<?php echo $searchResult['project_title']?>')">GET CALL BACK</button></div>
              </div>
              </div>
              </div>  
<?php
        $ii++; 
        if($ii % 4 == 0 && $ii != count($this->searchResultArr)){
            $container = new Zend\Session\Container('searchSessionFields');
            $bannerArr = $container->projectBanner;
            shuffle($bannerArr);
            ?>
    <!---Add-Banner--->  
     <div class="container insidepg-proj-row">
     <div class="clearfix margin_top2"></div> 
         <div class="row"><a style="float:left" href="<?php echo $baseUrl;?>/index/project-detail?id=<?php echo $bannerArr[0]['project_id']?>"><img width="1160" height="100" src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $bannerArr[0]['banner_image']?>"></a></div>
     <div class="clearfix margin_top3"></div> 
     </div>
    <?php }   
            }
        }
      }else{ ?>
          
        <div class="content_fullwidth">
        <div class="featured_section102">
        <div class="container insidepg-proj-grid-row">
            <?php 
        $count = 0;
        foreach($this->searchResultArr as $searchResult){
        $count++;
    ?>
        <div class="one_fourth_less <?php if($count % 4 == 0){ echo 'last';}?> "  >    
            <a href="projects-detail.html"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['project_image']?>" alt="" /></a>
            <h5><a href="projects-detail.html"><?php echo $searchResult['project_title']?></a> <em><?php echo $searchResult['address']?></em></h5>
             <?php  $floorSizeArr = array();$floorPriceArr = array();
             if(count($searchResult['floor_plans'])){
                    foreach($searchResult['floor_plans'] as $floor_plan){
                        $floorPriceArr[]= $floor_plan['price'];
                        $floorSizeArr[]= $floor_plan['size'];
             }}?>
            <div class="grid_type">
            4, 2 & 3 BHK ( <?php if(count($floorSizeArr)) echo max($floorSizeArr)?> - <?php if(count($floorSizeArr)) echo min($floorSizeArr)?> sq ft )<br>
            <span class="grid_type_left_smltxt">Possession Date: <?php echo date('M', strtotime($searchResult['possession']))?> `<?php echo date('d', strtotime($searchResult['possession']))?></span>
            </div>
            <div class="grid_button">
            <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> <?php if(count($floorPriceArr)) echo min($floorPriceArr)?></div>
            <div class="grid_button_right">
            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
            </div>
        </div>
        
    <?php  
    
     if($count % 4 == 0 && $count != count($this->searchResultArr)){ ?>
         <div style="border-bottom: 4px double #ccc;">&nbsp;</div>
    <?php }
        if($count % 8 == 0){
            $container = new Zend\Session\Container('searchSessionFields');
            $bannerArr = $container->projectBanner;
            shuffle($bannerArr);
        ?>
        <div class="container insidepg-proj-row">
        <div class="clearfix margin_top3"></div> 
        <div class="row"><a style="float:left" href="<?php echo $baseUrl;?>/index/project-detail?id=<?php echo $bannerArr[0]['project_id']?>"><img width="1160" height="100" src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $bannerArr[0]['banner_image']?>"></a></div>
        <div class="clearfix margin_top3"></div> 
        </div>
    <?php }
        }
    ?>   
        </div>
        </div>
        </div>        
 <?php } ?>
   
     
  
</div>


 
 
  
  
  
 
 


 
 
 
 
  
  
<script src="<?php echo $baseUrl;?>/public/projectScripts/index/project_list_grid.js" type="text/javascript"></script>
<script src="<?php echo $baseUrl;?>/public/js/jquery.mousewheel.js" type="text/javascript"></script>
<script>
$(document).ready(function(){
    return updateValues();
    
});
<!-- Below code is used to get mouse up-down event-->

$(document).mousewheel(function(event, delta) {
//    if (delta > 0)
//      alert(' up');
//    else if (delta < 0)
//      alert(' down');
    
 });


</script>
 
 



  
  