 <?php $baseUrl = $this->basePath(); ?>

		 <div class="clearfix"></div>
  <!-- Slider
======================================================================================= -->
  <!-- masterslider --->
   <div class="buy-bg-img16">
   <div class="container">
   <div class="buy-form-bg">
   <div class="buy-form-inside">
   
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><div style="color:#777; padding-top:18px; margin-right:30px; margin-left:30px;">FIND YOUR PROPERTY :</div></li>  
        <li class="dropdown buy-box-last">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Select City <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">All Cities</a></li>
            <li><a href="#">Noida</a></li>
            <li><a href="#">Greater Noida</a></li>
            <li><a href="#">Delhi</a></li>            
          </ul>
        </li>        
        <li class="dropdown buy-box-last">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Select Type <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Residential Properties</a></li>
            <li><a href="#">Commercial Properties</a></li>
            <li><a href="#">Plots Properties</a></li>  
            <li><a href="#">Studio Apartments</a></li>           
          </ul>
        </li>
        <li class="dropdown buy-box-last">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Min <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">5 Lacs</a></li>
            <li><a href="#">10 Lacs</a></li>
            <li><a href="#">15 Lacs</a></li>           
          </ul>
        </li>
        <li class="dropdown buy-box-last">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Max <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">10 Lacs</a></li>
            <li><a href="#">15 Lacs</a></li>
            <li><a href="#">20 Lacs</a></li>          
          </ul>
        </li>
        <li class="buy-box-last" style="padding-top:14px; padding-left:20px;"><button type="button" class="btn btn-danger">Search</button></li> 
      </ul>
     <!--right---> 
      
    </div>
   </div>
   </div>
   </div>
   </div>
<!---Best New Launches In Delhi-NCR----->
<div class="works01">
<div class="container">
  <h2 class="title27 roboto">Best New Launches in Delhi-NCR
        <div class="line"></div>
      </h2>
    
    <div id="grid-container" class="cbp-l-grid-masonry-projects">
    
            <div class="cbp-item graphic">
                <div class="cbp-caption">
                    <div class="cbp-caption-defaultWrap newlaunch-proj2">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/1.jpg" alt=""></a>
                    </div>
				</div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">AFOWO Raksha Towers</a>
                <div class="cbp-l-grid-masonry-projects-desc">Sector-1, Noida Extension</div>
            </div>
            
            <div class="cbp-item web-design logos">
                <div class="cbp-caption">
                    <div class="cbp-caption-defaultWrap newlaunch-proj1">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/2.jpg" alt=""></a>
                    </div>
                </div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">Antriksh Urban Greek</a>
                <div class="cbp-l-grid-masonry-projects-desc">Zone L Dwarka, Delhi</div>
            </div>
            
            <div class="cbp-item graphic logos">
                <div class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/3.jpg" alt=""></a>
                    </div>
                </div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">Saviour Builder Myra</a>
                <div class="cbp-l-grid-masonry-projects-desc">Crossing Republik, Ghaziabad</div>
            </div>
            
            <div class="cbp-item identity web-design">
                <div class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/5.jpg" alt=""></a>
                    </div>
                </div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">Pyramid Finmart Royal Residency</a>
                <div class="cbp-l-grid-masonry-projects-desc">Sector-25, Yamuna Express Way</div>
            </div>
            
            <div class="cbp-item web-design graphic">
                <div class="cbp-caption">
					<div class="cbp-caption-defaultWrap">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/6.jpg" alt=""></a>
                    </div>
                </div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">Ashiana Homes Greens</a>
                <div class="cbp-l-grid-masonry-projects-desc">Ahinsa Khand 2, Indrapuram, Gzb</div>
            </div>
            
            <div class="cbp-item identity web-design">
                <div class="cbp-caption">
					<div class="cbp-caption-defaultWrap">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/4.jpg" alt=""></a>
                    </div>
                </div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">S S Buildcon Emerald</a>
                <div class="cbp-l-grid-masonry-projects-desc">Knowledge Park V, Noida</div>
            </div>            
        </div>


</div>
</div>


  
  