 <?php $baseUrl = $this->basePath(); ?>

		 <div class="clearfix"></div>
  <!-- Slider
======================================================================================= -->
  <!-- masterslider --->
   <div class="buy-bg-img16">
   <div class="container">
   <div class="buy-form-bg">
   <div class="buy-form-inside">
   
   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <form action="" method="post">
      <ul class="nav navbar-nav">
        <li><div style="color:#777; padding-top:18px; margin-right:5px; margin-left:0px;">FIND YOUR PROPERTY :</div></li>  
        <li class="buy-box-last" style="padding-top:14px; width:16%; margin-left:2%;">
          <select name="cities" id="cities" class="form-control">
            <option value="">All Cities</option>
            <?php foreach($this->cities as $city){?>
                <option value="<?php echo $city['id'] ?>"><?php echo $city['city_name'] ?></option>
            <?php } ?>
          </select>
          
        </li>   
        <li class="dropdown buy-box-last" style="padding-top:14px; width:16%; margin-left:2%;">
          <select name="propcategory" id="propcategory" class="form-control"> 
              <?php foreach($this->propertyCategory as $propertyCategory){?>
                <option value="<?php echo $propertyCategory['id'] ?>"><?php echo $propertyCategory['category_name'] ?></option>
            <?php } ?>
          </select>          
        </li>   
        
        <li class="dropdown buy-box-last" style="padding-top:14px; width:12%; margin-left:2%;">
          <select name="minprice" id="minprice" class="form-control">
            <option>0</option>
            <option value="2500000">25.0Lacs +</option>
            <option value="5000000">50.0Lacs +</option> 
            <option value="10000000">1.0Cr +</option> 
            <option value="15000000">1.5Cr +</option> 
            <option value="2000000">2.0Cr +</option> 
            <option value="3000000">3.0Cr +</option> 
          </select>
          
        </li>   
        
       
        <li class="dropdown buy-box-last" style="padding-top:14px; width:12%; margin-left:2%;">
          <select name="maxprice" id="maxprice" class="form-control">
            <option value="35000000">3.5Cr +</option>
            <option value="40000000">4.0Cr +</option> 
            <option value="45000000">4.5Cr +</option> 
            <option value="50000000">5.0Cr +</option> 
            <option value="60000000">6.0Cr +</option> 
            <option value="70000000">7.0Cr +</option> 
        </select>
          
        </li>   
        <li class="buy-box-last" style="padding-top:14px; padding-left:5px; margin-left:2%;"><input type="submit" class="btn btn-danger" value="Search"/></li> 
      </ul>
     <!--right---> 
      </form>
    </div>
   </div>
   </div>
   </div>
   </div>
<!---Best New Launches In Delhi-NCR----->
<div class="works01">
<div class="container">
  <h2 class="title27 roboto">Best New Launches in Delhi-NCR
        <div class="line"></div>
      </h2>
    
    <div id="grid-container" class="cbp-l-grid-masonry-projects">
    
            <div class="cbp-item graphic">
                <div class="cbp-caption">
                    <div class="cbp-caption-defaultWrap newlaunch-proj2">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/1.jpg" alt=""></a>
                    </div>
				</div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">AFOWO Raksha Towers</a>
                <div class="cbp-l-grid-masonry-projects-desc">Sector-1, Noida Extension</div>
            </div>
            
            <div class="cbp-item web-design logos">
                <div class="cbp-caption">
                    <div class="cbp-caption-defaultWrap newlaunch-proj1">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/2.jpg" alt=""></a>
                    </div>
                </div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">Antriksh Urban Greek</a>
                <div class="cbp-l-grid-masonry-projects-desc">Zone L Dwarka, Delhi</div>
            </div>
            
            <div class="cbp-item graphic logos">
                <div class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/3.jpg" alt=""></a>
                    </div>
                </div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">Saviour Builder Myra</a>
                <div class="cbp-l-grid-masonry-projects-desc">Crossing Republik, Ghaziabad</div>
            </div>
            
            <div class="cbp-item identity web-design">
                <div class="cbp-caption">
                    <div class="cbp-caption-defaultWrap">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/5.jpg" alt=""></a>
                    </div>
                </div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">Pyramid Finmart Royal Residency</a>
                <div class="cbp-l-grid-masonry-projects-desc">Sector-25, Yamuna Express Way</div>
            </div>
            
            <div class="cbp-item web-design graphic">
                <div class="cbp-caption">
					<div class="cbp-caption-defaultWrap">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/6.jpg" alt=""></a>
                    </div>
                </div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">Ashiana Homes Greens</a>
                <div class="cbp-l-grid-masonry-projects-desc">Ahinsa Khand 2, Indrapuram, Gzb</div>
            </div>
            
            <div class="cbp-item identity web-design">
                <div class="cbp-caption">
					<div class="cbp-caption-defaultWrap">
                        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/new-launches-projects/4.jpg" alt=""></a>
                    </div>
                </div>
                <a href="#" class="cbp-l-grid-masonry-projects-title">S S Buildcon Emerald</a>
                <div class="cbp-l-grid-masonry-projects-desc">Knowledge Park V, Noida</div>
            </div>            
        </div>


</div>
</div>


<script>
function submitSearchForm(){
   
   var cities       = $('#cities').val();
   var propcategory = $('#propcategory').val();
   var minprice     = $('#minprice').val();
   var maxprice     = $('#maxprice').val();
   
   
    <?php
        $container = new \Zend\Session\Container('searchSessionFields');
        $container->cities          = '<script>cities</script>';
        $container->propcategory    = '<script>propcategory</script>';
        $container->minprice        = '<script>minprice</script>';
        $container->maxprice        = '<script>maxprice</script>';
    ?>
            
    
}

</script>
  