<?php $baseUrl = $this->basePath(); ?>

<div class="slidermar9">
    
  <div class="page_title1 sty7-i">
<div class="container">
	
    <h1 style="text-shadow: 2px 2px #fff; color:#000;">CAREERS <em></em></h1>
     
</div>
</div><!-- end page title --> 


<div class="clearfix margin_top10"></div>


<div class="container">
<div class="one_full stcode_title7">    
<h2> WHY YOU SHOULD    <strong> JOIN US</strong>
</h2>
<p style="text-align:justify; padding-top:30px;">
At Aadinath, we recruit skilled individuals who are perfectionists and passionate about their work. We nurture their talent, polish their skills with challenging work opportunities, and help them harness their potential to the fullest. Besides individual professional growth, the amicable work environment inculcates the spirit of teamwork, and thus, ensures organizational growth as well.<br><br>
   So, if you have the talent, we have the right opportunity for you. Join Aadinath today. <br><br>
   If you are interested to work with Aadinath please submit your CV with a covering letter to our HR Manager at info@aadinath.com<br>  
    </p>
</div>
</div><!-- end content area -->
  
  <div class="clearfix margin_top6"></div>
  <div class="container">
  <div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text"><strong>APPLY TO JOIN US</strong></span></h3></div>
<div class="one_half">    
        <div class="cforms">       
        <div id="form_status"></div>
    	<form type="" id="" onSubmit="">
	        <label class="label">Name <em>*</em></label>
	        <label class="input">
	            <input type="text" name="name" id="name">
	        </label>
	        
	        <div class="clearfix"></div>
	        
	        <label class="label">E-mail <em>*</em></label>
	        <label class="input">
	            <input type="email" name="email" id="email">
	        </label>
	
	        	
	        <div class="clearfix"></div>
	
	        
	        <label class="label">Phone <em>*</em></label>
	        <label class="input">
	            <input type="text" name="phone" id="phone">
	        </label>	
	        <div class="clearfix"></div> 
            <label class="label">Resume <em>*</em></label>
            <label class="input">
            <input type="file" style="width:200px;background:none; border:none; box-shadow:none; -webkit-box-shadow: none; padding:0;">
            </label>
            <div class="clearfix"></div><br>
             <button type="button" class="btn btn-danger">Send Message</button>
	        
    	</form>	
        
        
        
        
        
        </div>
        
      </div>


  <div class="one_half last"></div>
  </div>
    
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
    $(document).ready(function(){
        $('#pageTitle').text('Aadinath | Careers');
        $('.homeMenu,.AboutUsMenu,.ContactUsMenu').removeClass('active');
        $('.CareersMenu').addClass('active')
    });
    </script>


<!---End of Builder--->



  
  