<?php $baseUrl = $this->basePath(); ?>
<div class="slidermar9">
    
  <div class="page_title1 sty7">
<div class="container">
	
    <h1 style="text-shadow: 2px 2px #000;">Contact Us <em></em></h1>
     
</div>
</div><!-- end page title --> 


<div class="clearfix"></div>


<div class="content_fullwidth less2">
<div class="container">
	
    <div class="one_half">
      
        <p>Get in touch with us for your property requirement, query, complaint or feedback on our dedicated customer service helpdesk number & email ID</p>
        <br />
        <p><strong>Phone General Inquiries: 0120-4256308</strong><br>
        <strong>Email : crm@aadinathindia.com</strong></p>
        <br /><br />
        
        <div class="cforms">
        
        
        <div id="form_status"></div>
    	<form type="" id="" onSubmit="">
	        <label class="label">Name <em>*</em></label>
	        <label class="input">
	            <input type="text" name="name" id="name">
	        </label>
	        
	        <div class="clearfix"></div>
	        
	        <label class="label">E-mail <em>*</em></label>
	        <label class="input">
	            <input type="email" name="email" id="email">
	        </label>
	
	        	
	        <div class="clearfix"></div>
	
	        
	        <label class="label">Phone <em>*</em></label>
	        <label class="input">
	            <input type="text" name="phone" id="phone">
	        </label>
	
	        <div class="clearfix"></div>
	
	        <label class="label">Message <em>*</em></label>
	        <label class="textarea">
	            <textarea rows="5" name="message" id="message"></textarea>
	        </label>
	
	        <div class="clearfix"></div>
		
            <button type="button" class="btn btn-danger">Send Message</button>
	        
    	</form>	
        
        
        
        
        
        </div>
        
      </div>
      
      <div class="one_half last">
      
        <div class="address_info">
        
          <h4>Corporate Office <strong>Address:</strong></h4>
          <ul>           
              A-10, Sector-63, Noida - 201301 (Uttar Pradesh) India.<br />
              Telephone: +0120-4256308<br />
              Mobile No: +91-9650797111<br />
              E-mail: crm@aadinathindia.com<br />
              Website: <a href="index.html">www.aadinathindia.com</a>
          </ul>
        </div>
        <div class="clearfix"></div>
        <h4>Find the <strong>Address</strong></h4>
       <iframe src="https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d56041.07503799712!2d77.35013806930765!3d28.61275827920193!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x390cef8c1466f1e5%3A0xb916ca1aa19340b5!2sSector+65%2C+Noida%2C+Uttar+Pradesh+201307!3m2!1d28.612763299999997!2d77.3871319!5e0!3m2!1sen!2sin!4v1433583634109" width="540" height="340" frameborder="" style="border: 2px solid #e1e1e1;"></iframe>
        <br />
        <small><a href="https://www.google.co.in/maps/dir//Sector+65,+Noida,+Uttar+Pradesh+201307/@28.6127583,77.3501381,13z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x390cef8c1466f1e5:0xb916ca1aa19340b5!2m2!1d77.3871319!2d28.6127633?hl=en" target="_blank">View Larger Map</a></small> </div>

</div>
</div><!-- end content area -->
    
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
    $(document).ready(function(){
        $('#pageTitle').text('Aadinath | Contact Us');
        $('.homeMenu,.AboutUsMenu,.CareersMenu').removeClass('active');
        $('.ContactUsMenu').addClass('active')
    });
    </script>


<!---End of Builder--->



  
  