<?php $baseUrl = $this->basePath(); ?>

<div class="container">
	<div class="margin_top12"></div>
	<div class="page-header">
  <div class="clearfix"></div>  
  <h3>Property Buying Steps</h3></div>
	
   
<div class="container margin_top2">
<div class="content_left">    	
        
        <p style="text-align:justify;"><br>Our endeavor is to simplify the most important decision of your life - buying a home. We combine the power of the internet to provide comprehensive information along with the services of a property advisor who offers genuine and unbiased advice and helps conclude the transaction successfully.</p>        
        
        
        <div class="clearfix margin_top3"></div>
        
       <h4>1. Check out our website</h4> 
        <p class="margin_top1" style="text-align:justify;">           
           Visit aadinathindia.com to see and compare the best suited property from a vast database of properties from best builders. We provide comprehensive information on location, builder, unique selling points of the project, layout plan, floor plans, pricing, specifications and amenities on all properties.
        </p>
                
        
          <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">2. Select the property that meets your criteria</h4>
        <p style="text-align:justify;">Property selection is based on the following:
        <div class="margin_top1"></div>
        - Evaluating various choices available on the basis of your requirement<br>
        - Meeting our advisors who will help you shortlist the properties that suit your needs.. We will advise you on the location, price<br> &nbsp; and future prospects of the property, home loans, etc. All properties are verified and available in 100% cheque<br>
        - We arrange a site visit to all the shortlisted properties</p>
        
        
        
         <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">3. Closing the deal</h4>
        <p style="text-align:justify;">Once you have decided on the property of your choice, we help you:
        <div class="margin_top1"></div>
        - Close the deal by handling all the paperwork<br>
        - Guiding you through the application forms, allotment and arranging home loan from a reputed bank, if required<br>
        - Ensure a convenient and hassle free transaction<br>
        - Our services to you continue till the registry of the flat. This includes payment reminders, collection of cheques and handling all<br> &nbsp; documentation with the builder and the bank.</p>
        
        
</div><!-- end content left side -->


<!-- right sidebar starts -->
<div class="right_sidebar">
	<div class="sidebar_widget">    
    	<div class="sidebar_title">
        <div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text">Quick Links</span></h3></div>
        </div>        
		<ul class="arrows_list1">          
            <li><a href="<?php echo $baseUrl?>/faq"><i class="fa fa-angle-right"></i> Property Buying Steps</a></li>
            <li><a href="<?php echo $baseUrl?>/home-loan"><i class="fa fa-angle-right"></i> Home Loan</a></li>
            <li><a href="<?php echo $baseUrl?>/vaastu-tips"><i class="fa fa-angle-right"></i> Vaastu Tips</a></li>
            <li><a href="<?php echo $baseUrl?>/emi-calculator"><i class="fa fa-angle-right"></i> EMI Calculator</a></li>
            <li><a href="<?php echo $baseUrl?>/nri-services"><i class="fa fa-angle-right"></i> NRI services</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Real Estate News</a></li>           
		</ul>
        
         <div class="margin_top8"></div>    
    	<ul class="arrows_list1">        
            <li><a href="#"><img src="<?php echo $baseUrl?>/public/images/latest-Project/lp3.jpg"></a></li>
            
            
            
		</ul>	
       
	</div><!-- end section -->
    
    
    
</div><!-- end right sidebar -->

</div>
    
    <!-- end section -->
    
</div>
    
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
    $(document).ready(function(){
        $('#pageTitle').text('Aadinath | Property Buying Steps');
    });
    </script>


<!---End of Builder--->



  
  