<?php $baseUrl = $this->basePath(); ?>

<div class="container">
	<div class="margin_top12"></div>
	<div class="page-header">
  <div class="clearfix"></div>  
  <h3>Home Loan</h3></div>
	
   
<div class="container margin_top2">
<div class="content_left">    	
        
        <p style="text-align:justify;"><br>A Home loan is a loan taken for buying or constructing a home or to make improvements to a residential property. You can get a loan from from banks and registered housing finance companies.</p>
        
        <p style="text-align:justify;">Your Home loan is secured against the property that you buy. This means that in case you are unable to repay the loan, the lending bank will have the right to take possession of your home.</p>
        
        <div class="clearfix margin_top3"></div>
        
       <h4>Types of Home Loans available</h4> 
        <p class="margin_top1">        
            <strong>Home Purchase Loan</strong><br>
            A common type of loan taken for purchasing a home.<br><br>
         
            <strong>Home Improvement Loan</strong><br>
            A loan given for implementing repair works and renovations at home.<br><br>
            
            <strong>Home Construction Loan</strong><br>
            A loan available for the construction of a new home.<br><br>
           
            <strong>Home Extension Loan</strong><br>
            Home extension loans are given for expanding or extending an existing home. For example, addition of an extra room, etc.<br><br>
            
            <strong>Land Purchase Loan</strong><br>
            This type of loan is sanctioned for purchase of a land, for both home construction or investment purposes.<br><br>
            
            <strong>Balance Transfer Loan</strong><br>
            This loans help you pay off an existing home loan with a higher interest rate, and avail of a loan with a lower rate of interest.<br><br>
             
            <strong>Refinance Loan</strong><br>
            This loan helps you pay off the debt you may have incurred from private sources such as relatives and friends in order to purchase your present home.<br><br>
            
            <strong>Loans for NRIs</strong><br>
            This loan is tailored to suit the requirements of NRIs who wish to build or buy a home in India.

        </p>
        
        <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">EMI</h4> 
        <p style="text-align:justify;">EMI (Equated Monthly Installment) is the amount payable to the lending institution every month, till the loan is paid back in full. It consists of a portion of the interest as well as the principal.</p>
        
          <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Eligibility Conditions for a Home Loan</h4>
        <p style="text-align:justify;">
        <div class="margin_top1"></div>
        - An Indian resident or NRI<br>
        - Above 24 years of age at the commencement of the loan<br>
        - Below 60 or retirement age when the loan matures<br>
        - Either self employed or salaried</p>
        
        
        
          <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Interest rates offered for Home Loans / Daily Reducing, Monthly Reducing and Yearly Reducing</h4>
         <p style="text-align:justify;">Interest rates are different from institution to institution and generally range from about 8.75% to around 12 %. The interest on home loans in India is usually calculated either on monthly reducing or yearly reducing balance. In some cases, daily reducing basis is also adopted.</p>
        <div class="margin_top1"></div>
       <p class="margin_top1" style="text-align:justify;">        
            <strong>Annual reducing:</strong><br>
           In this system, the principal, for which you pay interest, reduces at the end of the year. Thus you continue to pay interest on a certain portion of the principal which you have actually paid back to the lender. This means the EMI for the monthly reducing system is effectively less than the annual reducing system.<br><br>
            <strong>Monthly reducing:</strong><br>
          In this system, the principal, for which you pay interest, reduces every month as you pay your EMI.<br><br>
            <strong>Daily Reducing:</strong><br>
           In this system, the principal, for which you pay interest, reduces from the day you pay your EMI. EMI in the daily reducing system is less than the monthly reducing system.<br>
        </p>
        
        
        <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Fixed Rate of Interest</h4> 
        <p style="text-align:justify;">Some institutions have a fixed rate of interest, which means the rate of interest remains unchanged for the entire duration of the loan. This means you do not benefit, even if rates of interest drop in the market.</p>
        
        
        <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Floating Rate</h4> 
        <p style="text-align:justify;">This is the rate of interest that fluctuates according to the market lending rate. This means you stand the risk of paying more than you budgeted for in case the lending rate goes up</p>
        
        
        <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Other costs that usually accompany a Home Loan</h4>
        
       
       <p style="text-align:justify;">        
            <strong>Processing Charge:</strong><br>
           A fee payable to the lender on applying for a loan. It is either a fixed amount not linked to the loan or may also be a percentage of the loan amount. The loan amount required cannot be less than the processing fee.<br><br>
            <strong>Pre-payment Penalties:</strong><br>
          When a loan is paid back before the end of the agreed duration, a penalty is charged by some banks/companies, which is usually 2% of the amount being paid.<br><br>
            <strong>Miscellaneous Costs:</strong><br>
           Some lenders may levy documentation or consultant charges.<br>
        </p>
        
        <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">HFCs decide on the Loan amount</h4> 
        <p style="text-align:justify;">Usually, most companies give up to a maximum of 85% of the cost of the house. The 15%, sometimes called 'seed money', will have to be provided by the loan applicant. The amount, for which the applicant is eligible, is determined by the age, income, no. of dependents, monthly outgoing and repayment capacity. This varies from case to case.</p>
        
         <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Securities required for Home Loans</h4> 
        <p style="text-align:justify;">In most cases, the property to be purchased itself becomes the security and is mortgaged to the lending institution till the entire loan is repaid. Some institutions may ask for additional security such as life insurance policies, FD receipts and share or savings certificates.</p>
        
        <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Time required for Loan disbursement</h4> 
        <p style="text-align:justify;">On an average, loans are disbursed within 3-15 days after satisfactory and complete documentation and completion of all relevant procedures, including proof that 15% of the cost has been paid upfront to the seller of the property.</p>
        
        <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Tax Benefits of Home Loans</h4> 
        <p style="text-align:justify;"> Both principal as well as interest of home loans attract tax benefits. With effect from 1st April 2005 (i.e. assessment year 2005-07) under section 80C of the Income Tax Act 1965: Principal amount of repayment of loan along with other savings such as PF, PPF, Life Insurance premium etc up to a maximum of Rs 1, 00,000/- will be eligible for deduction from gross income. Interest paid up to a maximum of Rs 1, 50,000/- will be eligible for deduction from gross income on loan after completion of construction will be deductible from income from property.
        </p>
</div><!-- end content left side -->


<!-- right sidebar starts -->
<div class="right_sidebar">
	<div class="sidebar_widget">    
    	<div class="sidebar_title">
        <div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text">Quick Links</span></h3></div>
        </div>        
		<ul class="arrows_list1">        
            <li><a href="<?php echo $baseUrl?>/faq"><i class="fa fa-angle-right"></i> Property Buying Steps</a></li>
            <li><a href="<?php echo $baseUrl?>/home-loan"><i class="fa fa-angle-right"></i> Home Loan</a></li>
            <li><a href="<?php echo $baseUrl?>/vaastu-tips"><i class="fa fa-angle-right"></i> Vaastu Tips</a></li>
            <li><a href="<?php echo $baseUrl?>/emi-calculator"><i class="fa fa-angle-right"></i> EMI Calculator</a></li>
            <li><a href="<?php echo $baseUrl?>/nri-services"><i class="fa fa-angle-right"></i> NRI services</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Real Estate News</a></li> 
		</ul>
        <div class="margin_top8"></div>    
    	<ul class="arrows_list1">        
            <li><a href="#"><img src="<?php echo $baseUrl?>/public/images/latest-Project/lp3.jpg"></a></li>
            <li class="margin_top5"><a href="#"><img src="<?php echo $baseUrl?>/public/images/latest-Project/lp1.jpg"></a></li>
            <li class="margin_top5"><a href="#"><img src="<?php echo $baseUrl?>/public/images/latest-Project/lp2.jpg"></a></li>
            
		</ul>
        
       
	</div><!-- end section -->
	    	
</div><!-- end right sidebar -->

</div>
    
    <!-- end section -->
    
</div> 
    
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
    $(document).ready(function(){
        $('#pageTitle').text('Aadinath | Home Loan');
    });
    </script>


<!---End of Builder--->



  
  