 <?php $baseUrl = $this->basePath(); ?>

		 <div id="navbar-collapse-1" class="navbar-collapse collapse">
            <nav>
              <ul class="nav navbar-nav">
                <!--Home-->
                <li class="dropdown yamm-fw"> <a href="#" class="dropdown-toggle active">Home</a></li>
                <!--About us-->
                <li class="dropdown"><a href="#" class="dropdown-toggle">About us</a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Overview</a></li>
                    <li><a href="#">Core Values</a></li>
                    <li><a href="#">Leadership</a></li>
                    <li><a href="#">Mission & Vision</a></li>
                    <li><a href="#">Brand Story</a></li>
                    <li><a href="#">Testimonials</a></li>
                  </ul>
                </li>
                <!--Project-->
                <li class="dropdown yamm-fw"> <a href="projects.html" class="dropdown-toggle">Projects</a>
                  <ul class="dropdown-menu">
                    <li>
                      <!-- Content container to add padding -->
                      <div class="yamm-content">
                        <div class="row">
                          <ul class="col-sm-6 col-md-3 list-unstyled">
                            <li>
                              <p>Residential Projects</p>
                            </li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 1</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 2</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 3</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 4</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 5</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 6</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 7</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 8</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Residential 9</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> For More Projects <em>Click</em></a></li>
                          </ul>
                          <ul class="col-sm-6 col-md-3 list-unstyled">
                            <li>
                              <p>Commercial Projects</p>
                            </li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 1</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 2</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 3</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 4</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 5</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 6</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 7</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 8</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> Commercial 9</a></li>
                            <li><a href="#"><i class="fa fa-caret-right"></i> For More Projects <em>Click</em></a></li>
                          </ul>
                          <ul class="col-sm-6 col-md-3 last list-unstyled nav-project-img-ul-bordr">
                            <li>
                              <p>Hot Deals</p>
                            </li>
                            <li class="nav-project-img-bg"><a href="#"><img src="<?php echo $baseUrl;?>/public/images/latest-Project/lp1.jpg" class="nav-project-img-border"></a></li>
                            <li class="nav-project-img-bg"><a href="#"><img src="<?php echo $baseUrl;?>/public/images/latest-Project/lp2.jpg" class="nav-project-img-border"></a></li>
                          </ul>
                          <ul class="col-sm-6 col-md-3 last list-unstyled">
                            <li>
                              <p>&nbsp;</p>
                            </li>
                            <li class="nav-project-img-bg"><a href="#"><img src="<?php echo $baseUrl;?>/public/images/latest-Project/lp3.jpg" class="nav-project-img-border"></a></li>
                          </ul>
                        </div>
                      </div>
                    </li>
                  </ul>
                </li>
                
                <!--Builders-->
                <li class="dropdown"> <a href="all-builders.html" class="dropdown-toggle">Builders </a></li>
                <!--Media-->
                <li class="dropdown"><a href="#" class="dropdown-toggle">Media</a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Press Coverage</a></li>
                    <li><a href="#">Press Releases</a></li>
                    <li><a href="#">Events</a></li>
                  </ul>
                </li>
               
                
                <!--Careers-->
                <li class="dropdown"> <a href="careers.html" class="dropdown-toggle">Careers </a></li>
                <!--Contact us-->
                <li class="dropdown"><a href="contact-us.html" class="dropdown-toggle">Contact us</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <!-- end Navigation Menu -->
      <div class="menu_rlinks"> <a href="#" class="mrbut cart-tab" data-toggle="modal" data-target="#myModal">LOGIN</a> </div>
      <!-- end menu right links -->
    </div>
  </header>
  <div class="clearfix"></div>
  <!-- Slider
======================================================================================= -->
  <!-- masterslider --->
  <div class="slidermar9">
    <div class="master-slider ms-skin-default" id="masterslider">
      <div class="ms-slide slide-1" data-delay="9">       
       
       <img src="<?php echo $baseUrl;?>/public/images/sliders/master/15.jpg">      
        <h3 class="ms-layer text7 center"
        	style="top: 235px;"
            data-type="text"
            data-effect="top(45)"
            data-duration="2000"
            data-delay="500"
            data-ease="easeOutExpo"> We have the best offers </h3>
        <h4 class="ms-layer text8 caps"
        	style="top: 280px;"
            data-type="text"
            data-effect="top(45)"
            data-duration="2000"
            data-delay="1000"
            data-ease="easeOutExpo"
            data-effect="scale(1.5,1.6)">FIND YOUR DREAM HOME.</h4>
        <div class="ms-layer sbox1"
        	style="left: 115px; top: 370px;"
            data-delay="1600"
			data-ease="easeOutExpo"
			data-duration="1200"
			data-effect="scale(1.2,1.3)"> <a href="buy.html"><img src="<?php echo $baseUrl;?>/public/images/icon/buy-icon.png"><br>
          <strong>BUY</strong></a> </div>
        <!-- end box -->
        <div class="ms-layer sbox2"
        	style="left: 505px; top: 370px;"
            data-delay="1700"
			data-ease="easeOutExpo"
			data-duration="1200"
			data-effect="scale(1.2,1.3)"> <a href="sell.html"><img src="<?php echo $baseUrl;?>/public/images/icon/sell-icon.png"><br>
          <strong>SELL</strong></a> </div>
        <!-- end box -->
        <div class="ms-layer sbox3"
        	style="left: 895px; top: 370px;"
            data-delay="1800"
			data-ease="easeOutExpo"
			data-duration="1200"
			data-effect="scale(1.2,1.3)"> <a href="new-projects.html"><img src="<?php echo $baseUrl;?>/public/images/icon/new-proj-icon.png"><br>
          <strong>NEW PROJECTS</strong></a> </div>
        <!-- end box -->
       
      <!-- end slide -->
    </div>
  </div>
  <!-- end of masterslider --->
  
  
  <!-- Company Profile======================================================================================= -->
  <!-- featured section 40 Intro -->
  <div class="featured_section40">
    <div class="container">
      <div class="onecol_forty animate" data-anim-type="fadeInLeft" data-anim-delay="300"> <img src="<?php echo $baseUrl;?>/public/images/logo/intro-logo.png" alt="" class="rimg" /> </div>
      <div class="onecol_sixty last">
        <h2 class="roboto">About Aadinath ( your homes india )</h2>
        <h4 class="gray">Lorem Ipsum as their default model text, and a search for ipsum will cover
          many web sites still in infancy versions have over the years.</h4>
        <div class="clearfix margin_top5"></div>
        <div class="one_half"> <a href="#"><i class="fa"><img src="<?php echo $baseUrl;?>/public/images/icon/intro-icon.jpg"></i>
          <h4 class="roboto">Overview</h4>
          </a>
          <p>Lorem Ipsum as their default model text, and.</p>
        </div>
        <!-- end section -->
        <div class="one_half last"> <a href="#"><i class="fa"><img src="<?php echo $baseUrl;?>/public/images/icon/intro-icon.jpg"></i>
          <h4 class="roboto">Core Values</h4>
          </a>
          <p>Lorem Ipsum as their default model text, and.</p>
        </div>
        <!-- end section -->
        <div class="clearfix margin_top5"></div>
        <div class="one_half"> <a href="#"><i class="fa"><img src="<?php echo $baseUrl;?>/public/images/icon/intro-icon.jpg"></i>
          <h4 class="roboto">Mission & Vision</h4>
          </a>
          <p>Lorem Ipsum as their default model text, and.</p>
        </div>
        <!-- end section -->
        <div class="one_half last"> <a href="#"><i class="fa"><img src="<?php echo $baseUrl;?>/public/images/icon/intro-icon.jpg"></i>
          <h4 class="roboto">Leadership</h4>
          </a>
          <p>Lorem Ipsum as their default model text, and.</p>
        </div>
        <!-- end section -->
      </div>
    </div>
  </div>
  <!-- end featured section 40 Intro -->
  
  
  <!-- Projects ============================================================================================= -->
  <!-- featured section 42 Project -->
  <div class="clearfix margin_top5"></div>
  <div class="featured_section42">
    <div class="left">
      <ul class="haccordion" id="haccordion">
        <li class="bg1">
          <div class="heading">Residential</div>
          <div class="bgDescription"></div>
          <div class="description">
            <h2>Residential</h2>
            <a href="projects.html"><img src="<?php echo $baseUrl;?>/public/images/latest-Project/lp41.jpg" class="nav-project-img-border"></a> <a href="projects.html"><img src="images/latest-Project/lp41.jpg" class="nav-project-img-border" style="margin-left:180px;"></a> </div>
        </li>
      </ul>
      <ul class="haccordion" id="haccordion">
        <li class="bg2">
          <div class="heading">Commercial</div>
          <div class="bgDescription"></div>
          <div class="description">
            <h2>Commercial</h2>
            <p>Lorem Ipsum is simply dummy text of the printing industry.</p>
            <a href="projects.html">Read more</a> </div>
        </li>
      </ul>
      
    </div>
    <div class="right">
      <h1 class="roboto"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. <strong>LOREM IPSUM HAS INDUSTRY’S !</strong></h1>
      <p>standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
    </div>
  </div>
  <!-- end featured section 42 Project -->
  
  
  <!-- Flow Chart============================================================================================ -->
  <div class="clearfix margin_top12"></div>
  <div class="featured_section39">
    <div class="container">

    
     <div class="one_half"> <figure><object width="550" height="420" data="<?php echo $baseUrl;?>/public/video/aadinath-animation-left.swf"></object></figure> </div>
      <!-- end section --->
      <div class="one_half last"> <figure><object width="550" height="420" data="<?php echo $baseUrl;?>/public/video/aadinath-animation-right.swf"></object></figure> </div>
      <!-- end section -->
 
     
    </div>
  </div>
  <!-- end featured section 39 Flow Chart -->
  
  
  
  <!-- Resources============================================================================================= -->
  <!-- featured section 43 Resources
  <!--<div class="clearfix margin_top12"></div>-->
  <div class="parallax_section7">
    <div class="container">
      <h1 class="roboto white">Resources at Aadinath</h1>
      <h2 class="roboto white">To help you in your Real Estate Quest</h2>
      <div class="clearfix margin_top4"></div>
      <div class="one_third one animate" data-anim-type="fadeInLeft" data-anim-delay="500"> <span class="resource-head-text">FAQs</span>
        <p class="bigtfont" align="center"><b>Questions on Real Estate and How Aadinath can help</b> <br>
          <br>
          What terminologies should I be familiar with? How can Aadinath help me...</p>
        <br>
        <br>
        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/icon/read-more-btn.jpg"></a> </div>
      <!-- end section -->
      <div class="one_third two animate" data-anim-type="fadeInLeft" data-anim-delay="300"> <span class="resource-head-text">NEWS</span>
        <p class="bigtfont" align="center"><b>Featured news and videos on Real Estate</b> <br>
          <br>
          Videos with smart advice from experts at Aadinath. Featured news & events on Real Estate market in India...</p>
        <br>
        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/icon/read-more-btn.jpg"></a> </div>
      <!-- end section -->
      <div class="one_third third animate" data-anim-type="fadeInLeft" data-anim-delay="100"> <span class="resource-head-text">BLOG</span>
        <p class="bigtfont" align="center"><b>Articles on property market in India</b> <br>
          <br>
          <br>
          Get your daily dose of key updates and insights about property markets in India...</p>
        <br>
        <a href="#"><img src="<?php echo $baseUrl;?>/public/images/icon/read-more-btn.jpg"></a> </div>
      <!-- end section -->
    </div>
  </div>
  <!-- end featured section 39 Resources -->
  
  
  <!-- Testimonial========================================================================================== -->
  <!-- featured section 46 Testimonial--->
  <div class="clearfix margin_top12"></div>
  <div class="featured_section46">
    <div class="container">
      <h2 class="title27 roboto">People Says
        <div class="line"></div>
      </h2>
      <div class="clearfix margin_top1"></div>
      <div class="one_half animate" data-anim-type="fadeInLeft" data-anim-delay="200">
        <div class="bubble"> <img src="<?php echo $baseUrl;?>/public/images/testimonial/people-img-1.jpg" alt="" />
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,</p>
          <div class="clearfix"></div>
        </div>
        <strong>Anupam Sinha <em>&nbsp;</em></strong> </div>
      <!-- end section -->
      <div class="one_half last animate" data-anim-type="fadeInRight" data-anim-delay="200">
        <div class="bubble"> <img src="<?php echo $baseUrl;?>/public/images/testimonial/people-img-2.jpg" alt="" />
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,</p>
          <div class="clearfix"></div>
        </div>
        <strong>Meenu Raghav <em>&nbsp;</em></strong> </div>
      <!-- end section -->
    </div>
  </div>
  <!-- end featured section 46 Testimonial--->
  
  