<?php $baseUrl = $this->basePath(); 
//echo '<pre>';print_r($this->searchResultJsonArr);exit;

        $container = new \Zend\Session\Container('searchSessionFields');
        $projectListPage         = (is_numeric($container->cities)) ? $baseUrl.'/projects-in-noida' : $baseUrl.'/projects';
        
        $compareProjects       = new Zend\Session\Container('compareProjects');
        $allCompareProjects    = (count($compareProjects->allCompareProjects)) ? $compareProjects->allCompareProjects : [];

?>

  <input type="hidden" id="builderDetailId" value="">
<input type="hidden" id="PossessionFilters" value="<?php echo $this->possession;?>">
<input type="hidden" id="PropertyTypeFilters" value="<?php echo $this->propertyType;?>">
<input type="hidden" id="BudgetFilters" value="<?php echo $this->budget;?>">
<input type="hidden" id="BedroomFilters" value="<?php echo $this->bedroom;?>">


<link rel="stylesheet" href="<?php echo $baseUrl;?>/public/css/map-proj.css" type="text/css" />
<script
src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false">
</script>
<input type="hidden" id="baseUrl" value="<?php echo $baseUrl;?>">
<!---------Filteration bar----------->
<div class="filteration">
<div class="container">
  <div class="container-fluid bg-white">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><div style="color:#777; padding-top:15px; margin-right:30px;">Refine Results :</div></li>               
        <li class="dropdown">
            <a  class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" ><span id="possessionText" >Possession</span><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a style="cursor:default;"><input type="checkbox" onchange="managePossession('readyToMoveIn')" id="readyToMoveIn" value="readyToMoveIn" class="cursor"><span id="text_readyToMoveIn" > Ready to move in</span></a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="managePossession('upto3month')" id="upto3month" value="upto3month" class="cursor"><span id="text_upto3month" > Upto 3 Months</span></a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="managePossession('upto6month')" id="upto6month" value="upto6month" class="cursor"><span id="text_upto6month" > Upto 6 Months</span></a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="managePossession('upto9month')" id="upto9month" value="upto9month" class="cursor"><span id="text_upto9month" > Upto 9 Months</span></a></li>                  
          </ul>
        </li>
        <?php if(count($this->propertyTypeArr)){ ?>
        <li class="dropdown">
          <a class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" id="propertyTypeFilter">Property Type <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <?php
              foreach($this->propertyTypeArr as $propertyType){?>
                  <li><a style="cursor:default;"><input type="checkbox"  onchange="managePropertyType(<?php echo $propertyType['id'];?>)" id="propertyType_<?php echo $propertyType['id'];?>" value="<?php echo $propertyType['id'];?>" class="cursor"> <?php echo $propertyType['property_type'];?></a></li>
             <?php  }?>         
          </ul>
        </li>
        <?php } ?>    
        
        <li class="dropdown">
          <a class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" id="budgetFilter">Budget <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(2500000)" id="budget_2500000" value="2500000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 25 L</a></li> 
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(5000000)" id="budget_5000000" value="5000000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 50 L</a></li> 
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(7500000)" id="budget_7500000" value="7500000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 75 L</a></li> 
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(10000000)" id="budget_10000000" value="10000000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 1.00 Cr</a></li> 
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(15000000)" id="budget_15000000" value="15000000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 1.50 Cr</a></li> 
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(20000000)" id="budget_20000000" value="20000000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 2.00 Cr</a></li> 
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" id="bedroomFilter">Bedrooms <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a style="cursor:default;"><input type="checkbox" onchange="manageBedrooms(1)" id="bedroom_1" value="1" class="cursor"> 1 Bedroom</a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="manageBedrooms(2)" id="bedroom_2" value="2" class="cursor"> 2 Bedrooms</a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="manageBedrooms(3)" id="bedroom_3" value="3" class="cursor"> 3 Bedrooms</a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="manageBedrooms(4)" id="bedroom_4" value="4" class="cursor"> 4 Bedrooms</a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="manageBedrooms(5)" id="bedroom_5" value="4+" class="cursor"> 4+ Bedrooms</a></li>            
          </ul>
        </li>
        <li><a ><span class="glyphicon glyphicon-refresh"></span> <span style="cursor:pointer" id="resetFilter">Reset</span> </a></li> 
      </ul>
     <!--right---> 
      <ul class="nav navbar-nav navbar-right"> 
        <li><a onclick="gridListView('list')" class="cursor"><span class="glyphicon glyphicon-th-list"></span> LIST</a></li>       
        <li><a onclick="gridListView('grid')" class="cursor"><span class="glyphicon glyphicon-th-large"></span> GRID</a></li>
        <li><a href="<?php echo $baseUrl;?>/front-end/index/mapsearch" class="cursor"><span class="glyphicon glyphicon-map-marker"></span> MAP</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</div>
</div>

<!--<img id="callBackLoader" style="display:none;margin-right:20px;" src="<?php echo $baseUrl;?>/public/images/lightbox-ico-loading.gif">-->
<!------Map Project Detail ------->
<div class="col-md-3 map-proj-detail-main" id="prjDetailDiv" style="display: none;">
</div>



  
<!---Container--->
<div class="row map-main"> 
  <div class="col-md-9 map-left" id="googleMap" style="margin-top:100px;">
  </div>
  <div class="col-md-3 map-right" style="margin-top:105px;">
  <div class="row">
  <div class="clearfix margin_top1"></div>
	  <div class="col-md-12 totalproj">  	
		 <h5>Residential Projects <?php if($this->cityName!=''){ echo 'in '.$this->cityName; }else '';?></h5>
         Found a total of <?php echo count($this->searchResultArr)?> projects.
         
     </div>
  </div>
  <?php 
    $kk=0;
    foreach($this->searchResultArr as $searchResult){ 
        $bhkArray = [];
        if($searchResult['has_1BHK']==1)
           $bhkArray[] = 1;
        if($searchResult['has_2BHK']==1)
           $bhkArray[] = 2;
        if($searchResult['has_3BHK']==1)
           $bhkArray[] = 3;
        if($searchResult['has_4BHK']==1)
           $bhkArray[] = 4;
        if($searchResult['has_5BHK']==1)
           $bhkArray[] = 5;
        $bhkStr = '';
        $pp=0;
   // echo '<pre>';print_r($bhkArray);exit;
        foreach($bhkArray as $bhk){
            if($bhkStr!=''){
                if($pp==count($bhkArray)-1)
                    $bhkStr .= ' & ';
                else
                    $bhkStr .= ', ';
            }
            $bhkStr .= $bhk;
            $pp++;
        }
      
      ?>
      <div class="row" onclick="clickProject(<?php echo $kk;?>)" onmouseover="mouseOverProject(<?php echo $kk;?>)">
  <div class="clearfix margin_top1"></div>
	  <div class="col-md-12">  	
          <div class="col-md-4 map-right-img-box cursor"><a onclick="projectInfo(<?php echo $searchResult['project_id']?>)"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['project_image']?>"></a></div>
         
         
         <div class="col-md-8 map-right-detail-box cursor"><h5><a onclick="projectInfo(<?php echo $searchResult['project_id']?>)"><?php echo $searchResult['project_title']?></a></h5>
         <em><?php echo $searchResult['city_name']?></em>
         <div class="grid_type1"><?php echo $bhkStr;?> BHK ( <?php  echo $searchResult['min_floor_plan_size']?> - <?php  echo $searchResult['max_floor_plan_size']?> sq ft )</div>
         <div class="grid_button1">
	         <div class="grid_button_left1"><span class="grid_button_left_smltxt1">STARTING PRICE- </span><span class="rupee">`</span>
<?php  echo $searchResult['min_floor_plan_price']?> </div>
             <div class="grid_button_right1"><a href="#" data-toggle="modal" data-target="#myModal1" onclick="return getCallBAck('<?php echo $searchResult['project_id']?>','<?php echo $searchResult['project_title']?>')" title="Get call back"><span class="glyphicon glyphicon-envelope"></span></a></div>
         </div>
         </div>
         
     </div>
  </div>
  <?php $kk++; } ?>
 
  
  <div class="clearfix margin_top3"></div>
  </div>
  </div>
  </div>
  
  
  <script>
//$(document).ready(function(){
    var projectListPage = '<?php echo $projectListPage;?>';
    //return updateValues();
    
    
//});

</script>
  
  
<script src="<?php echo $baseUrl;?>/public/projectScripts/index/project_list_grid.js" type="text/javascript"></script>






  
  
  <!-- scroll to top======================================================================================== -->  
  <div class="scrollup" style="cursor:pointer"></div><!-- end scroll to top of the page-->
  
  <!-- Left Navigation Toggal=============================================================================== 
  <div id="style-selector"  style="left: -224px;">
<div class="style-selector-wrapper">
<span class="title">MENU</span>
<div>        
<br /><br />

<span class="title-sub2"><strong>Aadinath Guide <br>(Complete Property Guide)</strong></span>
<ul class="styles" style="border-bottom: none;">
    <li><a href="property-buying-step.html" class="demolinks">- FAQs</a></li>
    <li><a href="home-loan.html" class="demolinks">- Home Loan</a></li>
    <li><a href="vaastu-tips.html" class="demolinks">- Vaastu Tips</a></li>
    <li><a href="emi.html" class="demolinks">- EMI Calculator</a></li>
	<li><a href="nri.html" class="demolinks">- NRI Services</a></li>
    <li><a href="#" class="demolinks">- Blog</a></li>
</ul>
<span class="title-sub2">Need Any Help? <br><b>Call us: 0120-4256308</b></span>


<a href="#" class="close icon-chevron-right"></a>  
    
</div>
</div>-->
</div>
</div>

<!-- ######### JS FILES ######### -->
<!-- get jQuery used for the theme -->
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/universal/jquery.js"></script>
<script src="<?php echo $baseUrl;?>/public/js/style-switcher/styleselector.js"></script>
<script src="<?php echo $baseUrl;?>/public/js/animations/js/animations.min.js" type="text/javascript"></script>
<script src="<?php echo $baseUrl;?>/public/js/mainmenu/bootstrap.min.js"></script>
<script src="<?php echo $baseUrl;?>/public/js/mainmenu/customeUI.js"></script>
<script src="<?php echo $baseUrl;?>/public/js/masterslider/jquery.easing.min.js"></script>



 
  <script type="text/javascript">
    $('#myModal').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
  
 </script>

 <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">ACCOUNT LOGIN</h4>
      </div>
      <div class="modal-body">
        <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter your Email Address">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter your Password">
  </div>
  
  <div class="checkbox">
    <label>
      <input type="checkbox"> Remember Me      
    </label>
    <p class="help-block"><a href="#">Forgot Password?</a></p>
  </div>  
</form>

     </div>
      <div class="modal-footer">
      	<button type="button" class="btn btn-danger">LOGIN NOW!</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">SIGN UP</button>       
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Interested in <span id='callBackPrjName'>Parsvnath Paramount</span>?</h4>
      </div>
      <div class="modal-body">
        <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="callBackInputEmail" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Mobile No.</label>
    <input type="text" class="form-control" id="callBackInputMobile" placeholder="Mobile No.">
  </div>
  <input type="hidden"  id="callBackProjectId" >
</form>
      </div>
      <div class="modal-footer">
          <img id="callBackLoader" style="display:none;margin-right:20px;" src="<?php echo $baseUrl;?>/public/images/lightbox-ico-loading.gif">
          <button id="callBackSubmit" type="button" class="btn btn-danger" onclick="return submitCallBack()">GET CALL BACK</button>
               
      </div>
      
    </div>
  </div>
</div>
 <script>
 var searchResultJsonArr = <?php echo $this->searchResultJsonArr;?>;
 </script>
<script src="<?php echo $baseUrl;?>/public/js/scrolltotop/totop.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/mainmenu/sticky.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/mainmenu/modernizr.custom.75180.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/cubeportfolio/jquery.cubeportfolio.min.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/cubeportfolio/main5.js"></script>
<script src="<?php echo $baseUrl;?>/public/js/carouselowl/owl.carousel.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/accordion2/custom.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/universal/custom.js"></script>

<script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/jquery.disablescroll.js"></script>


<script src="<?php echo $baseUrl;?>/public/projectScripts/index/mapsearch.js" ></script>

<script>
$(document).ready(function(){
    $('#pageTitle').text('Aadinath | <?php if($container->searchCityName!='') echo 'Projects in '.$container->searchCityName; else echo 'Projects'; ?> ');
    return updateValues();
});
var CompareProjectsArr = [];
<?php if(count($allCompareProjects)){ 
    foreach($allCompareProjects as $projects){  ?>
        CompareProjectsArr.push(<?php echo $projects;?>);
<?php }} ?>
</script>