<?php $baseUrl = $this->basePath(); ?>

<div class="container">
	<div class="margin_top12"></div>
	<div class="page-header">
  <div class="clearfix"></div>  
  <h3>Property Purchase Guide for NRI</h3></div>  
<div class="container margin_top2">
<div class="content_left">        
        <div class="clearfix margin_top3"></div>        
       <h4>General</h4> 
        <div class="margin_top1">        
            <strong>NRI.</strong><br>
            <p style="text-align:justify;">
           Indian citizens who stay abroad for employment or carrying on business or vocation outside India or for any other purpose in circumstances indicating an indefinite period of stay abroad;</p>
           <div style="text-align:center;"><strong>OR</strong></div>
           <br>
           <p style="text-align:justify;">
		Government servants who are posted abroad on duty with the Indian missions and similar other agencies set up abroad by the Government of India where the officials draw their salaries out of Government resources;</p>
        <div style="text-align:center;"><strong>OR</strong></div>
        <br>
        <p style="text-align:justify;">
        Government servants deputed abroad on assignments with foreign Governments or regional/international agencies like the World Bank, International Monetary Fund (IMF), World Health Organisation (WHO), Economic and Social Commission for Asia and the Pacific (ESCAP)</p>
        <div style="text-align:center;"><strong>OR</strong></div>
        <br>
        <p style="text-align:justify;">
        Officials of the State Government and Public Sector Undertakings deputed abroad on temporary assignments or posted to their branches or offices abroad.
        </p> <br>          
        
        <p style="text-align:justify;" class="margin_top1"> 
        <strong>Foreign Citizen of Indian origin.</strong><br>      
        - he held an Indian Passport at any time or<br>
        - he or his father or paternal grandfather was a citizen of India by virtue of the Constitution of India or the Citizenship Act, 1955.<br> &nbsp; However this does not apply to citizens of Pakistan, Bangladesh, Afghanistan, Bhutan, Sri Lanka or Nepal.<br>
       </p>
       </div>
        <!-- end section -->        
           
          <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Buying a Property</h4>     
        <p style="text-align:justify;" class="margin_top1"> 
        <strong>Consumer keep in mind while purchasing a housing flat.</strong><br>      
        - Locality i.e. transport, schools, hospitals, market, business district, entertainment centers, hotels, restaurants, pollution levels, etc.<br>
        - Quoted area of the flat, i.e., carpet, built up area and super built up area<br>
        - Car parking space<br>
        - Quality of construction<br>
        - Reputation of the builder or seller<br>
        - Sufficient water and electric supply, other utilities<br>
        - Cost components: price, stamp duty, registration charges, transfer fees, monthly outgoings and society charges, costs of utilities<br>
        - Potential for resale or renting out of the property<br>
        - Any other distinguishing features or advantages of the property<br>
       </p><br>
       
        
        <p style="text-align:justify;" class="margin_top1"> 
        <strong>Checklist for buying a residential property.</strong><br>      
        - Market Trends about prevalent rates of property in the vicinity and last known transactions<br>
        - Ask for photocopies of the all deeds of title related to the property to be purchased. Examine the deeds to establish the ownership<br>&nbsp; of the property by seller, preferably through an advocate. Ascertain the survey number, village and registration district of the<br>&nbsp; property as these details are required for registration of the sale. Previous encumbrances and loans, if any on the property must be<br>&nbsp; cleared before completion of purchase of the property. The title of the Vendor to the property must be clear and marketable.<br>
        - Check for approved layout plan and approved building plan with number of floors<br>
        - Clearance from municipality, electricity, water, pollution and lift authorities<br>
        - Check the building bye-laws in that area to verify any issue with setback, side setback, height, etc.<br>
        - Confirm transfer fees, stamp duty and registration charges to be paid on purchase of the property as well as outgoings to be paid<br> &nbsp; for the property, i.e., property tax, water and electricity charges, society charges and maintenance charges<br>       
       </p>
       
       <p class="margin_top1" style="text-align:justify;">        
           <strong>NRIs require consent of the Reserve Bank to buy immovable property in India.</strong><br>
           No, NRI's do not require permission to buy any immovable property in India other than agricultural/plantation property or a farmhouse.</p>
           
       <p class="margin_top1" style="text-align:justify;">        
            <strong>Purchase consideration for the immovable property be paid under the general permission.</strong><br>
           The purchase consideration should be met either out of inward remittances in foreign exchange through normal banking channels or out of funds from any non-resident accounts maintained with banks in India.</p>
           
            <p class="margin_top1" style="text-align:justify;">        
            <strong>Limit on the number of housing properties that may be purchased by an NRI.</strong><br>
           There are no limits on the number of residential properties that may be bought by an NRI. However, repatriation (the process of converting a foreign currency into the currency of one’s own country) is allowed only in respect of two such properties.</p>
           
            <p style="text-align:justify;" class="margin_top1"> 
        <strong>Guiding principles for getting hold of agricultural land / plantation property / farmhouse by NRIs and foreign citizens of Indian origin.</strong><br>      
        - The Chief General Manager,<br>
        - Reserve Bank of India, Central Office<br>
        - Exchange Control Department<br>
        - Foreign Investment Division (III)<br>
        - Mumbai 400 001<br>       
       </p>
           
        
        <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Selling a Property</h4> 
        <p style="text-align:justify;" class="margin_top1"> 
        <strong>Home/Land be sold without the permission of Reserve Bank.</strong><br>
        Yes, the Reserve Bank has granted general permission for sale of property. However, where another foreign citizen of Indian origin purchases the property, funds towards the purchase consideration should either be remitted to India or paid out of balances in non-resident accounts maintained with banks in India.</p>
        
        <p style="text-align:justify;" class="margin_top1">
        <strong>Sale proceeds of such property if and when sold be remitted out of India.</strong><br>
        In the event of sale of immovable property other than agricultural land/farm house/plantation property in India by a NRI or PIO, the authorized dealer may allow repatriation of the sale proceeds outside India, provided all the following conditions are satisfied:<br><br>
        The immovable property was acquired by the seller in accordance with the provisions of the Exchange Control Rules/Regulations/Law in force at the time of acquisition, or the provisions of the Regulations framed under the Foreign Exchange Management Act, 1999;<br><br> 
        NRIs/PIOs can effect remittance of sale proceeds of immovable property in India irrespective of the period for which the property was held. The sale proceeds allowed to be repatriated should, however, not exceed the foreign exchange brought in to acquire the said property.<br><br> 
        In case of residential property, the repatriation of sale proceeds is restricted to not more than two such properties, if the property was purchased from funds held in NRE Account.<br><br>
        The amount sought to be repatriated abroad should not exceed the amount paid for acquisition of the immovable property in the foreign exchange received through normal banking channels or out of funds held in FCNR or NRE Account. In case of investment out of NRE Account the amount to be calculated as foreign currency is equivalent value as on the date of payment for acquisition of the said property.
        </p>
        
        <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Loan</h4> 
        <p style="text-align:justify;" class="margin_top1">
        <strong>RBI have any guidelines for loans to NRIs/PIOs</strong><br>
        - The loan amount shall not exceed 85% of the cost of the housing unit.<br>
        - Own contribution, which is the cost of housing unit financed less the loan amount, can be met from direct remittances from abroad<br>&nbsp; only through normal banking channels, your Non-Resident (External) [NR (E)] Account and /or Non-Resident (Ordinary) [NR (O)]<br>&nbsp; account and /or Non-Resident Special Rupee account [NRSR] in India.<br>
        - Reimbursement of the loan, comprising of the principal and interest including all the charges are to be remitted from abroad only<br>&nbsp; through normal banking channels, your Non-Resident (External) [NR (E)] Account and /or Non-Resident (Ordinary) [NR (O)] account<br>&nbsp; and /or Non-Resident Special Rupee account [NRSR] in India. </p>      
        
        <p style="text-align:justify;" class="margin_top1">
        <strong>Authorized dealers grant loans to NRIs for purchase of a flat/house for residential intention.</strong><br>
        Authorized dealers have been granted permission to grant loans to NRIs for acquisition of house/flat for self-occupation on their return to India subject to certain conditions. Repayment of the loan should be made within a period not exceeding 15 years out of inward remittance through banking channels or out of funds held in the investors' NRE/FCNR/NRO accounts.</p>
        
                <p style="text-align:justify;" class="margin_top1">
        <strong>authorized dealers grant housing loan to NRIs where he is a principal borrower with his resident close relative as a co-applicant / guarantor or where the land is owned jointly by such NRI borrower with his resident close relative.</strong><br>
        Yes. Such housing loans availed in rupees can also be repaid by the close relatives in India of the borrower.</p>
        
        <p style="text-align:justify;" class="margin_top1">
        <strong>Documents required along with the application</strong><br>
        - Photocopy of the labor contract and English translation duly countersigned by your employer.<br>
        - Latest salary certificate (in English) specifying the following: name (as it appears in the passport), date of joining, passport number,<br>&nbsp; designation, perquisites and salary.<br>
        - Photocopy of labor card/identity card<br>
        - Photocopy of valid resident visa stamped on the passport<br>
        - Photocopy of monthly statement of local bank account for the last 4 months<br>
        - Property related documents<br>
        </p>      
        <!-- end section -->
      
         
        
</div><!-- end content left side -->


<!-- right sidebar starts -->
<div class="right_sidebar">
	<div class="sidebar_widget">    
    	<div class="sidebar_title">
        <div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text">Quick Links</span></h3></div>
        </div>        
		<ul class="arrows_list1">        
            <li><a href="<?php echo $baseUrl?>/faq"><i class="fa fa-angle-right"></i> Property Buying Steps</a></li>
            <li><a href="<?php echo $baseUrl?>/home-loan"><i class="fa fa-angle-right"></i> Home Loan</a></li>
            <li><a href="<?php echo $baseUrl?>/vaastu-tips"><i class="fa fa-angle-right"></i> Vaastu Tips</a></li>
            <li><a href="<?php echo $baseUrl?>/emi-calculator"><i class="fa fa-angle-right"></i> EMI Calculator</a></li>
            <li><a href="<?php echo $baseUrl?>/nri-services"><i class="fa fa-angle-right"></i> NRI services</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Real Estate News</a></li> 
		</ul>
        <div class="margin_top8"></div>    
    	<ul class="arrows_list1">        
            <li><a href="#"><img src="<?php echo $baseUrl?>/public/images/latest-Project/lp3.jpg"></a></li>
            <li class="margin_top5"><a href="#"><img src="<?php echo $baseUrl?>/public/images/latest-Project/lp1.jpg"></a></li>
            <li class="margin_top5"><a href="#"><img src="<?php echo $baseUrl?>/public/images/latest-Project/lp2.jpg"></a></li>
            
		</ul>
        
       
	</div><!-- end section -->
	    	
</div><!-- end right sidebar -->

</div>
    
    <!-- end section -->
    
</div>   
    
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
    $(document).ready(function(){
        $('#pageTitle').text('Aadinath | NRI Services');
    });
    </script>


<!---End of Builder--->



  
  