<?php $baseUrl = $this->basePath(); 

//echo $this->max_floor_plan;exit;

//echo '<pre>';print_r($this->projectDetail);exit;
//echo '<pre>';print_r($this->floor_plans);exit;

?>
 <!-- tabs -->
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/js/tabs/assets/css/responsive-tabs.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/js/tabs/assets/css/responsive-tabs2.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl;?>/public/js/tabs/assets/css/responsive-tabs3.css">
    <input type="hidden" id="baseUrl" value="<?php echo $baseUrl;?>">

<!--zoom--->

<link href="<?php echo $baseUrl;?>/public/zoom/css/jquery.lightbox-0.5.css" rel="stylesheet" type="text/css" />
<!--------------HEADING-------------->  
    <div class="insidepg-heading">
  <div class="container">
   <div class="page-header1 clearfix">
  <div class="col-md-10"><h3><?php echo strtoupper($this->projectDetail['project_title'])?><br> <small><?php echo $this->projectDetail['address']?></small></h3></div>
  <?php if($this->projectDetail['brochure']!='')?>
  <a target="_blank" href="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['brochure'];?>"><div class="col-md-1 project-download-btnn1"><span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span><br>BROUCHER </div></a>  
  <?php if($this->projectDetail['application_form']!='')?>
  <a target="_blank" href="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['application_form'];?>"><div class="col-md-1 project-download-btnn2"><span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span><br>APP-FORM</div></a>
  </div>
  </div>  
  </div>
 
<!---------------SLIDER-------------->   

    <div class="container proj-detail-row"> 
  <div class="row">
  
 <!---Slider left--->
    <div class="col-md-9">

        <div id="sync1" class="owl-carousel">
        <?php if($this->projectDetail['slide_image_1']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_1'];?>" alt=""  /></div>
        <?php } if($this->projectDetail['slide_image_2']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_2'];?>" alt=""  /></div>
        <?php } if($this->projectDetail['slide_image_3']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_3'];?>" alt=""  /></div>
        <?php } if($this->projectDetail['slide_image_4']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_4'];?>" alt=""  /></div>
        <?php } if($this->projectDetail['slide_image_5']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_5'];?>" alt=""  /></div>
        <?php } if($this->projectDetail['slide_image_6']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_6'];?>" alt=""  /></div>
        <?php } if($this->projectDetail['slide_image_7']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_7'];?>" alt=""  /></div>
        <?php } if($this->projectDetail['slide_image_8']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_8'];?>" alt=""  /></div>
        <?php } if($this->projectDetail['slide_image_9']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_9'];?>" alt=""  /></div>
        <?php } if($this->projectDetail['slide_image_10']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_10'];?>" alt=""  /></div>
        <?php } ?>  
   
      </div><!-- end section -->
    
      <div id="sync2" class="owl-carousel">
        <?php if($this->projectDetail['slide_image_1']!='')?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_1'];?>" alt="" style="width:150px;"/></div>
        <?php if($this->projectDetail['slide_image_2']!='')?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_2'];?>" alt="" style="width:150px;"/></div>
        <?php if($this->projectDetail['slide_image_3']!='')?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_3'];?>" alt="" style="width:150px;"/></div>
        <?php if($this->projectDetail['slide_image_4']!='')?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_4'];?>" alt="" style="width:150px;"/></div>
        <?php if($this->projectDetail['slide_image_5']!='')?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_5'];?>" alt="" style="width:150px;"/></div>
        <?php if($this->projectDetail['slide_image_6']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_6'];?>" alt="" style="width:150px;"/></div>
        <?php } if($this->projectDetail['slide_image_7']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_7'];?>" alt="" style="width:150px;"/></div>
        <?php } if($this->projectDetail['slide_image_8']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_8'];?>" alt="" style="width:150px;"/></div>
        <?php } if($this->projectDetail['slide_image_9']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_9'];?>" alt="" style="width:150px;"/></div>
        <?php } if($this->projectDetail['slide_image_10']!=''){?>   
        <div class="item"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['slide_image_10'];?>" alt="" style="width:150px;"/></div>
        <?php } ?> 
        
      </div><!-- end section -->
    


  
  </div>
  <?php
        $bhkArray = [];
        if($this->projectDetail['has_1BHK']==1)
           $bhkArray[] = 1;
        if($this->projectDetail['has_2BHK']==1)
           $bhkArray[] = 2;
        if($this->projectDetail['has_3BHK']==1)
           $bhkArray[] = 3;
        if($this->projectDetail['has_4BHK']==1)
           $bhkArray[] = 4;
        if($this->projectDetail['has_5BHK']==1)
           $bhkArray[] = 5;
        $bhkStr = '';
        $pp=0;
   // echo '<pre>';print_r($bhkArray);exit;
        foreach($bhkArray as $bhk){
            if($bhkStr!=''){
                if($pp==count($bhkArray)-1)
                    $bhkStr .= ' & ';
                else
                    $bhkStr .= ', ';
            }
            $bhkStr .= $bhk;
            $pp++;
        }
  
  ?>
 <!---Slider right--->
  <div class="col-md-3">
  <div class="row">
  <div class="col-md-9 proj-detail-right1">
  <span class="proj-price-text"><span class="rupee">`</span> <?php echo $this->min_floor_plan;?> - <span class="rupee">`</span> <?php echo $this->max_floor_plan;?></span><br>
	<?php echo $bhkStr;?> BHK
  </div>
  <div class="col-md-3 proj-detail-right1">
  <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-check"></span></button>
  </div>  
  </div>
  <div class="row">
  <div class="col-md-12  proj-detail-right1">  
  <span class="proj-price-text">POSSESSION <?php echo date('M', strtotime($this->projectDetail['possession']))?> `<?php echo date('Y', strtotime($this->projectDetail['possession']))?></span><br>
  Last Update <?php echo date('m-d-Y', strtotime($this->projectDetail['last_updated']))?>
  </div>
  </div>
  <div class="row">
  <div class="col-md-12 less2" style="margin:0; padding:0;">  
    <div class="logregform two">       
        <div class="title"> 
        <span class="proj-price-text">Interested in this project?</span><br>
        <span style="font-size:12px; line-height:10px;">Please fill in your details below and we will get in touch with you shortly</span> 		           
        </div>        
        <div class="feildcont">        
            <form role="form">            
                <label>Name <em>*</em></label>
                <input type="text">
                
                <label>Email <em>*</em></label>
                <input type="text">
                
                <div class="one_half">
                    <label>City <em>*</em></label>
                    <input type="text">
                </div>
                
                 <div class="one_half last">
                    <label>Mobile No. <em>*</em></label>
                    <input type="text">
                </div>                                
                <button type="button" class="fbut">GET CALL BACK</button>                    
            </form>        
        </div>
	</div>
	</div>
    </div>
  </div>
  
  </div>
  </div>

<!------------OVERVIEW---------------> 
    <div class="clearfix"></div>
    <div class="divider_line1"></div>
    <div class="container">
		<div class="one_full stcode_title7">    
            <h2>ABOUT   <strong><?php echo strtoupper($this->projectDetail['project_title'])?></strong>  PROJECT
        <em><?php echo $this->projectDetail['address']?></em>
       </h2>
        
        <p style="text-align:justify; padding-top:30px;"><?php echo $this->projectDetail['project_desc']?></em>
    </p>
    </div>
  </div>
  
<!------SPECIFICATION/AMENITIES------->

   <div class="clearfix"></div>
   <div class="container">
		<div class="three_fourth"  style="margin-top:65px;">    
    	<div class="one_third">   
        <div class="flips4">        
            <div class="flips4_front flipscont4">
            	<img src="<?php echo $baseUrl;?>/public/images/icon/address-icon.png" alt="" >
                <h5><strong>ADDRESS</strong></h5>
            </div>            
            <div class="flips4_back flipscont4 white-text">
            	<h5><strong>ADDRESS</strong></h5>
                <p><?php echo $this->projectDetail['address']?></p>
            </div>
        </div>
        </div><!-- end section -->
                            
   		<div class="one_third">   
        <div class="flips4">        
            <div class="flips4_front flipscont4">
            	<img src="<?php echo $baseUrl;?>/public/images/icon/builtuparea-icon.png" alt="" >
                <h5><strong>SUPER BUILTUP AREA</strong></h5>
            </div>            
            <div class="flips4_back flipscont4 white-text">
            	<h5><strong>SUPER BUILTUP AREA</strong></h5>
               <p><?php echo min($this->floorSizeArr)?> - <?php echo max($this->floorSizeArr)?> sq.ft.</p>
            </div>
            
        </div>
    
    </div><!-- end section -->    
    
        <div class="one_third">   
        <div class="flips4">        
            <div class="flips4_front flipscont4">
            	<img src="<?php echo $baseUrl;?>/public/images/icon/possession-icon.png" alt="" >
                <h5><strong>POSSESSION</strong></h5>
            </div>            
            <div class="flips4_back flipscont4 white-text">
            	<h5><strong>POSSESSION</strong></h5>
                <p><?php echo date('M', strtotime($this->projectDetail['possession']))?> `<?php echo date('Y', strtotime($this->projectDetail['possession']))?></p>

            </div>
            
        </div>
    
    </div><!-- end section -->
        
        <div class="margin_top3"></div><div class="clearfix"></div>
        
        <div class="one_third">   
        <div class="flips4">        
            <div class="flips4_front flipscont4">
            	<img src="<?php echo $baseUrl;?>/public/images/icon/price-icon.png" alt="" >
                <h5><strong>STARTING PRICE</strong></h5>
            </div>            
            <div class="flips4_back flipscont4 white-text">
            	<h5><strong>STARTING PRICE</strong></h5>
                <p><span class="rupee">`</span> <?php echo $this->min_floor_plan;?></p>

            </div>
            
        </div>
    
    </div><!-- end section -->
                            
   		<div class="one_third">   
        <div class="flips4">        
            <div class="flips4_front flipscont4">
            	<img src="<?php echo $baseUrl;?>/public/images/icon/building-icon.png" alt="" >
                <h5><strong>BUILDINGS</strong></h5>
            </div>            
            <div class="flips4_back flipscont4 white-text">
            	<h5><strong>BUILDINGS</strong></h5>
                <p>5</p>

            </div>
            
        </div>
    
    </div><!-- end section -->    
    
        <div class="one_third">   
        <div class="flips4">        
            <div class="flips4_front flipscont4">
            	<img src="<?php echo $baseUrl;?>/public/images/icon/configurations-icon.png" alt="" >
                <h5><strong>CONFIGURATIONS</strong></h5>
            </div>            
            <div class="flips4_back flipscont4 white-text">
            	<h5><strong>CONFIGURATIONS</strong></h5>
                <p>3, 4, 5 Bedroom Apartment,Penthouse</p>

            </div>
            
        </div>
    
    </div>
    </div><!-- end section -->
    
    <div class="one_fourth last">
    <div class="last stcode_title5">
            
        <h3><span class="line2"></span><span class="line"></span><span class="text"><strong>AMENITIES</strong></span></h3>
        
        <ul>
        <?php
            foreach($this->amenitiesArr as $amenities){ ?>
               <li><img height="30" width="40" src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $amenities['amenity_image'];?>"> <?php echo $amenities['amenity_name'];?></li> 
        <?php } ?>
        </ul>        
    </div>
    </div>
  </div>
  
<!-------------FLOOR PLAN------------->
   <div class="clearfix margin_top2"></div>
   <div class="divider_line1"></div>
   <div class="container">
      <div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text"><strong>FLOOR PLANS</strong></span></h3></div>
		<table class="table table-bordered gallery text-center">
      <thead>
        <tr class="active">
          <td><b>TYPE</b></td>
          <td><b>SIZE</b></td>
          <td><b>PRICE</b></td>       
          <td><b>FLOOR PLAN</b></td>
        </tr>
      </thead>
      <tbody>
        <?php foreach($this->floor_plans as $floor_plan){ ?>
        <tr>
          <td><?php echo $floor_plan['plan_type'] ?></th>
          <td><?php echo $floor_plan['size'] ?> <?php echo $floor_plan['unit'] ?></td>
          <td><?php echo $floor_plan['price'].' '.$floor_plan['price_unit'] ?></td>
          <td><a class="yo" href="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $floor_plan['floor_plan_image'] ?>" title="<?php echo $this->projectDetail['project_title']?> - FLOOR PLAN (<?php echo $floor_plan['plan_type'] ?> / <?php echo $floor_plan['size'] ?> <?php echo $floor_plan['unit'] ?>)">View Floor Plan</a></td>
        </tr>
        <?php } ?>
                     
      </tbody>
    </table>
  </div>

<!---GOOGLEMAP/LOCATIONMAP/SITEPLAN--->
  
   <div class="clearfix margin_top2"></div>
   <div class="divider_line1"></div>
   <div class="container">    	        
		<ul class="tabs side">
            <li class="animate" data-anim-type="fadeInUp" data-anim-delay="100"><a href="#demo-tab-1" target="_self"><img src="<?php echo $baseUrl;?>/public/images/icon/googlemap-icon.png"><br>Google Map</a></li>
            <li class="animate" data-anim-type="fadeInUp" data-anim-delay="200"><a href="#demo-tab-2" target="_self"><img src="<?php echo $baseUrl;?>/public/images/icon/location-map-icon.png"><br>Location Map</a></li>
            <li class="animate" data-anim-type="fadeInUp" data-anim-delay="300"><a href="#demo-tab-3" target="_self"><img src="<?php echo $baseUrl;?>/public/images/icon/siteplan-icon1.png"><br>Site Plan</a></li>
        </ul>

        <div class="tabs-content">
            <div id="demo-tab-1" class="tabs-panel gallery"> 
            <div id="map-canvas" style="width:900px; height:400px;"></div>  
             
                
            </div><!-- end tab 1 -->
            
            <div id="demo-tab-2" class="tabs-panel gallery">
            <a class="yo" href="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['location_map'];?>" title="<?php echo $this->projectDetail['project_title']?> - LOCATION MAP"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['location_map'];?>" style="width:900px; height:400px;"></a>                         
               
                
            </div><!-- end tab 2 -->
            
            <div id="demo-tab-3" class="tabs-panel gallery">                 
            <a class="yo" href="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['site_plan'];?>" title="<?php echo $this->projectDetail['project_title']?> - SITE PLAN"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $this->projectDetail['site_plan'];?>" style="width:900px; height:400px;"></a>            
                            
            </div><!-- end tab 3 -->
        
    	</div><!-- end all tabs -->

</div>



<!------BUILDER DETAILS------->

  <div class="clearfix"></div>
   <div class="divider_line1"></div>

<div class="container">
<div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text"><strong>ABOUT BUILDERS</strong></span></h3></div>
	<div class="three_fourth">    
    	<p style="text-align:justify;"><?php echo $this->projectDetail['about_builder'];?><br><br> <a href="<?php echo $baseUrl;?>/index/builder-detail?id=<?php echo $this->projectDetail['bldId'];?>"><b>View more about Builders...</b></a></p>
    </div><!-- end section -->
    
    <div class="one_fourth last">
    <div class="last stcode_title5">
        <ul>
        <li>EXPERIENCE : <?php echo $this->projectDetail['builder_experience'];?> Years</li>
        <li>TOTAL PROJECTS : <?php echo $this->totalProject;?></li>
        <li>ONGOING PROJECTS : <?php echo $this->ongoingProject;?></li>
        </ul>        
    </div>
    </div>
  </div>

<!----------SIMILER PROJECT----------->

   <div class="clearfix margin_top2"></div>
   <div class="divider_line1"></div>  
   <div class="container">
          <div class="stcode_title4">
		<div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text"><strong>SIMILAR PROJECTS</strong></span></h3></div>
	</div>
    
    <div class="margin_top1"></div>
    <div class="clearfix"></div>
        
    <div id="owl-demo7" class="owl-carousel">
            
        <div class="item"><img class="lazyOwl" src="<?php echo $baseUrl;?>/public/images/similar-project/supertech-orb-elevation.jpeg" alt="" /></div>
        <div class="item"><img class="lazyOwl" src="<?php echo $baseUrl;?>/public/images/similar-project/ajnara-grand-heritage-elevation.jpeg" alt="" /></div>
        <div class="item"><img class="lazyOwl" src="<?php echo $baseUrl;?>/public/images/similar-project/apex-buildcon-athena-elevation.jpeg" alt="" /></div>
        <div class="item"><img class="lazyOwl" src="<?php echo $baseUrl;?>/public/images/similar-project/panchsheel-group-pratishtha-elevation.jpeg" alt="" /></div>
        <div class="item"><img class="lazyOwl" src="<?php echo $baseUrl;?>/public/images/similar-project/supertech-orb-elevation.jpeg" alt="" /></div>
        <div class="item"><img class="lazyOwl" src="<?php echo $baseUrl;?>/public/images/similar-project/ajnara-grand-heritage-elevation.jpeg" alt="" /></div>
        <div class="item"><img class="lazyOwl" src="<?php echo $baseUrl;?>/public/images/similar-project/apex-buildcon-athena-elevation.jpeg" alt="" /></div>
        <div class="item"><img class="lazyOwl" src="<?php echo $baseUrl;?>/public/images/similar-project/panchsheel-group-pratishtha-elevation.jpeg" alt="" /></div>

	</div><!-- end section -->
    <div class="clearfix margin_top4"></div>
        </div>
        
<!---------EMI CALCULATOR----------->

    <div class="clearfix margin_top2"></div>
    <div class="divider_line1"></div> 	
        
    <div class="container">
<div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text"><strong>EMI Calculator</strong></span></h3></div>



<div class="starter-template col-sm-12 margin_top7" style="background:url(<?php echo $baseUrl;?>/public/images/bg/emi-bg.jpg) 100% 0%; background-repeat:no-repeat;">

<form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="intrate" class="col-sm-4 control-label">Interest Rate</label>
	<div class="col-sm-4">
		<input type="text" class="form-control" id="intrate" placeholder="Enter Interest Rate" value="10.5">
	</div>
  </div>
  <div class="form-group">
    <label for="remAmount" class="col-sm-4 control-label">Remaining Loan Amount</label>
	<div class="col-sm-4">
		<input type="text" class="form-control" id="remAmount" placeholder="Enter Remaing Loan Amount" value="1,000,000">
	</div>
  </div>
  <div class="form-group">
    <label for="emiAmount" class="col-sm-4 control-label">Emi Amount</label>
	<div class="col-sm-4">
		<input type="text" class="form-control" id="emiAmount" placeholder="Enter Emi Amount" value="20,000">
	</div>
  </div>
  <div class="form-group">
    <label for="dayOfEmi" class="col-sm-4 control-label">day of month on which emi is paid</label>
	<div class="col-sm-4">
		<input type="text" class="form-control" id="dayOfEmi" placeholder="Enter day of month on which emi is paid" value="10">
	</div>
  </div>
  <div class="margin_top2"></div>
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
      <button onClick="javascript:generateTable();return false;" class="btn btn-danger btn-sm">Generate Table</button>
    </div>
  </div>
</form>
<div id="content">
</div>
<script>
function generateTable(){
document.getElementById("content").innerHTML = "";
var date = new Date();
var dateofEmi = document.getElementById('dayOfEmi').value;
var dayOfEmi = dateofEmi - 1;
var curMonth = date.getMonth() + 1;
var curYear = date.getFullYear();
var ydate = new Date(curYear,0,0);
var ydate1 = new Date(curYear+1,0,0);
var no_of_day_in_year = (ydate1-ydate)/(60*60*24*1000);
var interest_rate = parseFloat(document.getElementById('intrate').value);
var starting_amount = parseInt(document.getElementById('remAmount').value.replace(/,/g, ""));
var emiAmount = parseInt(document.getElementById('emiAmount').value.replace(/,/g, ""));
var total_interest_paid = 0;
var content = "";
var content1 = "";
content += "<table class='table'>";
content += "<tr>";
content += "<td>Remaining Loan Amount<td/> <td>Interest till emi date<td/> <td>Interest from emi date to End of Month<td/> <td>Total Interest<td/> <td>Amount at end of month include total Interest - Emi<td/> <td>Month<td/> <td>Year<td/>";
content += "<tr/>";
while(starting_amount > 0){
	var lastDayOfMonth = (new Date(curYear, curMonth ,0)).getDate();
	var int_before_emi = (dayOfEmi*starting_amount*interest_rate)/(no_of_day_in_year*100);
	var int_after_emi = 0;
	if( (int_before_emi+starting_amount) > emiAmount ){
		int_after_emi = ((lastDayOfMonth-dayOfEmi)*(starting_amount-emiAmount)*interest_rate)/(no_of_day_in_year*100);
	}
	content += "<tr>";
	content += "<td>"+Math.round(starting_amount)+"<td/>";
	content += "<td>"+Math.round(int_before_emi)+"<td/>";
	content += "<td>"+Math.round(int_after_emi)+"<td/>";
	content += "<td>"+Math.round(int_before_emi+int_after_emi)+"<td/>";
	if(starting_amount > emiAmount ){
		starting_amount = starting_amount - emiAmount + int_before_emi + int_after_emi;
	}else{
		starting_amount = 0;
	}
	content += "<td>"+Math.round(starting_amount)+"<td/>";
	content += "<td>"+ (curMonth) +"<td/>";
	content += "<td>"+ (curYear) +"<td/>";
	content += "<tr/>";
	curMonth = curMonth + 1;
	if(curMonth == 13){
		curMonth = 1;
		curYear = curYear + 1;
		ydate = new Date(curYear,0,0);
		ydate1 = new Date(curYear+1,0,0);
		no_of_day_in_year = (ydate1-ydate)/(60*60*24*1000);
	}
	total_interest_paid = total_interest_paid + Math.round(int_before_emi + int_after_emi);
}
content += "<table\>";
content1 += "<table>";
	content1 += "<tr>";
	content1 += "<td> Total interest : "+total_interest_paid+"<td/>";
	content1 += "<tr\>";
content1 += "<table\><br/>";
var div = document.createElement('div');
div.innerHTML = content1 + content;
document.getElementById('content').appendChild(div);
return false;
}
document.getElementById("remAmount").onblur = function (){
    this.value = parseFloat(this.value.replace(/,/g, ""))
                    .toFixed(2)
                    .toString()
                    .replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
document.getElementById("emiAmount").onblur = function (){
    this.value = parseFloat(this.value.replace(/,/g, ""))
                    .toFixed(2)
                    .toString()
                    .replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
</script>
      </div>

  </div>   
        
        
<!-------------DISCUSS THIS PROJECT------------->
   <div class="clearfix margin_top2"></div>
   <div class="divider_line1"></div>
   <div class="container">
      <div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text"><strong>DISCUSS THIS PROJECT</strong></span></h3></div>
		
       <div id="disqus_thread" class="margin_top3"></div>
	   <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'Aadinath';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
	   <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript> 
  </div>
  
  
  <script type="text/javascript" src="<?php echo $baseUrl;?>/public/js/universal/jquery.js"></script>
  <!--For Popup Jquery --->
  <script type="text/javascript">
    $('#myModal').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
  
 </script>
 <script src="<?php echo $baseUrl;?>/public/js/tabs/assets/js/responsive-tabs.min.js" type="text/javascript"></script>
 
<script language="javascript" type="text/javascript" src="<?php echo $baseUrl;?>/public/zoom/js/jquery.lightbox-0.5.js"></script>

<!--	<script language="javascript" type="text/javascript" src="zoom/js/jquery.js"></script>	-->
	<script type="text/javascript">
//    $(function() {
//	$(document).ready(function() {
        $('.gallery a').lightBox();
		//$('#gallery2 a').lightBox();
		$('.gallery a.yo').lightBox();
		//$('#gallery4 a.down').lightBox();
		//$('#gallery5 a.me').lightBox();
		
//    });
//    });
</script>


<!----disqus---->
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'Aadinath';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
    <script>
function initialize() {
  var myLatlng = new google.maps.LatLng(<?php echo $this->projectDetail['latitude']?>,<?php echo $this->projectDetail['longitude']?>);
  var mapOptions = {
    zoom: 12,
    center: myLatlng
  }
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: '<?php echo $this->projectDetail['project_title']?>'
  });
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>