 <?php $baseUrl = $this->basePath(); ?>

<!---------Filteration bar----------->
<div class="filteration">
<div class="container">
  <div class="container-fluid bg-white">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><div style="color:#777; padding-top:15px; margin-right:30px;">Refine Results :</div></li>               
        <li class="dropdown">
          <a  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" id="possessionFilter">Possession <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a ><input type="checkbox" onchange="managePossession('readyToMoveIn')" id="readyToMoveIn" value="readyToMoveIn"> Ready to move in</a></li>
            <li><a ><input type="checkbox" onchange="managePossession('upto3month')" id="upto3month" value="upto3month"> Upto 3 Months</a></li>
            <li><a ><input type="checkbox" onchange="managePossession('upto6month')" id="upto6month" value="upto6month"> Upto 6 Months</a></li>
            <li><a ><input type="checkbox" onchange="managePossession('upto9month')" id="upto9month" value="upto9month"> Upto 9 Months</a></li>            
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" id="propertyTypeFilter">Property Type <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <?php
              foreach($this->propertyTypeArr as $propertyType){?>
                  <li><a ><input type="checkbox"  onchange="managePropertyType(<?php echo $propertyType['id'];?>)" id="propertyType_<?php echo $propertyType['id'];?>" value="<?php echo $propertyType['id'];?>"> <?php echo $propertyType['property_type'];?></a></li>
             <?php  }?>         
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" id="budgetFilter">Budget <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <li><a ><input type="checkbox" onchange="manageBudget(2500000)" id="budget_2500000" value="2500000">&nbsp;&nbsp;<span class="rupee">`</span> 25 L</a></li> 
              <li><a ><input type="checkbox" onchange="manageBudget(5000000)" id="budget_5000000" value="5000000">&nbsp;&nbsp;<span class="rupee">`</span> 50 L</a></li> 
              <li><a ><input type="checkbox" onchange="manageBudget(7500000)" id="budget_7500000" value="7500000">&nbsp;&nbsp;<span class="rupee">`</span> 75 L</a></li> 
              <li><a ><input type="checkbox" onchange="manageBudget(10000000)" id="budget_10000000" value="10000000">&nbsp;&nbsp;<span class="rupee">`</span> 1.00 Cr</a></li> 
              <li><a ><input type="checkbox" onchange="manageBudget(15000000)" id="budget_15000000" value="15000000">&nbsp;&nbsp;<span class="rupee">`</span> 1.50 Cr</a></li> 
              <li><a ><input type="checkbox" onchange="manageBudget(20000000)" id="budget_20000000" value="20000000">&nbsp;&nbsp;<span class="rupee">`</span> 2.00 Cr</a></li> 
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" id="bedroomFilter">Bedrooms <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a ><input type="checkbox" onchange="manageBedrooms(1)" id="bedroom_1" value="1"> 1 Bedroom</a></li>
            <li><a ><input type="checkbox" onchange="manageBedrooms(2)" id="bedroom_2" value="2"> 2 Bedrooms</a></li>
            <li><a ><input type="checkbox" onchange="manageBedrooms(3)" id="bedroom_3" value="3"> 3 Bedrooms</a></li>
            <li><a ><input type="checkbox" onchange="manageBedrooms(4)" id="bedroom_4" value="4"> 4 Bedrooms</a></li>
            <li><a ><input type="checkbox" onchange="manageBedrooms(5)" id="bedroom_5" value="4+"> 4+ Bedrooms</a></li>           
          </ul>
        </li>
        <li><a ><span class="glyphicon glyphicon-refresh"></span> <span style="cursor:pointer" id="resetFilter">Reset</span> </a></li> 
      </ul>
     <!--right---> 
      <ul class="nav navbar-nav navbar-right"> 
        <li><a onclick="changeView('list')"><span class="glyphicon glyphicon-th-list"></span> LIST</a></li>       
        <li><a onclick="changeView('grid')"><span class="glyphicon glyphicon-th-large"></span> GRID</a></li>
             
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</div>
</div>

 
  <div class="clearfix margin_top12"></div>
  
  <!---------Heading----------->
  <input type="hidden" id="baseUrl" value="<?php echo $baseUrl;?>">
  <input type="hidden" id="PossessionFilters" value="<?php echo $this->possession;?>">
  <input type="hidden" id="PropertyTypeFilters" value="<?php echo $this->propertyType;?>">
  <input type="hidden" id="BudgetFilters" value="<?php echo $this->budget;?>">
  <input type="hidden" id="BedroomFilters" value="<?php echo $this->bedroom;?>">
  
  <div class="insidepg-heading">
  <div class="container">
  <div class="page-header">
  <div class="clearfix margin_top4"></div>  
  <h3>New Residential Projects in Delhi<br> <small>Found a total of <?php echo count($this->searchResultArr)?> projects.</small></h3> </div>
  </div>  
  </div>
 
  <!---------All Project-----------> 
  

  <div id='searchProjects'>
     <?php if($this->viewType == 'list'){ 
        if(count($this->searchResultArr)){
            $ii = 0;
            foreach($this->searchResultArr as $searchResult){
    ?>            
            <div class="container insidepg-proj-row"> 
              <div class="row">
              <div class="col-md-3  insidepg-proj-img-box"><a href="projects-detail.html"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['project_image']?>" class="img-responsive"></a></div>
              <div class="col-md-7 insidepg-proj-detail">
              <div class="bs-example" data-example-id="bordered-table">
               <h4 id="tables-bordered"><a href="projects-detail.html"><?php echo $searchResult['project_title']?></a></h4>
              <p><?php echo $searchResult['address']?></p>
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>PROPERTY</th>
                      <th>SIZE</th>
                      <th>BUILDER PRICE</th>
                    </tr>
                  </thead>
                  <tbody>
                      <?php $floorSizeArr = array();
                      foreach($searchResult['floor_plans'] as $floor_plan){?>
                          <tr>
                          <td><?php echo $floor_plan['plan_type'];?></th>
                          <td><?php echo $floor_plan['size'].' '.$floor_plan['unit'];?></td>
                          <td><span class="rupee">`</span> <?php echo $floor_plan['price'];?></td>
                        </tr> 
                     <?php $floorSizeArr[]= $floor_plan['price'];
                      }?>

                  </tbody>
                </table>
              </div>
              </div>


              <div class="col-md-2 insidepg-proj-builder">
              <div class="row insidepg-proj-builder-img" align="center"><a href="#"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['builder_image']?>"  class="img-responsive"></a></div>
            <div class="row insidepg-proj-builder text-center"><?php if(count($floorSizeArr)){ ?><div class="proj-price-text"><span class="rupee">`</span>  <?php echo min($floorSizeArr);?> - <span class="rupee">`</span> <?php echo max($floorSizeArr);?></div><?php } ?>
                  POSSESSION <?php echo date('M', strtotime($searchResult['possession']))?> `<?php echo date('d', strtotime($searchResult['possession']))?></div>
              <div class="row text-center"><button type="button" class="btn btn-danger" onclick="return getCallBAck('<?php echo $searchResult['project_id']?>','<?php echo $searchResult['project_title']?>')">GET CALL BACK</button></div>
              </div>
              </div>
              </div>  
<?php
        $ii++; 
        if($ii % 4 == 0 && $ii != count($this->searchResultArr)){?>

    <!---Add-Banner--->  
     <div class="container insidepg-proj-row">
     <div class="clearfix margin_top2"></div> 
         <div class="row"><a style="float:left" href="#"><img src="<?php echo $baseUrl;?>/public/images/project/add-banner1.jpg"></a></div>
     <div class="clearfix margin_top3"></div> 
     </div>
    <?php }  
            }
        }
      }else{ ?>
          
        <div class="content_fullwidth">
        <div class="featured_section102">
        <div class="container insidepg-proj-grid-row">
            <?php 
        $count = 0;
        foreach($this->searchResultArr as $searchResult){
        $count++;
    ?>
        <div class="one_fourth_less <?php if($count % 4 == 0){ echo 'last';}?> "  >    
            <a href="projects-detail.html"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['project_image']?>" alt="" /></a>
            <h5><a href="projects-detail.html"><?php echo $searchResult['project_title']?></a> <em><?php echo $searchResult['address']?></em></h5>
             <?php  $floorSizeArr = array();$floorPriceArr = array();
             if(count($searchResult['floor_plans'])){
                    foreach($searchResult['floor_plans'] as $floor_plan){
                        $floorPriceArr[]= $floor_plan['price'];
                        $floorSizeArr[]= $floor_plan['size'];
             }}?>
            <div class="grid_type">
            4, 2 & 3 BHK ( <?php if(count($floorSizeArr)) echo max($floorSizeArr)?> - <?php if(count($floorSizeArr)) echo min($floorSizeArr)?> sq ft )<br>
            <span class="grid_type_left_smltxt">Possession Date: <?php echo date('M', strtotime($searchResult['possession']))?> `<?php echo date('d', strtotime($searchResult['possession']))?></span>
            </div>
            <div class="grid_button">
            <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> <?php if(count($floorPriceArr)) echo min($floorPriceArr)?></div>
            <div class="grid_button_right">
            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
            </div>
        </div>
        
    <?php  
    
     if($count % 4 == 0 && $count != count($this->searchResultArr)){ ?>
         <div style="border-bottom: 4px double #ccc;">&nbsp;</div>
    <?php }
        if($count % 8 == 0){ ?>
        <div class="container insidepg-proj-row">
        <div class="clearfix margin_top3"></div> 
        <div class="row"><a style="float:left" href="#"><img src="<?php echo $baseUrl;?>/public/images/project/add-banner1.jpg"></a></div>
        <div class="clearfix margin_top3"></div> 
        </div>
    <?php }
        }
    ?>   
        </div>
        </div>
        </div>        
 <?php } ?>
   
     
  
</div>
<script src="<?php echo $baseUrl;?>/public/projectScripts/index/project_list_grid.js" type="text/javascript"></script>
<script src="<?php echo $baseUrl;?>/public/js/jquery.mousewheel.js" type="text/javascript"></script>
<script>
$(document).ready(function(){
    return updateValues();
    
});
<!-- Below code is used to get mouse up-down event-->

$(document).mousewheel(function(event, delta) {
//    if (delta > 0)
//      alert(' up');
//    else if (delta < 0)
//      alert(' down');
    
 });


</script>
 
 
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Interested in <span id='callBackPrjName'>Parsvnath Paramount</span>?</h4>
      </div>
      <div class="modal-body">
        <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="callBackInputEmail" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Mobile No.</label>
    <input type="text" class="form-control" id="callBackInputMobile" placeholder="Mobile No.">
  </div>
  <input type="hidden"  id="callBackProjectId" >
</form>
      </div>
      <div class="modal-footer">
          <img id="callBackLoader" style="display:none;margin-right:20px;" src="<?php echo $baseUrl;?>/public/images/lightbox-ico-loading.gif">
          <button id="callBackSubmit" type="button" class="btn btn-danger" onclick="return submitCallBack()">GET CALL BACK</button>
               
      </div>
      
    </div>
  </div>
</div>



  
  