 <?php $baseUrl = $this->basePath(); ?>
  

<!---------Filteration bar----------->
<div class="filteration">
<div class="container">
  <div class="container-fluid bg-white">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><div style="color:#777; padding-top:15px; margin-right:30px;">Refine Results :</div></li>               
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Possession <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#"><input type="checkbox"> Ready to move</a></li>
            <li><a href="#"><input type="checkbox"> Upto 3 Months</a></li>
            <li><a href="#"><input type="checkbox"> Upto 6 Months</a></li>
            <li><a href="#"><input type="checkbox"> Upto 9 Months</a></li>            
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Property Type <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#"><input type="checkbox"> Apartment</a></li>
            <li><a href="#"><input type="checkbox"> Villa</a></li>
            <li><a href="#"><input type="checkbox"> Builder Floor</a></li>  
            <li><a href="#"><input type="checkbox"> Plot</a></li>           
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Budget <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">0</a></li>
            <li><a href="#">0</a></li>
            <li><a href="#">0</a></li>           
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Bedrooms <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#"><input type="checkbox"> 1 Bedroom</a></li>
            <li><a href="#"><input type="checkbox"> 2 Bedrooms</a></li>
            <li><a href="#"><input type="checkbox"> 3 Bedrooms</a></li>
            <li><a href="#"><input type="checkbox"> 4 Bedrooms</a></li>
            <li><a href="#"><input type="checkbox"> 4+ Bedrooms</a></li>           
          </ul>
        </li>
        <li><a href="#"><span class="glyphicon glyphicon-refresh"></span> Reset </a></li> 
      </ul>
     <!--right---> 
      <ul class="nav navbar-nav navbar-right"> 
      	<li><a href="projects.html"><span class="glyphicon glyphicon-th-list"></span> LIST</a></li>       
        <li><a href="projects-grid.html"><span class="glyphicon glyphicon-th-large"></span> GRID</a></li>
             
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</div>
</div>

  <div class="clearfix margin_top12"></div>
 
  <!---------Heading----------->
  
  <div class="insidepg-heading">
  <div class="container">
  <div class="page-header">
  <div class="clearfix margin_top4"></div>  
  <h3>New Residential Projects in Delhi<br> <small>Found a total of 102 projects.</small></h3> </div>
  </div>  
  </div>

<div id='searchProjects'>
    
<div class="content_fullwidth">
<div class="featured_section102">
<div class="container insidepg-proj-grid-row">
    <?php 
        $count = 0;
        foreach($this->searchResultArr as $searchResult){
        $count++;
    ?>
    <div class="one_fourth_less <?php if($count % 4 == 0){ echo 'last';}?> "  >    
		<a href="projects-detail.html"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['project_image']?>" alt="" /></a>
    	<h5><a href="projects-detail.html"><?php echo $searchResult['project_title']?></a> <em><?php echo $searchResult['address']?></em></h5>
        <div class="grid_type">
        4, 2 & 3 BHK ( 930 - 2385 sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `17</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 3.04 Crs</div>
        <div class="grid_button_right">
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
        
    </div><!-- end section -->
        
    <?php  
    
     if($count % 4 == 0 && $count != count($this->searchResultArr)){ ?>
         <div style="border-bottom: 4px double #ccc;">&nbsp;</div>
    <?php }
        if($count % 8 == 0){ ?>
        <div class="container insidepg-proj-row">
        <div class="clearfix margin_top3"></div> 
        <div class="row"><a style="float:left" href="#"><img src="<?php echo $baseUrl;?>/public/images/project/add-banner1.jpg"></a></div>
        <div class="clearfix margin_top3"></div> 
        </div>
    <?php }
        }
    ?>
    </div>
</div><!-- end featured section 102 -->
</div>
    
    
    
</div>
 
  
 



  
  