 <?php $baseUrl = $this->basePath(); ?>
  
  <div class="clearfix margin_top12"></div>
 
  <!---------Heading----------->
  
  <div class="insidepg-heading">
  <div class="container">
  <div class="page-header">
  <div class="clearfix margin_top4"></div>  
  <h3>New Residential Projects in Delhi<br> <small>Found a total of 102 projects.</small></h3> </div>
  </div>  
  </div>


<div class="clearfix"></div>
<div class="content_fullwidth">
<div class="featured_section102">
<div class="container insidepg-proj-grid-row">
   
    <div class="one_fourth_less">    
		<a href="projects-detail.html"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img1.jpg" alt="" /></a>
    	<h5><a href="projects-detail.html">Parsvnath Paramount</a> <em>Subhash Nagar , Delhi</em></h5>
        <div class="grid_type">
        4, 2 & 3 BHK ( 930 - 2385 sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `17</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 3.04 Crs
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
        
    </div><!-- end section -->
    
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img2.jpg" alt="" /></a>
    	<h5><a href="#">Eden Heights</a> <em>Sector 6, Dwarka , Delhi</em></h5>    
         <div class="grid_type">
        2, 3 & 4 BHK ( undefined sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `18</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 44.63 L
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img3.jpg" alt="" /></a>
    	<h5><a href="#">Supertech Golf Village</a> <em>Sec 22D Yamuna Exp.</em></h5>     
        <div class="grid_type">
         1, 2 & 3 BHK ( 480 - 1440 sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `17</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 16.1 L
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
    <div class="one_fourth_less last">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img4.jpg" alt="" /></a>
    	<h5><a href="#">Jaypee Greens Pavilion Heights</a> <em>Sector 128, Noida </em></h5>    
        <div class="grid_type">
        2, 3 & 4 BHK ( 1240 - 2500 sq ft )<br>
		<span class="grid_type_left_smltxt">Completed: Apr `15</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> Price on req.
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
	
    </div>
    <div class="clearfix"></div> 
    <div class="container insidepg-proj-grid-row">      
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img3.jpg" alt="" /></a>
    	<h5><a href="#">Supertech Golf Village</a> <em>Sec 22D Yamuna Exp.</em></h5>     
        <div class="grid_type">
         1, 2 & 3 BHK ( 480 - 1440 sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `17</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 16.1 L
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img4.jpg" alt="" /></a>
    	<h5><a href="#">Jaypee Greens Pavilion Heights</a> <em>Sector 128, Noida </em></h5>    
        <div class="grid_type">
        2, 3 & 4 BHK ( 1240 - 2500 sq ft )<br>
		<span class="grid_type_left_smltxt">Completed: Apr `15</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> Price on req.
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img1.jpg" alt="" /></a>
    	<h5><a href="#">Parsvnath Paramount</a> <em>Subhash Nagar , Delhi</em></h5>
        <div class="grid_type">
        4, 2 & 3 BHK ( 930 - 2385 sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `17</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 3.04 Crs
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
    <div class="one_fourth_less last">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img2.jpg" alt="" /></a>
    	<h5><a href="#">Eden Heights</a> <em>Sector 6, Dwarka , Delhi</em></h5>    
         <div class="grid_type">
        2, 3 & 4 BHK ( undefined sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `18</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 44.63 L
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
</div>
</div><!-- end featured section 102 -->





</div>

 <!---Add-Banner--->  
 <div class="container insidepg-proj-row">
 <div class="clearfix margin_top5"></div> 
 	 <div class="row"><a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/add-banner1.jpg"></a></div>
 <div class="clearfix margin_top3"></div> 
 </div>
   
<div class="clearfix"></div>
   
<div class="content_fullwidth">
<div class="featured_section102">
<div class="container insidepg-proj-grid-row">
   
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img1.jpg" alt="" /></a>
    	<h5><a href="#">Parsvnath Paramount</a> <em>Subhash Nagar , Delhi</em></h5>
        <div class="grid_type">
        4, 2 & 3 BHK ( 930 - 2385 sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `17</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 3.04 Crs
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
        
    </div><!-- end section -->
    
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img2.jpg" alt="" /></a>
    	<h5><a href="#">Eden Heights</a> <em>Sector 6, Dwarka , Delhi</em></h5>    
         <div class="grid_type">
        2, 3 & 4 BHK ( undefined sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `18</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 44.63 L
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img3.jpg" alt="" /></a>
    	<h5><a href="#">Supertech Golf Village</a> <em>Sec 22D Yamuna Exp.</em></h5>     
        <div class="grid_type">
         1, 2 & 3 BHK ( 480 - 1440 sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `17</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 16.1 L
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
    <div class="one_fourth_less last">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img4.jpg" alt="" /></a>
    	<h5><a href="#">Jaypee Greens Pavilion Heights</a> <em>Sector 128, Noida </em></h5>    
        <div class="grid_type">
        2, 3 & 4 BHK ( 1240 - 2500 sq ft )<br>
		<span class="grid_type_left_smltxt">Completed: Apr `15</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> Price on req.
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
	
    </div>
    <div class="clearfix"></div> 
    <div class="container insidepg-proj-grid-row">      
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img3.jpg" alt="" /></a>
    	<h5><a href="#">Supertech Golf Village</a> <em>Sec 22D Yamuna Exp.</em></h5>     
        <div class="grid_type">
         1, 2 & 3 BHK ( 480 - 1440 sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `17</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 16.1 L
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img4.jpg" alt="" /></a>
    	<h5><a href="#">Jaypee Greens Pavilion Heights</a> <em>Sector 128, Noida </em></h5>    
        <div class="grid_type">
        2, 3 & 4 BHK ( 1240 - 2500 sq ft )<br>
		<span class="grid_type_left_smltxt">Completed: Apr `15</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> Price on req.
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
    <div class="one_fourth_less">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img1.jpg" alt="" /></a>
    	<h5><a href="#">Parsvnath Paramount</a> <em>Subhash Nagar , Delhi</em></h5>
        <div class="grid_type">
        4, 2 & 3 BHK ( 930 - 2385 sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `17</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 3.04 Crs
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
    <div class="one_fourth_less last">    
		<a href="#"><img src="<?php echo $baseUrl;?>/public/images/project/proj-img2.jpg" alt="" /></a>
    	<h5><a href="#">Eden Heights</a> <em>Sector 6, Dwarka , Delhi</em></h5>    
         <div class="grid_type">
        2, 3 & 4 BHK ( undefined sq ft )<br>
		<span class="grid_type_left_smltxt">Possession Date: Dec `18</span>
        </div>
        <div class="grid_button">
        <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> 44.63 L
</div>
        <div class="grid_button_right">
        
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
    </div><!-- end section -->
    
</div>
</div><!-- end featured section 102 -->





</div> 


  
  