 <?php $baseUrl = $this->basePath(); 
 $container             = new Zend\Session\Container('compareProjects');
 $allCompareProjects    = (count($container->allCompareProjects)) ? $container->allCompareProjects : [];
 
// echo '<pre>';print_r($allCompareProjects);exit;
 ?>

<!---------Filteration bar----------->
<div class="filteration">
<div class="container">
  <div class="container-fluid bg-white">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><div style="color:#777; padding-top:15px; margin-right:30px;">Refine Results :</div></li>               
        <li class="dropdown">
            <a  class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" ><span id="possessionText" >Possession</span><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a style="cursor:default;"><input type="checkbox" onchange="managePossession('readyToMoveIn')" id="readyToMoveIn" value="readyToMoveIn" class="cursor"><span id="text_readyToMoveIn" > Ready to move in</span></a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="managePossession('upto3month')" id="upto3month" value="upto3month" class="cursor"><span id="text_upto3month" > Upto 3 Months</span></a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="managePossession('upto6month')" id="upto6month" value="upto6month" class="cursor"><span id="text_upto6month" > Upto 6 Months</span></a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="managePossession('upto9month')" id="upto9month" value="upto9month" class="cursor"><span id="text_upto9month" > Upto 9 Months</span></a></li>                  
          </ul>
        </li>
        <?php if(count($this->propertyTypeArr)){ ?>
        <li class="dropdown">
          <a class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" id="propertyTypeFilter">Property Type <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <?php
              foreach($this->propertyTypeArr as $propertyType){?>
                  <li><a style="cursor:default;"><input type="checkbox"  onchange="managePropertyType(<?php echo $propertyType['id'];?>)" id="propertyType_<?php echo $propertyType['id'];?>" value="<?php echo $propertyType['id'];?>" class="cursor"> <?php echo $propertyType['property_type'];?></a></li>
             <?php  }?>         
          </ul>
        </li>
        <?php } ?>    
        
        <li class="dropdown">
          <a class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" id="budgetFilter">Budget <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(2500000)" id="budget_2500000" value="2500000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 25 L</a></li> 
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(5000000)" id="budget_5000000" value="5000000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 50 L</a></li> 
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(7500000)" id="budget_7500000" value="7500000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 75 L</a></li> 
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(10000000)" id="budget_10000000" value="10000000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 1.00 Cr</a></li> 
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(15000000)" id="budget_15000000" value="15000000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 1.50 Cr</a></li> 
              <li><a style="cursor:default;"><input type="checkbox" onchange="manageBudget(20000000)" id="budget_20000000" value="20000000" class="cursor">&nbsp;&nbsp;<span class="rupee">`</span> 2.00 Cr</a></li> 
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle cursor" data-toggle="dropdown" role="button" aria-expanded="false" id="bedroomFilter">Bedrooms <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a style="cursor:default;"><input type="checkbox" onchange="manageBedrooms(1)" id="bedroom_1" value="1" class="cursor"> 1 Bedroom</a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="manageBedrooms(2)" id="bedroom_2" value="2" class="cursor"> 2 Bedrooms</a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="manageBedrooms(3)" id="bedroom_3" value="3" class="cursor"> 3 Bedrooms</a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="manageBedrooms(4)" id="bedroom_4" value="4" class="cursor"> 4 Bedrooms</a></li>
            <li><a style="cursor:default;"><input type="checkbox" onchange="manageBedrooms(5)" id="bedroom_5" value="4+" class="cursor"> 4+ Bedrooms</a></li>            
          </ul>
        </li>
        <li><a ><span class="glyphicon glyphicon-refresh"></span> <span style="cursor:pointer" id="resetFilter">Reset</span> </a></li> 
      </ul>
     <!--right---> 
      <ul class="nav navbar-nav navbar-right"> 
        <li><a onclick="changeView('list')" class="cursor"><span class="glyphicon glyphicon-th-list"></span> LIST</a></li>       
        <li><a onclick="changeView('grid')" class="cursor"><span class="glyphicon glyphicon-th-large"></span> GRID</a></li>
        <li><a onclick="redirectUrl(1)" class="cursor"><span class="glyphicon glyphicon-map-marker"></span> MAP</a></li>    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</div>
</div>

 
  <div class="clearfix margin_top12"></div>
  
  <!---------Heading----------->
  <input type="hidden" id="baseUrl" value="<?php echo $baseUrl;?>">
  <input type="hidden" id="pageName" value="project-list">
  <input type="hidden" id="builderDetailId" value="">
  <input type="hidden" id="PossessionFilters" value="<?php echo $this->possession;?>">
  <input type="hidden" id="PropertyTypeFilters" value="<?php echo $this->propertyType;?>">
  <input type="hidden" id="BudgetFilters" value="<?php echo $this->budget;?>">
  <input type="hidden" id="BedroomFilters" value="<?php echo $this->bedroom;?>">
  
  <div class="insidepg-heading">
  <div class="container">
  <div class="page-header">
  <div class="clearfix margin_top4"></div>  
  <h3>Residential Projects <?php if($this->cityName!=''){ echo 'in '.$this->cityName; }else '';?><br> <small>Found a total of <?php echo count($this->searchResultArr)?> projects.</small></h3> </div>
  </div>  
  </div>
 
  <!---------All Project-----------> 
  

  <div id='searchProjects'>
     <?php if($this->viewType == 'list'){ 
        if(count($this->searchResultArr)){
            $ii = 0;
            foreach($this->searchResultArr as $searchResult){
                
                
//                echo '<pre>';print_r($searchResult);exit;
                
                
    ?>            
            <div class="container insidepg-proj-row"> 
              <div class="row">
                  <div class="col-md-3  insidepg-proj-img-box"><a href="<?php echo $baseUrl;?>/projects-in-<?php echo strtolower($searchResult['citySlug'])?>/<?php echo $searchResult['projectSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['project_image']?>" class="img-responsive"></a></div>
              <div class="col-md-7 insidepg-proj-detail">
              <div class="bs-example" data-example-id="bordered-table">
               <h4 id="tables-bordered"><a href="<?php echo $baseUrl;?>/projects-in-<?php echo strtolower($searchResult['citySlug'])?>/<?php echo $searchResult['projectSlug']?>"><?php echo $searchResult['project_title']?></a></h4>
              <p><?php echo $searchResult['address']?></p>
                <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th>PROPERTY</th>
                        <th>SIZE</th>
                        <th>BUILDER PRICE</th>
                      </tr>
                    </thead>
                    <tbody>
                    <?php 
                    $pp = 1111;  
                    foreach($searchResult['floor_plans'] as $floor_plan){?>
                        <tr onClick="showRow('subrow<?php echo $searchResult["project_id"].$pp;?>',this);" id='head<?php echo $searchResult["project_id"].$pp;?>' style="cursor:pointer;">
                            <td><?php echo $floor_plan['BHK'];?> Bedroom &nbsp;<span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span></td>
                            <td><?php echo $floor_plan['min_size']; if(count($floor_plan['floor_plan_list'])>1) { echo ' - '.$floor_plan['max_size'];}      echo ' '.$floor_plan['size_unit']; ?></td>
            <td><span class="rupee">`</span> <?php echo $floor_plan['min_price'];if(count($floor_plan['floor_plan_list'])>1) {?> - <span class="rupee">`</span> <?php echo $floor_plan['max_price']; }?></td>
                        </tr>
                        <?php if(count($floor_plan['floor_plan_list'])){?>
                            <tr class="subrow<?php echo $searchResult["project_id"].$pp;?> hide-row-bg" onClick="hideRow('subrow<?php echo $searchResult["project_id"].$pp;?>','head<?php echo $searchResult["project_id"].$pp;?>');" style="cursor:pointer;display:none;">
                                <td><?php echo $floor_plan['BHK'];?> Bedroom &nbsp;<span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span></td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                            <?php foreach($floor_plan['floor_plan_list'] as $floor_plan_list){?>
                            <tr class="subrow<?php echo $searchResult["project_id"].$pp;?>" style="display:none;">
                                <td class="hide-cell-pad"><?php echo $floor_plan_list['plan_type'];?> </th>
                                <td class="hide-cell-pad"><?php echo $floor_plan_list['size'];?> <?php echo $floor_plan_list['unit'];?></td>
                                <td class="hide-cell-pad"><span class="rupee">`</span> <?php echo $floor_plan_list['price'];?> <?php echo $floor_plan_list['price_unit'];?></td>
                            </tr>
                      <?php }}
                      $pp++;
                    }?>  
                    </tbody>
                </table>
              </div>
              </div>
              <div class="col-md-2 insidepg-proj-builder">
              <div class="row insidepg-proj-builder-img" align="center"><a href="<?php echo $baseUrl;?>/builders/<?php echo $searchResult['builderSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['builder_image']?>"  class="img-responsive"></a></div>
            <div class="row insidepg-proj-builder-price text-center"><div class="proj-price-text"><span class="rupee">`</span>  <?php echo $searchResult['min_floor_plan_price'];?> - <span class="rupee">`</span> <?php echo $searchResult['max_floor_plan_price'];?></div> POSSESSION <?php echo date('M', strtotime($searchResult['possession']))?> `<?php echo date('Y', strtotime($searchResult['possession']))?></div>     
              <div class="clearfix"></div> 
              <div class="row projlistpg-compare-pad cursor" align="center" id="addCompareDiv_<?php echo $searchResult['project_id'];?>">
                <?php if(!in_array($searchResult['project_id'],$allCompareProjects)) { ?>
                  <a class="addToCompare" data-toggle="tooltip" title="Maximum 3 Projects" onclick='addRemoveCompare(<?php echo $searchResult["project_id"];?>)'><span class="glyphicon glyphicon-unchecked" aria-hidden="true" ></span> Add to Compare</a>
                <?php }else{?>  
              <a onclick='addRemoveCompare(<?php echo $searchResult["project_id"];?>)'><span class="glyphicon glyphicon-check" aria-hidden="true" ></span> Remove from Compare</a>
                <?php }?>
              </div>
              <div class="row" align="center"><button type="button" class="btn btn-danger btn-sm" onclick="return getCallBAck('<?php echo $searchResult['project_id']?>','<?php echo $searchResult['project_title']?>')">GET CALL BACK</button></div>
              </div>
              </div>
              </div>  
<?php
        $ii++; 
        if($ii % 4 == 0 && $ii != count($this->searchResultArr)){
            $container = new Zend\Session\Container('searchSessionFields');
            $bannerArr = $container->projectBanner;
            shuffle($bannerArr);
            ?>
    <!---Add-Banner--->  
     <div class="container insidepg-proj-row">
     <div class="clearfix margin_top2"></div> 
         <div class="row"><a style="float:left" href="<?php echo $baseUrl;?>/projects/<?php echo $bannerArr[0]['projectSlug']?>"><img width="1160" height="100" src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $bannerArr[0]['banner_image']?>"></a></div>
     <div class="clearfix margin_top3"></div> 
     </div>
    <?php }  
            }
        }
      }else{ ?>
          
        <div class="content_fullwidth">
        <div class="featured_section102">
        <div class="container insidepg-proj-grid-row">
            <?php 
        $count = 0;
        foreach($this->searchResultArr as $searchResult){
        $count++;
        $bhkArray = [];
        if($searchResult['has_1BHK']==1)
           $bhkArray[] = 1;
        if($searchResult['has_2BHK']==1)
           $bhkArray[] = 2;
        if($searchResult['has_3BHK']==1)
           $bhkArray[] = 3;
        if($searchResult['has_4BHK']==1)
           $bhkArray[] = 4;
        if($searchResult['has_5BHK']==1)
           $bhkArray[] = 5;
        $bhkStr = '';
        $pp=0;
   // echo '<pre>';print_r($bhkArray);exit;
        foreach($bhkArray as $bhk){
            if($bhkStr!=''){
                if($pp==count($bhkArray)-1)
                    $bhkStr .= ' & ';
                else
                    $bhkStr .= ', ';
            }
            $bhkStr .= $bhk;
            $pp++;
        }
//        echo $bhkStr;exit;
    ?>
        <div class="one_fourth_less <?php if($count % 4 == 0){ echo 'last';}?> "  >    
            <a href="<?php echo $baseUrl;?>/projects-in-<?php echo strtolower($searchResult['citySlug'])?>/<?php echo $searchResult['projectSlug']?>"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['project_image']?>" alt="" /></a>
            <h5><a href="<?php echo $baseUrl;?>/projects-in-<?php echo strtolower($searchResult['citySlug'])?>/<?php echo $searchResult['projectSlug']?>"><?php echo $searchResult['project_title']?></a> <em><?php echo $searchResult['city_name'].', '.$searchResult['state_name']?></em></h5>
            
            <div class="grid_type">
            <?php echo $bhkStr;?> BHK ( <?php  echo $searchResult['min_floor_plan_size']?> - <?php  echo $searchResult['max_floor_plan_size']?> sq ft )<br>
            <span class="grid_type_left_smltxt">Possession Date: <?php echo date('M', strtotime($searchResult['possession']))?> `<?php echo date('Y', strtotime($searchResult['possession']))?></span>
            </div>
            <div class="grid_button">
            <div class="grid_button_left"> <span class="grid_button_left_smltxt">STARTING PRICE</span><br> <span class="rupee">`</span> <?php  echo $searchResult['min_floor_plan_price']?></div>
            <div class="grid_button_right cursor" id="addCompareDiv_<?php echo $searchResult['project_id'];?>">
                <?php if(!in_array($searchResult['project_id'],$allCompareProjects)) { ?>
                  <a class="addToCompare" data-toggle="tooltip" title="Maximum 3 Projects" onclick='addRemoveCompare(<?php echo $searchResult["project_id"];?>)'><span class="glyphicon glyphicon-unchecked" aria-hidden="true" ></span> Add to Compare</a>
                <?php }else{?>  
              <a onclick='addRemoveCompare(<?php echo $searchResult["project_id"];?>)'><span class="glyphicon glyphicon-check" aria-hidden="true" ></span> Remove from Compare</a>
                <?php }?>
            </div>
            </div>
            <div class="row projlistpg-compare-pad"><button type="button" class="btn btn-danger btn-sm" data-toggle="modal" onclick="return getCallBAck('<?php echo $searchResult['project_id']?>','<?php echo $searchResult['project_title']?>')">GET CALL BACK</button></div>
        </div>
        
    <?php  
    
     if($count % 4 == 0 && $count != count($this->searchResultArr)){ ?>
         <div style="border-bottom: 4px double #ccc;">&nbsp;</div>
    <?php }
        if($count % 8 == 0){
            $container = new Zend\Session\Container('searchSessionFields');
            $bannerArr = $container->projectBanner;
            if(count($bannerArr))
            shuffle($bannerArr);
        ?>
        <div class="container insidepg-proj-row">
        <div class="clearfix margin_top3"></div> 
        <div class="row"><a style="float:left" href="<?php echo $baseUrl;?>/projects/<?php echo $bannerArr[0]['projectSlug']?>"><img width="1160" height="100" src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $bannerArr[0]['banner_image']?>"></a></div>
        <div class="clearfix margin_top3"></div> 
        </div>
    <?php }
        }
    ?>   
        </div>
        </div>
        </div>        
 <?php } ?>
   
     
  
</div>
  <script>
   $(function () {
    $('[data-toggle="tooltip"]').tooltip();
   })
   var projectListPage = window.location.pathname;
   function shuffleProjectBanner(){
        
        <?php $container = new Zend\Session\Container('searchSessionFields');
        $bannerArr = $container->projectBanner;
        if(count($bannerArr))
        shuffle($bannerArr); ?>
        var returnArr = new Array();
        returnArr['project_id']      = '<?php echo $bannerArr[0]['project_id']?>';
        returnArr['banner_image']    = '<?php echo $bannerArr[0]['banner_image']?>';
        return returnArr;
    }
    var CompareProjectsArr = [];
    <?php if(count($allCompareProjects)){ 
        foreach($allCompareProjects as $projects){?>
            CompareProjectsArr.push(<?php echo $projects;?>);
    <?php }} ?>
  </script>

<script src="<?php echo $baseUrl;?>/public/js/jquery.mousewheel.js" type="text/javascript"></script>

<script>
$(document).ready(function(){
    return updateValues();
});
<?php 
        $containerrrr = new Zend\Session\Container('searchSessionFields');
    ?>
$(document).ready(function(){
    $('#pageTitle').text('Aadinath | <?php if($containerrrr->searchCityName!='') echo 'Projects in '.$containerrrr->searchCityName; else echo 'Projects'; ?> ');
});

$(document).mousewheel(function(event, delta) {
//    if (delta > 0)
//      alert(' up');
//    else if (delta < 0)
//      alert(' down');
    
 });

</script>
 

<script src="<?php echo $baseUrl;?>/public/projectScripts/index/project_list_grid.js" type="text/javascript"></script>
  