 <?php $baseUrl = $this->basePath(); ?>


  

 
  <div class="clearfix margin_top12"></div>
  
  <!---------Heading----------->
  
  <div class="insidepg-heading">
  <div class="container">
  <div class="page-header">
  <div class="clearfix margin_top4"></div>  
  <h3>New Residential Projects in Delhi<br> <small>Found a total of <?php echo count($this->searchResultArr)?> projects.</small></h3> </div>
  </div>  
  </div>
 
  <!---------All Project-----------> 
  


<?php if(count($this->searchResultArr)){
    foreach($this->searchResultArr as $searchResult){?>
        
        <div class="container insidepg-proj-row"> 
        <div class="row">
        <div class="col-md-3  insidepg-proj-img-box"><a href="projects-detail.html"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['project_image']?>" class="img-responsive"></a></div>
        <div class="col-md-7 insidepg-proj-detail">
        <div class="bs-example" data-example-id="bordered-table">
         <h4 id="tables-bordered"><a href="projects-detail.html"><?php echo $searchResult['project_title']?></a></h4>
        <p><?php echo $searchResult['address']?></p>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>PROPERTY</th>
                <th>SIZE</th>
                <th>BUILDER PRICE</th>
              </tr>
            </thead>
            <tbody>
                <?php $floorSizeArr = array();
                foreach($searchResult['floor_plans'] as $floor_plan){?>
                    <tr>
                    <td><?php echo $floor_plan['plan_type'];?></th>
                    <td><?php echo $floor_plan['plan_type'].' '.$floor_plan['unit'];?></td>
                    <td><span class="rupee">`</span> <?php echo $floor_plan['price'];?></td>
                  </tr> 
               <?php $floorSizeArr[]= $floor_plan['price'];
                }?>
                  
            </tbody>
          </table>
        </div>
        </div>
        <div class="col-md-2 insidepg-proj-builder">
        <div class="row insidepg-proj-builder-img" align="center"><a href="#"><img src="<?php echo $baseUrl;?>/public/uploadfiles/<?php echo $searchResult['builder_image']?>"  class="img-responsive"></a></div>
        <div class="row insidepg-proj-builder text-center"><span class="proj-price-text"><span class="rupee">`</span>  <?php echo min($floorSizeArr);?> - <span class="rupee">`</span> <?php echo max($floorSizeArr);?></span>
          POSSESSION Dec `17</div>
          <div class="row text-center"><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal1">GET CALL BACK</button></div>
        </div>
        </div>
        </div>
        
        
 <?php   }
}else{?>
    
  No Result Found.
    
    
<?php }?>





  
  
  
<!---Add-Banner--->  
 <div class="container insidepg-proj-row">
 <div class="clearfix margin_top2"></div> 
 	 <div class="row"><a style="float:left" href="#"><img src="<?php echo $baseUrl;?>/public/images/project/add-banner1.jpg"></a></div>
 <div class="clearfix margin_top3"></div> 
 </div>
  



  
  