<?php $baseUrl = $this->basePath(); ?>

<div class="container">
	<div class="margin_top12"></div>
	<div class="page-header">
  <div class="clearfix"></div>  
  <h3>Vaastu for Home</h3></div>
	
   
<div class="container margin_top2">
<div class="content_left">    	
        
        <p style="text-align:justify;"><br>Vaastu is a set of principles that helps home owners lead a happy and peaceful life in their abode. The doctrine of Vaastu is related to architecture and the designs are based on directional arrangements. Vaastu guidelines can be applied during the construction of homes, offices, temples and other buildings and help bring about positive energy and general well-being for the home owner. As such, it is important to keep in mind few tips while searching for or building your ideal house.</p>        
        
        
        <div class="clearfix margin_top3"></div>
        
       <h4>General Tips:</h4> 
        <p style="text-align:justify;">
        <div class="margin_top1"></div>
        - The entrance to the house should be towards the east as it is considered an auspicious direction. The entrance should also be<br>&nbsp; well-kept and nicely decorated<br>
        - The north direction signifies prosperity, as such this part of the house should not be blocked in any way<br>
        - Make sure to never grow a Cactus plant in the house<br>
        - Hinges on doors should work smoothly and should not make noise<br>
        - If the house has a slope, it should be from south to north or from west to east only<br>
        - Avoid putting up paintings or pictures that depict violence or sorrow</p>
                
        
          <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Bedrooms:</h4>
        <p style="text-align:justify;">
        <div class="margin_top1"></div>
        - The master bedroom in the house should always be in the south-west direction and not in the north<br>
        - One should always sleep with their head towards the south<br>
        - Make sure the bed is not placed directly below a beam<br>
        - Bedrooms should be absolutely clutter free, especially the area around where you place your head while sleeping</p>
        
        
        
         <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Children's Room:</h4>
        <p style="text-align:justify;">
        <div class="margin_top1"></div>
        - Children's rooms should be constructed in the northwest corner of the house<br>
        - Avoid sticking furniture to the wall as it blocks the flow of positive energy<br>
        - The colour scheme in a kid’s room should be mild yet cheerful<br>
        - The study table should be placed in a way so that the child faces the east, north or north eastern corner of the room. The<br>&nbsp; computer should be kept in the southwest corner</p>
        
         <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Living Room:</h4>
        <p style="text-align:justify;">
        <div class="margin_top1"></div>
        - The living room should always be in the north direction<br>
        - Air-conditioners should be placed in the west and avoided being put in the southeast direction<br>
        - The chairs of dining tables must be even-numbered<br>
        - The south and west corners of the room are ideal for keeping furniture</p>
        
        <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Kitchen:</h4>
        <p style="text-align:justify;">
        <div class="margin_top1"></div>
        - The kitchen should be located in the southeast corner of the house. Northwest corner is also an ideal location for a kitchen<br>
        - All cooking should be done while facing east or north<br>
        - South, west, southeast and northwest are the ideal locations to place the refrigerator<br>
        - Kitchen appliances such as mixers, juicers, microwaves and toasters should be kept in the southeast corner<br>
        - Make sure the kitchen is equipped for good and adequate cross-ventilation</p>
        
         <!-- end section -->
        <div class="page-header">&nbsp;</div>
        <h4 class="margin_top3">Bathroom:</h4>
        <p style="text-align:justify;">
        <div class="margin_top1"></div>
        - Bathrooms should be constructed in the north-west direction<br>
        - Make sure the bathroom has sufficient ventilation and natural lighting<br>
        - Sanitary and bath fittings must be of good quality and should work smoothly over the years. If broken, they should be fixed<br>&nbsp; immediately<br>
        - Always keep the bath and toilet areas neat and clean<br>
        </p>
</div><!-- end content left side -->


<!-- right sidebar starts -->
<div class="right_sidebar">
	<div class="sidebar_widget">    
    	<div class="sidebar_title">
        <div class="last stcode_title5"><h3><span class="line2"></span><span class="line"></span><span class="text">Quick Links</span></h3></div>
        </div>        
		<ul class="arrows_list1">        
            <li><a href="<?php echo $baseUrl?>/faq"><i class="fa fa-angle-right"></i> Property Buying Steps</a></li>
            <li><a href="<?php echo $baseUrl?>/home-loan"><i class="fa fa-angle-right"></i> Home Loan</a></li>
            <li><a href="<?php echo $baseUrl?>/vaastu-tips"><i class="fa fa-angle-right"></i> Vaastu Tips</a></li>
            <li><a href="<?php echo $baseUrl?>/emi-calculator"><i class="fa fa-angle-right"></i> EMI Calculator</a></li>
            <li><a href="<?php echo $baseUrl?>/nri-services"><i class="fa fa-angle-right"></i> NRI services</a></li>
            <li><a href="#"><i class="fa fa-angle-right"></i> Real Estate News</a></li> 
		</ul>
        
         <div class="margin_top8"></div>    
    	<ul class="arrows_list1">        
            <li><a href="#"><img src="<?php echo $baseUrl?>/public/images/latest-Project/lp3.jpg"></a></li>
            <li class="margin_top5"><a href="#"><img src="<?php echo $baseUrl?>/public/images/latest-Project/lp1.jpg"></a></li>
            <li class="margin_top5"><a href="#"><img src="<?php echo $baseUrl?>/public/images/latest-Project/lp2.jpg"></a></li>           
		</ul>	
       
	</div><!-- end section -->
    
    
    
</div><!-- end right sidebar -->

</div>
    
    <!-- end section -->
    
</div>
    
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
    $(document).ready(function(){
        $('#pageTitle').text('Aadinath | Vaastu Tips');
    });
    </script>


<!---End of Builder--->



  
  